#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace widgetsDemo{

namespace R{
    namespace animator{
        enum : int {
            press_scale = 0x7f010000,
        };
    }/*namespace animator*/

    namespace color{
        enum : int {
            accent = 0x7f020000,
            accent2 = 0x7f020001,
            accent_pressed = 0x7f020002,
            btn_normal = 0x7f020003,
            card_bg = 0x7f020004,
            card_bg2 = 0x7f020005,
            card_stroke = 0x7f020006,
            danger = 0x7f020007,
            demo_bg = 0x7f020008,
            divider = 0x7f020009,
            good = 0x7f02000a,
            grad_amber_a = 0x7f02000b,
            grad_amber_b = 0x7f02000c,
            grad_blue_a = 0x7f02000d,
            grad_blue_b = 0x7f02000e,
            grad_teal_a = 0x7f02000f,
            grad_teal_b = 0x7f020010,
            grad_violet_a = 0x7f020011,
            grad_violet_b = 0x7f020012,
            text_disabled = 0x7f020013,
            text_primary = 0x7f020014,
            text_secondary = 0x7f020015,
            warn = 0x7f020016,
        };
    }/*namespace color*/

    namespace dimen{
        enum : int {
            body_size = 0x7f030000,
            btn_corner = 0x7f030001,
            card_gap = 0x7f030002,
            card_padding = 0x7f030003,
            card_radius = 0x7f030004,
            chip_corner = 0x7f030005,
            page_padding = 0x7f030006,
            row_gap = 0x7f030007,
            section_size = 0x7f030008,
            title_size = 0x7f030009,
        };
    }/*namespace dimen*/

    namespace drawable{
        enum : int {
            btn_demo = 0x7f040000,
            btn_outline = 0x7f040001,
            btn_primary = 0x7f040002,
            card_bg = 0x7f040003,
            chip_bg = 0x7f040004,
            circle_accent = 0x7f040005,
            ripple_demo = 0x7f040006,
            tile_amber = 0x7f040007,
            tile_blue = 0x7f040008,
            tile_teal = 0x7f040009,
            tile_violet = 0x7f04000a,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            anim_combo = 0x7f050000,
            anim_fade = 0x7f050001,
            anim_move = 0x7f050002,
            anim_reset = 0x7f050003,
            anim_rotate = 0x7f050004,
            anim_scale = 0x7f050005,
            anim_target = 0x7f050006,
            avd_img = 0x7f050007,
            bar_a = 0x7f050008,
            bar_b = 0x7f050009,
            bar_below = 0x7f05000a,
            btn_default = 0x7f05000b,
            btn_dialog = 0x7f05000c,
            btn_outline = 0x7f05000d,
            btn_ripple = 0x7f05000e,
            btn_toast = 0x7f05000f,
            car_center = 0x7f050010,
            car_left = 0x7f050011,
            car_right = 0x7f050012,
            carousel = 0x7f050013,
            chart_container = 0x7f050014,
            checkbox = 0x7f050015,
            chrono = 0x7f050016,
            chrono_toggle = 0x7f050017,
            cl_bar_box = 0x7f050018,
            cl_barrier = 0x7f050019,
            cl_bias_left = 0x7f05001a,
            cl_bias_right = 0x7f05001b,
            cl_chain_a = 0x7f05001c,
            cl_chain_b = 0x7f05001d,
            cl_chain_c = 0x7f05001e,
            cl_demo = 0x7f05001f,
            cl_fill = 0x7f050020,
            cl_flow = 0x7f050021,
            cl_flow_box = 0x7f050022,
            cl_guide_box = 0x7f050023,
            cl_h_guideline = 0x7f050024,
            cl_ratio = 0x7f050025,
            cl_v_guideline = 0x7f050026,
            cpk_a = 0x7f050027,
            cpk_b = 0x7f050028,
            cpk_c = 0x7f050029,
            cs_next = 0x7f05002a,
            cs_prev = 0x7f05002b,
            cs_rest = 0x7f05002c,
            cs_spr_a = 0x7f05002d,
            cs_spr_b = 0x7f05002e,
            cs_spr_c = 0x7f05002f,
            csi_a = 0x7f050030,
            csi_b = 0x7f050031,
            csi_c = 0x7f050032,
            dt_calview = 0x7f050033,
            dt_calview_mat = 0x7f050034,
            dt_calview_mat_val = 0x7f050035,
            dt_calview_val = 0x7f050036,
            dt_clock = 0x7f050037,
            dt_dp = 0x7f050038,
            dt_dp_cal = 0x7f050039,
            dt_dp_cal_val = 0x7f05003a,
            dt_dp_val = 0x7f05003b,
            dt_tp_clock = 0x7f05003c,
            dt_tp_clock_val = 0x7f05003d,
            dt_tp_spinner = 0x7f05003e,
            dt_tp_spinner_val = 0x7f05003f,
            edit_num = 0x7f050040,
            edit_pwd = 0x7f050041,
            edit_text = 0x7f050042,
            end = 0x7f050043,
            fl_1 = 0x7f050044,
            fl_2 = 0x7f050045,
            fl_3 = 0x7f050046,
            fl_4 = 0x7f050047,
            fl_5 = 0x7f050048,
            fl_6 = 0x7f050049,
            g_begin = 0x7f05004a,
            g_end = 0x7f05004b,
            g_pct = 0x7f05004c,
            list_rv = 0x7f05004d,
            marquee_tv = 0x7f05004e,
            ml_box1 = 0x7f05004f,
            ml_box2 = 0x7f050050,
            ml_box3 = 0x7f050051,
            ml_carousel = 0x7f050052,
            ml_demo = 0x7f050053,
            np_speed = 0x7f050054,
            np_temp = 0x7f050055,
            np_value_tv = 0x7f050056,
            pager = 0x7f050057,
            progress_h = 0x7f050058,
            qr = 0x7f050059,
            radio_a = 0x7f05005a,
            radio_b = 0x7f05005b,
            radiogroup = 0x7f05005c,
            rating = 0x7f05005d,
            rating2 = 0x7f05005e,
            result_tv = 0x7f05005f,
            seekbar = 0x7f050060,
            span_tv = 0x7f050061,
            spinner = 0x7f050062,
            spinner1 = 0x7f050063,
            start = 0x7f050064,
            switch1 = 0x7f050065,
            tabs = 0x7f050066,
            toggle = 0x7f050067,
            tr_backward = 0x7f050068,
            tr_forward = 0x7f050069,
            vt_grow = 0x7f05006a,
            vt_pop = 0x7f05006b,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            main = 0x7f060000,
            page_animation = 0x7f060001,
            page_buttons = 0x7f060002,
            page_constraint = 0x7f060003,
            page_datetime = 0x7f060004,
            page_images = 0x7f060005,
            page_lists = 0x7f060006,
            page_misc = 0x7f060007,
            page_motion = 0x7f060008,
            page_progress = 0x7f060009,
            page_text = 0x7f06000a,
        };
    }/*namespace layout*/

    namespace mipmap{
        enum : int {
            demo_photo = 0x7f070000,
            ic_placeholder = 0x7f070001,
        };
    }/*namespace mipmap*/

    namespace string{
        enum : int {
            app_title = 0x7f080000,
            sec_buttons = 0x7f080001,
            sec_choice = 0x7f080002,
            sec_chrono = 0x7f080003,
            sec_progress = 0x7f080004,
            tap_hint = 0x7f080005,
        };
    }/*namespace string*/

    namespace xml{
        enum : int {
            scene_carousel = 0x7f090000,
            scene_constraint = 0x7f090001,
        };
    }/*namespace xml*/

};//endof namespace R

}//endof namespace
