// Regression tests for the pak-font loading routes (no AOSP counterpart —
// coretests reaches fonts via instrumentation assets; these pin the cdroid
// contracts):
//  - Typeface::createFromAsset: per-path instance cache (repeated calls return
//    the SAME pointer), and the loaded face actually drives measurement.
//  - Context::getFont(R.font.<name>): the arsc resource route
//    (openNonAsset) resolves to the same family.
//
// The exact-width font lives in the gui_test pak twice on purpose:
//   assets/font/... (asset route, "assets/" zip prefix) and
//   font/...        (R.font resource route, zip root — aapt2 compiles font/)
#include <gtest/gtest.h>
#include <core/app.h>
#include <core/typeface.h>
#include <text/textpaint.h>
#include <text/String.h>
#include "R.h"

using namespace cdroid;

TEST(CoreTypefaceTest, createFromAsset_returnsCachedInstancePerPath) {
    const std::string path = "font/StaticLayoutLineBreakingTestFont.ttf";
    Typeface* first = Typeface::createFromAsset(path);
    ASSERT_NE(nullptr, first);
    EXPECT_EQ(first, Typeface::createFromAsset(path));
    EXPECT_STREQ("Sample Font", first->getFamily().c_str());
}

TEST(CoreTypefaceTest, createFromAsset_fontDrivesMeasurement) {
    TextPaint paint;
    paint.setTypeface(Typeface::createFromAsset("font/StaticLayoutLineBreakingTestFont.ttf"));
    paint.setTextSize(10.0f); // 1em == 10px in this font
    String text(u"XXXXX");    // X == 10em == 100px
    EXPECT_FLOAT_EQ(500.0f, paint.measureText(&text, 0, (int)text.length()));
}

TEST(CoreTypefaceTest, contextGetFont_resolvesFontResource) {
    // R.font entry generated by aapt2 from tests/gui/assets/font/.
    Typeface* face = App::getInstance().getFont(gui_test::R::font::StaticLayoutLineBreakingTestFont);
    ASSERT_NE(nullptr, face);
    EXPECT_STREQ("Sample Font", face->getFamily().c_str());

    // Same resource twice -> same cached instance.
    EXPECT_EQ(face, App::getInstance().getFont(gui_test::R::font::StaticLayoutLineBreakingTestFont));
}

// AOSP Paint.setTypeface(null) is the documented "clear" (Paint.java: "Pass
// null to clear any previous typeface"): the field stays null while text ops
// fall back to the default typeface. A failed font load used to hand Paint a
// null face that metrics dereferenced (the LayoutBidiCursorPath segfault).
TEST(CoreTypefaceTest, setTypefaceNullFallsBackToDefault) {
    TextPaint paint;
    paint.setTypeface(nullptr);
    EXPECT_EQ(nullptr, paint.getTypeface());   // field keeps the null contract

    Paint::FontMetricsInt fmi;
    const int lineHeight = paint.getFontMetricsInt(&fmi);
    EXPECT_GT(lineHeight, 0);
    EXPECT_LT(fmi.ascent, 0);
    EXPECT_GT(fmi.descent, 0);
    // ascent()/descent() go through the same fallback (float extent vs the
    // int-truncated FontMetricsInt — same font, so within 1px).
    EXPECT_NEAR(paint.ascent(), (float) fmi.ascent, 1.0f);
    EXPECT_NEAR(paint.descent(), (float) fmi.descent, 1.0f);

    // Clearing an already-set face restores the default's metrics, not the
    // previous face's (the cached FontCollection must follow the null).
    paint.setTypeface(Typeface::createFromAsset("font/StaticLayoutLineBreakingTestFont.ttf"));
    paint.setTypeface(nullptr);
    Paint::FontMetricsInt cleared;
    paint.getFontMetricsInt(&cleared);
    EXPECT_EQ(cleared.ascent, fmi.ascent);
    EXPECT_EQ(cleared.descent, fmi.descent);
}

TEST(CoreTypefaceTest, contextGetFont_unknownIdReturnsNull) {
    EXPECT_EQ(nullptr, App::getInstance().getFont(0x7fffffff));
}
