// Regression tests for the pak-font loading routes (no AOSP counterpart —
// coretests reaches fonts via instrumentation assets; these pin the cdroid
// contracts):
//  - Typeface::createFromAsset: per-path instance cache (repeated calls return
//    the SAME pointer), and the loaded face actually drives measurement.
//  - Context::getFont(R.font.<name>): the arsc resource route
//    (openNonAsset) resolves to the same family.
//
// The exact-width font lives in the gui_test pak twice on purpose:
//   assets/font/... (asset route, "assets/" zip prefix) and
//   font/...        (R.font resource route, zip root — aapt2 compiles font/)
#include <gtest/gtest.h>
#include <core/app.h>
#include <core/typeface.h>
#include <text/textpaint.h>
#include <text/String.h>
#include "R.h"

using namespace cdroid;

TEST(CoreTypefaceTest, createFromAsset_returnsCachedInstancePerPath) {
    const std::string path = "font/StaticLayoutLineBreakingTestFont.ttf";
    Typeface* first = Typeface::createFromAsset(path);
    ASSERT_NE(nullptr, first);
    EXPECT_EQ(first, Typeface::createFromAsset(path));
    EXPECT_STREQ("Sample Font", first->getFamily().c_str());
}

TEST(CoreTypefaceTest, createFromAsset_fontDrivesMeasurement) {
    TextPaint paint;
    paint.setTypeface(Typeface::createFromAsset("font/StaticLayoutLineBreakingTestFont.ttf"));
    paint.setTextSize(10.0f); // 1em == 10px in this font
    String text(u"XXXXX");    // X == 10em == 100px
    EXPECT_FLOAT_EQ(500.0f, paint.measureText(&text, 0, (int)text.length()));
}

TEST(CoreTypefaceTest, contextGetFont_resolvesFontResource) {
    // R.font entry generated by aapt2 from tests/gui/assets/font/.
    Typeface* face = App::getInstance().getFont(gui_test::R::font::StaticLayoutLineBreakingTestFont);
    ASSERT_NE(nullptr, face);
    EXPECT_STREQ("Sample Font", face->getFamily().c_str());

    // Same resource twice -> same cached instance.
    EXPECT_EQ(face, App::getInstance().getFont(gui_test::R::font::StaticLayoutLineBreakingTestFont));
}

TEST(CoreTypefaceTest, contextGetFont_unknownIdReturnsNull) {
    EXPECT_EQ(nullptr, App::getInstance().getFont(0x7fffffff));
}
