#include "framework_styleable.h"
namespace cdroid {
namespace styleable {
    namespace View {
        const uint32_t IDS[] = {
            fw_attr::background,
            fw_attr::padding, fw_attr::paddingLeft, fw_attr::paddingTop,
            fw_attr::paddingRight, fw_attr::paddingBottom,
            fw_attr::paddingStart, fw_attr::paddingEnd,
            fw_attr::minWidth, fw_attr::minHeight,
            fw_attr::visibility, fw_attr::id, fw_attr::tag,
            fw_attr::scrollX, fw_attr::scrollY,
            fw_attr::fitsSystemWindows, fw_attr::scrollbars, fw_attr::fadingEdge,
            fw_attr::fadingEdgeLength,
            fw_attr::nextFocusLeft, fw_attr::nextFocusRight,
            fw_attr::nextFocusUp, fw_attr::nextFocusDown,
            fw_attr::clickable, fw_attr::longClickable,
            fw_attr::saveEnabled, fw_attr::drawingCacheQuality,
            fw_attr::duplicateParentState,
            fw_attr::focusable, fw_attr::focusableInTouchMode,
            fw_attr::soundEffectsEnabled, fw_attr::hapticFeedbackEnabled,
            fw_attr::onClick, fw_attr::contentDescription,
            fw_attr::isScrollContainer, fw_attr::foregroundGravity,
            fw_attr::scrollbarStyle, fw_attr::scrollbarSize,
            fw_attr::scrollbarFadeDuration, fw_attr::scrollbarDefaultDelayBeforeFade,
            fw_attr::fadeScrollbars, fw_attr::filterTouchesWhenObscured,
            fw_attr::keepScreenOn, fw_attr::layerType,
            fw_attr::layoutDirection, fw_attr::textDirection,
            fw_attr::textAlignment, fw_attr::importantForAccessibility,
            fw_attr::requiresFadingEdge, fw_attr::overScrollMode,
            fw_attr::verticalScrollbarPosition,
            fw_attr::rotation, fw_attr::rotationX, fw_attr::rotationY,
            fw_attr::scaleX, fw_attr::scaleY,
            fw_attr::transformPivotX, fw_attr::transformPivotY,
            fw_attr::translationX, fw_attr::translationY, fw_attr::translationZ,
            fw_attr::alpha, fw_attr::elevation,
            fw_attr::transitionName, fw_attr::stateListAnimator,
            fw_attr::nestedScrollingEnabled,
            fw_attr::backgroundTint, fw_attr::backgroundTintMode,
            fw_attr::foregroundTint, fw_attr::foregroundTintMode,
            fw_attr::outlineProvider,
            fw_attr::scrollIndicators, fw_attr::nextFocusForward,
            fw_attr::nextClusterForward,
            fw_attr::keyboardNavigationCluster,
            fw_attr::focusedByDefault, fw_attr::allowClickWhenDisabled,
            fw_attr::enabled,
        };
    }
}
}
