#ifndef __KEYCODES_H__
#define __KEYCODES_H__
#ifdef __cplusplus
extern "C" {
#endif

/* Key codes. */
enum {
    KEY_UNKNOWN         = 0,
    KEY_SOFT_LEFT       = 1,
    KEY_SOFT_RIGHT      = 2,
    KEY_HOME            = 3,
    KEY_BACK            = 4,
    KEY_CALL            = 5,
    KEY_ENDCALL         = 6,
    KEY_0               = 7,
    KEY_1               = 8,
    KEY_2               = 9,
    KEY_3               = 10,
    KEY_4               = 11,
    KEY_5               = 12,
    KEY_6               = 13,
    KEY_7               = 14,
    KEY_8               = 15,
    KEY_9               = 16,
    KEY_STAR            = 17,
    KEY_POUND           = 18,
    KEY_DPAD_UP         = 19,
    KEY_DPAD_DOWN       = 20,
    KEY_DPAD_LEFT       = 21,
    KEY_DPAD_RIGHT      = 22,
    KEY_DPAD_CENTER     = 23,
    KEY_VOLUME_UP       = 24,
    KEY_VOLUME_DOWN     = 25,
    KEY_POWER           = 26,
    KEY_CAMERA          = 27,
    KEY_CLEAR           = 28,
    KEY_A               = 29,
    KEY_B               = 30,
    KEY_C               = 31,
    KEY_D               = 32,
    KEY_E               = 33,
    KEY_F               = 34,
    KEY_G               = 35,
    KEY_H               = 36,
    KEY_I               = 37,
    KEY_J               = 38,
    KEY_K               = 39,
    KEY_L               = 40,
    KEY_M               = 41,
    KEY_N               = 42,
    KEY_O               = 43,
    KEY_P               = 44,
    KEY_Q               = 45,
    KEY_R               = 46,
    KEY_S               = 47,
    KEY_T               = 48,
    KEY_U               = 49,
    KEY_V               = 50,
    KEY_W               = 51,
    KEY_X               = 52,
    KEY_Y               = 53,
    KEY_Z               = 54,
    KEY_COMMA           = 55,
    KEY_PERIOD          = 56,
    KEY_ALT_LEFT        = 57,
    KEY_ALT_RIGHT       = 58,
    KEY_SHIFT_LEFT      = 59,
    KEY_SHIFT_RIGHT     = 60,
    KEY_TAB             = 61,
    KEY_SPACE           = 62,
    KEY_SYM             = 63,
    KEY_EXPLORER        = 64,
    KEY_ENVELOPE        = 65,
    KEY_ENTER           = 66,
    KEY_DEL             = 67,
    KEY_GRAVE           = 68,
    KEY_MINUS           = 69,
    KEY_EQUALS          = 70,
    KEY_LEFTBRACE       = 71,
    KEY_RIGHTBRACE      = 72,
    KEY_BACKSLASH       = 73,
    KEY_SEMICOLON       = 74,
    KEY_APOSTROPHE      = 75,
    KEY_SLASH           = 76,
    KEY_AT              = 77,
    KEY_NUM             = 78,
    KEY_HEADSETHOOK     = 79,
    KEY_FOCUS           = 80,   // *Camera* focus
    KEY_PLUS            = 81,
    KEY_MENU            = 82,
    KEY_NOTIFICATION    = 83,
    KEY_SEARCH          = 84,
    KEY_MEDIA_PLAY_PAUSE= 85,
    KEY_MEDIA_STOP      = 86,
    KEY_MEDIA_NEXT      = 87,
    KEY_MEDIA_PREVIOUS  = 88,
    KEY_MEDIA_REWIND    = 89,
    KEY_MEDIA_FAST_FORWARD = 90,
    KEY_MUTE            = 91,
    KEY_PAGE_UP         = 92,
    KEY_PAGE_DOWN       = 93,
    KEY_PICTSYMBOLS     = 94,
    KEY_SWITCH_CHARSET  = 95,
    KEY_BUTTON_A        = 96,
    KEY_BUTTON_B        = 97,
    KEY_BUTTON_C        = 98,
    KEY_BUTTON_X        = 99,
    KEY_BUTTON_Y        = 100,
    KEY_BUTTON_Z        = 101,
    KEY_BUTTON_L1       = 102,
    KEY_BUTTON_R1       = 103,
    KEY_BUTTON_L2       = 104,
    KEY_BUTTON_R2       = 105,
    KEY_BUTTON_THUMBL   = 106,
    KEY_BUTTON_THUMBR   = 107,
    KEY_BUTTON_START    = 108,
    KEY_BUTTON_SELECT   = 109,
    KEY_BUTTON_MODE     = 110,
    KEY_ESCAPE          = 111,
    KEY_FORWARD_DEL     = 112,
    KEY_CTRL_LEFT       = 113,
    KEY_CTRL_RIGHT      = 114,
    KEY_CAPS_LOCK       = 115,
    KEY_SCROLL_LOCK     = 116,
    KEY_META_LEFT       = 117,
    KEY_META_RIGHT      = 118,
    KEY_FUNCTION        = 119,
    KEY_SYSRQ           = 120,
    KEY_BREAK           = 121,
    KEY_MOVE_HOME       = 122,
    KEY_MOVE_END        = 123,
    KEY_INSERT          = 124,
    KEY_FORWARD         = 125,
    KEY_MEDIA_PLAY      = 126,
    KEY_MEDIA_PAUSE     = 127,
    KEY_MEDIA_CLOSE     = 128,
    KEY_MEDIA_EJECT     = 129,
    KEY_MEDIA_RECORD    = 130,
    KEY_F1              = 131,
    KEY_F2              = 132,
    KEY_F3              = 133,
    KEY_F4              = 134,
    KEY_F5              = 135,
    KEY_F6              = 136,
    KEY_F7              = 137,
    KEY_F8              = 138,
    KEY_F9              = 139,
    KEY_F10             = 140,
    KEY_F11             = 141,
    KEY_F12             = 142,
    KEY_NUM_LOCK        = 143,
    KEY_NUMPAD_0        = 144,
    KEY_NUMPAD_1        = 145,
    KEY_NUMPAD_2        = 146,
    KEY_NUMPAD_3        = 147,
    KEY_NUMPAD_4        = 148,
    KEY_NUMPAD_5        = 149,
    KEY_NUMPAD_6        = 150,
    KEY_NUMPAD_7        = 151,
    KEY_NUMPAD_8        = 152,
    KEY_NUMPAD_9        = 153,
    KEY_NUMPAD_DIVIDE   = 154,
    KEY_NUMPAD_MULTIPLY = 155,
    KEY_NUMPAD_SUBTRACT = 156,
    KEY_NUMPAD_ADD      = 157,
    KEY_NUMPAD_DOT      = 158,
    KEY_NUMPAD_COMMA    = 159,
    KEY_NUMPAD_ENTER    = 160,
    KEY_NUMPAD_EQUALS   = 161,
    KEY_NUMPAD_LEFT_PAREN = 162,
    KEY_NUMPAD_RIGHT_PAREN = 163,
    KEY_VOLUME_MUTE     = 164,
    KEY_INFO            = 165,
    KEY_CHANNEL_UP      = 166,
    KEY_CHANNEL_DOWN    = 167,
    KEY_ZOOM_IN         = 168,
    KEY_ZOOM_OUT        = 169,
    KEY_TV              = 170,
    KEY_WINDOW          = 171,
    KEY_GUIDE           = 172,
    KEY_DVR             = 173,
    KEY_BOOKMARK        = 174,
    KEY_CAPTIONS        = 175,
    KEY_SETTINGS        = 176,
    KEY_TV_POWER        = 177,
    KEY_TV_INPUT        = 178,
    KEY_STB_POWER       = 179,
    KEY_STB_INPUT       = 180,
    KEY_AVR_POWER       = 181,
    KEY_AVR_INPUT       = 182,
    KEY_PROG_RED        = 183,
    KEY_PROG_GREEN      = 184,
    KEY_PROG_YELLOW     = 185,
    KEY_PROG_BLUE       = 186,
    KEY_APP_SWITCH      = 187,
    KEY_BUTTON_1        = 188,
    KEY_BUTTON_2        = 189,
    KEY_BUTTON_3        = 190,
    KEY_BUTTON_4        = 191,
    KEY_BUTTON_5        = 192,
    KEY_BUTTON_6        = 193,
    KEY_BUTTON_7        = 194,
    KEY_BUTTON_8        = 195,
    KEY_BUTTON_9        = 196,
    KEY_BUTTON_10       = 197,
    KEY_BUTTON_11       = 198,
    KEY_BUTTON_12       = 199,
    KEY_BUTTON_13       = 200,
    KEY_BUTTON_14       = 201,
    KEY_BUTTON_15       = 202,
    KEY_BUTTON_16       = 203,
    KEY_LANGUAGE_SWITCH = 204,
    KEY_MANNER_MODE     = 205,
    KEY_3D_MODE         = 206,
    KEY_CONTACTS        = 207,
    KEY_CALENDAR        = 208,
    KEY_MUSIC           = 209,
    KEY_CALCULATOR      = 210,
    KEY_ZENKAKU_HANKAKU = 211,
    KEY_EISU            = 212,
    KEY_MUHENKAN        = 213,
    KEY_HENKAN          = 214,
    KEY_KATAKANA_HIRAGANA = 215,
    KEY_YEN             = 216,
    KEY_RO              = 217,
    KEY_KANA            = 218,
    KEY_ASSIST          = 219,
    KEY_BRIGHTNESS_DOWN = 220,
    KEY_BRIGHTNESS_UP   = 221,
    KEY_MEDIA_AUDIO_TRACK= 222,
/////////////////////////////////////////
    KEY_OK              =223,
    KEY_EPG             =224,
    KEY_AUDIO           =225,
    KEY_SUBTITLE        =226,
    KEY_HELP            =227,
    KEY_TELETEXT        =228,
    KEY_SLEEP           =229,
    KEY_WAKEUP          =230
    // NOTE: If you add a new keycode here you must also add it to several other files.
    //       Refer to frameworks/base/core/java/android/view/KeyEvent.java for the full list.
};

enum {
    /**
     * Constants for LEDs. Hidden from the API since we don't actually expose a way to interact
     * with LEDs to developers
     *
     * NOTE: If you add LEDs here, you must also add them to InputEventLabels.h
     */

    LED_NUM_LOCK = 0x00,
    LED_CAPS_LOCK = 0x01,
    LED_SCROLL_LOCK = 0x02,
    LED_COMPOSE = 0x03,
    LED_KANA = 0x04,
    LED_SLEEP = 0x05,
    LED_SUSPEND = 0x06,
    LED_MUTE = 0x07,
    LED_MISC = 0x08,
    LED_MAIL = 0x09,
    LED_CHARGING = 0x0a,
    LED_CONTROLLER_1 = 0x10,
    LED_CONTROLLER_2 = 0x11,
    LED_CONTROLLER_3 = 0x12,
    LED_CONTROLLER_4 = 0x13,
};
#ifdef __cplusplus
}
#endif

#endif // ___KEYCODES_H__
