//#include <porting/cdtypes.h>
#include <gui/gui_features.h>
#include <view/viewgroup.h>
#include <view/viewoverlay.h>
#include <widget/viewpager.h>
#include <widget/simplemonthview.h>
#include <widget/linearlayout.h>
#include <widget/relativelayout.h>
#include <widget/numberpicker.h>
#include <widget/absolutelayout.h>
#include <widget/framelayout.h>
#include <widget/viewanimator.h>
#include <widget/viewflipper.h>
#include <widget/simplemonthview.h>
#include <widget/tablelayout.h>
#include <widget/tablayout.h>
#include <widget/drawerlayout.h>
#include <widget/textview.h>
#include <widget/edittext.h>
#include <widget/button.h>
#include <widget/compoundbutton.h>
#include <widget/togglebutton.h>
#include <widget/switch.h>
#include <widget/checkbox.h>
#include <widget/radiobutton.h>
#include <widget/radiogroup.h>
#include <widget/imagebutton.h>
#include <widget/analogclock.h>
#include <widget/imageview.h>
#include <widget/adapterview.h>
#include <widget/absspinner.h>
#include <widget/spinner.h>
#include <widget/abslistview.h>
#include <widget/listview.h>
#include <widget/gridview.h>
#include <widget/gridlayout.h>
#include <widget/scrollview.h>
#include <widget/horizontalscrollview.h>
#include <widget/progressbar.h>
#include <widget/cdwindow.h>
#include <widget/toast.h>
#include <core/app.h>
#include <widget/seekbar.h>

#include <widgetEx/recyclerview/recyclerview.h>
#include <widgetEx/recyclerview/linearlayoutmanager.h>
#include <widgetEx/recyclerview/gridlayoutmanager.h>
#include <widgetEx/recyclerview/staggeredgridlayoutmanager.h>
#include <widgetEx/recyclerview/scrollbarhelper.h>
#include <widgetEx/recyclerview/linearsmoothscroller.h>
#include <widgetEx/recyclerview/defaultitemanimator.h>
#include <widgetEx/recyclerview/linearsnaphelper.h>
#include <widgetEx/recyclerview/pagersnaphelper.h>
#include <widgetEx/recyclerview/divideritemdecoration.h>
#include <widgetEx/recyclerview/orientationhelper.h>

using namespace cdroid;
