#include <cdtypes.h>
#include <widget/viewgroup.h>
#include <views/viewoverlay.h>
#include <widget/viewpager.h>
#include <widget/simplemonthview.h>
#include <widget/linearlayout.h>
#include <widget/relativelayout.h>
#include <widget/numberpicker.h>
#include <widget/absolutelayout.h>
#include <widget/framelayout.h>
#include <widget/viewanimator.h>
#include <widget/viewflipper.h>
#include <widget/simplemonthview.h>
#include <widget/tablelayout.h>
#include <widget/tablayout.h>
#include <widget/drawerlayout.h>
#include <widget/textview.h>
#include <widget/edittext.h>
#include <widget/button.h>
#include <widget/compoundbutton.h>
#include <widget/togglebutton.h>
#include <widget/switch.h>
#include <widget/checkbox.h>
#include <widget/radiobutton.h>
#include <widget/radiogroup.h>
#include <widget/imagebutton.h>
#include <widget/analogclock.h>
#include <widget/imageview.h>
#include <widget/adapterview.h>
#include <widget/absspinner.h>
#include <widget/spinner.h>
#include <widget/abslistview.h>
#include <widget/listview.h>
#include <widget/gridview.h>
#include <widget/gridlayout.h>
#include <widget/scrollview.h>
#include <widget/horizontalscrollview.h>
#include <widget/progressbar.h>
#include <widget/cdwindow.h>
#include <views/toastwindow.h>
#include <core/app.h>
#include <widget/seekbar.h>
using namespace cdroid;
