#pragma once

/*Generated by machine ,Do not edit!!!*/

namespace uidemo{

class R{
public:
    enum id {
        exitbutton              = 0x00002710 ,
        tablayout               = 0x00002711 ,
        viewpager               = 0x00002712
    };//endof enum id

};//endof class R

}//endof namespace

