#pragma once

/*Generated by machine ,Do not edit!!!*/

namespace uidemo{

class R{
public:
    class id {
    public: enum{
         power                   = 0x00002710 /*     10000*/,
         devicename              = 0x00002711 /*     10001*/,
         coldfan                 = 0x00002712 /*     10002*/,
         fanspeed                = 0x00002713 /*     10003*/,
         windtype                = 0x00002714 /*     10004*/,
         move                    = 0x00002715 /*     10005*/,
         timer                   = 0x00002716 /*     10006*/,
         oxygen                  = 0x00002717 /*     10007*/,
         emode                   = 0x00002718 /*     10008*/,
         hum                     = 0x00002719 /*     10009*/,
         ailock                  = 0x0000271A /*     10010*/,
         oprecords               = 0x0000271B /*     10011*/,
         usermanager             = 0x0000271C /*     10012*/,
         temp_down               = 0x0000271D /*     10013*/,
         temp_up                 = 0x0000271E /*     10014*/,
         imageView1              = 0x0000271F /*     10015*/,
         open                    = 0x00002720 /*     10016*/,
         pause                   = 0x00002721 /*     10017*/,
         close                   = 0x00002722 /*     10018*/,
         container1              = 0x00002723 /*     10019*/,
         devicename1             = 0x00002724 /*     10020*/,
         gap                     = 0x00002725 /*     10021*/,
         container2              = 0x00002726 /*     10022*/,
         devicename2             = 0x00002727 /*     10023*/,
         open1                   = 0x00002728 /*     10024*/,
         pause1                  = 0x00002729 /*     10025*/,
         close1                  = 0x0000272A /*     10026*/,
         right_panel             = 0x0000272B /*     10027*/,
         title                   = 0x0000272C /*     10028*/,
         viewpager               = 0x0000272D /*     10029*/,
         footer                  = 0x0000272E /*     10030*/,
         buttonContainer         = 0x0000272F /*     10031*/,
         lights                  = 0x00002730 /*     10032*/,
         curtains                = 0x00002731 /*     10033*/,
         sockets                 = 0x00002732 /*     10034*/,
         airconds                = 0x00002733 /*     10035*/,
         tvsets                  = 0x00002734 /*     10036*/,
         ailocks                 = 0x00002735 /*     10037*/,
         hangers                 = 0x00002736 /*     10038*/,
         centeraircond           = 0x00002737 /*     10039*/,
         music                   = 0x00002738 /*     10040*/,
         wind                    = 0x00002739 /*     10041*/,
         acfan                   = 0x0000273A /*     10042*/,
         dvd                     = 0x0000273B /*     10043*/,
         container               = 0x0000273C /*     10044*/,
         leftPanel               = 0x0000273D /*     10045*/,
         imageView               = 0x0000273E /*     10046*/,
         listview                = 0x0000273F /*     10047*/,
         addbutton               = 0x00002740 /*     10048*/,
         light1                  = 0x00002741 /*     10049*/,
         light2                  = 0x00002742 /*     10050*/,
         light3                  = 0x00002743 /*     10051*/,
         light4                  = 0x00002744 /*     10052*/,
         sencetype               = 0x00002745 /*     10053*/,
         gridview                = 0x00002746 /*     10054*/,
         smokesensor             = 0x00002747 /*     10055*/,
         powerstate              = 0x00002748 /*     10056*/,
         detail                  = 0x00002749 /*     10057*/,
         socket                  = 0x0000274A /*     10058*/,
         poweron                 = 0x0000274B /*     10059*/,
         poweroff                = 0x0000274C /*     10060*/,
         volumn_down             = 0x0000274D /*     10061*/,
         volumn_up               = 0x0000274E /*     10062*/
    };/*enum*/};/*class*/

};//endof class R

}//endof namespace

