#pragma once

/*Generated by machine ,Do not edit !!!*/

namespace uidemo2{

namespace R{
    namespace id{
         static constexpr int power                   = 0x00002710 ;/*10000*/
         static constexpr int devicename              = 0x00002711 ;/*10001*/
         static constexpr int coldfan                 = 0x00002712 ;/*10002*/
         static constexpr int fanspeed                = 0x00002713 ;/*10003*/
         static constexpr int windtype                = 0x00002714 ;/*10004*/
         static constexpr int move                    = 0x00002715 ;/*10005*/
         static constexpr int timer                   = 0x00002716 ;/*10006*/
         static constexpr int oxygen                  = 0x00002717 ;/*10007*/
         static constexpr int emode                   = 0x00002718 ;/*10008*/
         static constexpr int hum                     = 0x00002719 ;/*10009*/
         static constexpr int ailock                  = 0x0000271A ;/*10010*/
         static constexpr int oprecords               = 0x0000271B ;/*10011*/
         static constexpr int usermanager             = 0x0000271C ;/*10012*/
         static constexpr int temp_down               = 0x0000271D ;/*10013*/
         static constexpr int temp_up                 = 0x0000271E ;/*10014*/
         static constexpr int imageView1              = 0x0000271F ;/*10015*/
         static constexpr int open                    = 0x00002720 ;/*10016*/
         static constexpr int pause                   = 0x00002721 ;/*10017*/
         static constexpr int close                   = 0x00002722 ;/*10018*/
         static constexpr int container1              = 0x00002723 ;/*10019*/
         static constexpr int devicename1             = 0x00002724 ;/*10020*/
         static constexpr int gap                     = 0x00002725 ;/*10021*/
         static constexpr int container2              = 0x00002726 ;/*10022*/
         static constexpr int devicename2             = 0x00002727 ;/*10023*/
         static constexpr int open1                   = 0x00002728 ;/*10024*/
         static constexpr int pause1                  = 0x00002729 ;/*10025*/
         static constexpr int close1                  = 0x0000272A ;/*10026*/
         static constexpr int right_panel             = 0x0000272B ;/*10027*/
         static constexpr int title                   = 0x0000272C ;/*10028*/
         static constexpr int viewpager               = 0x0000272D ;/*10029*/
         static constexpr int footer                  = 0x0000272E ;/*10030*/
         static constexpr int buttonContainer         = 0x0000272F ;/*10031*/
         static constexpr int lights                  = 0x00002730 ;/*10032*/
         static constexpr int curtains                = 0x00002731 ;/*10033*/
         static constexpr int sockets                 = 0x00002732 ;/*10034*/
         static constexpr int airconds                = 0x00002733 ;/*10035*/
         static constexpr int tvsets                  = 0x00002734 ;/*10036*/
         static constexpr int ailocks                 = 0x00002735 ;/*10037*/
         static constexpr int hangers                 = 0x00002736 ;/*10038*/
         static constexpr int centeraircond           = 0x00002737 ;/*10039*/
         static constexpr int music                   = 0x00002738 ;/*10040*/
         static constexpr int wind                    = 0x00002739 ;/*10041*/
         static constexpr int acfan                   = 0x0000273A ;/*10042*/
         static constexpr int dvd                     = 0x0000273B ;/*10043*/
         static constexpr int container               = 0x0000273C ;/*10044*/
         static constexpr int leftPanel               = 0x0000273D ;/*10045*/
         static constexpr int imageView               = 0x0000273E ;/*10046*/
         static constexpr int listview                = 0x0000273F ;/*10047*/
         static constexpr int addbutton               = 0x00002740 ;/*10048*/
         static constexpr int light1                  = 0x00002741 ;/*10049*/
         static constexpr int light2                  = 0x00002742 ;/*10050*/
         static constexpr int light3                  = 0x00002743 ;/*10051*/
         static constexpr int light4                  = 0x00002744 ;/*10052*/
         static constexpr int sencetype               = 0x00002745 ;/*10053*/
         static constexpr int gridview                = 0x00002746 ;/*10054*/
         static constexpr int smokesensor             = 0x00002747 ;/*10055*/
         static constexpr int powerstate              = 0x00002748 ;/*10056*/
         static constexpr int detail                  = 0x00002749 ;/*10057*/
         static constexpr int socket                  = 0x0000274A ;/*10058*/
         static constexpr int poweron                 = 0x0000274B ;/*10059*/
         static constexpr int poweroff                = 0x0000274C ;/*10060*/
         static constexpr int volumn_down             = 0x0000274D ;/*10061*/
         static constexpr int volumn_up               = 0x0000274E ;/*10062*/
    };/*namespace id*/

    namespace strings{
    };/*namespace strings*/

};//endof namespace R

}//endof namespace

