#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace uidemo1{

namespace R{
    namespace drawable{
        enum : int {
            dev_sync = 0x7f010000,
            dial = 0x7f010001,
            horizontal_thumb = 0x7f010002,
            horizontal_track = 0x7f010003,
            hour = 0x7f010004,
            ic_wp_3 = 0x7f010005,
            icon_back = 0x7f010006,
            light2 = 0x7f010007,
            light_off = 0x7f010008,
            light_on = 0x7f010009,
            minute = 0x7f01000a,
            reback = 0x7f01000b,
            second = 0x7f01000c,
            watch = 0x7f01000d,
            watch_2 = 0x7f01000e,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            BtnGo = 0x7f020000,
            TextUrl = 0x7f020001,
            WebView01 = 0x7f020002,
            address = 0x7f020003,
            btnadd = 0x7f020004,
            button1 = 0x7f020005,
            editText1 = 0x7f020006,
            editText2 = 0x7f020007,
            et1 = 0x7f020008,
            et2 = 0x7f020009,
            exitbutton = 0x7f02000a,
            filename = 0x7f02000b,
            filesize = 0x7f02000c,
            icon = 0x7f02000d,
            idno = 0x7f02000e,
            imgbtn = 0x7f02000f,
            light = 0x7f020010,
            tablayout = 0x7f020011,
            table = 0x7f020012,
            textcontainer = 0x7f020013,
            textview1 = 0x7f020014,
            toolbar = 0x7f020015,
            tv1 = 0x7f020016,
            tv2 = 0x7f020017,
            viewpager = 0x7f020018,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            fileitem = 0x7f030000,
            fileitem2 = 0x7f030001,
            layout1 = 0x7f030002,
            layout2 = 0x7f030003,
            layout3 = 0x7f030004,
            layout4 = 0x7f030005,
            main = 0x7f030006,
        };
    }/*namespace layout*/

    namespace string{
        enum : int {
            Go = 0x7f040000,
            address = 0x7f040001,
            blue = 0x7f040002,
            green = 0x7f040003,
            inputcolumns = 0x7f040004,
            inputnum = 0x7f040005,
            red = 0x7f040006,
            row1 = 0x7f040007,
            row2 = 0x7f040008,
            row3 = 0x7f040009,
            row4 = 0x7f04000a,
            teststring1 = 0x7f04000b,
            webview = 0x7f04000c,
            yellow = 0x7f04000d,
        };
    }/*namespace string*/

};//endof namespace R

}//endof namespace
