#pragma once

/*Generated by machine ,Do not edit !!!*/

namespace uidemo1{

namespace R{
    namespace id{
         static constexpr int idno                    = 0x00002710 ;/*10000*/
         static constexpr int filename                = 0x00002711 ;/*10001*/
         static constexpr int filesize                = 0x00002712 ;/*10002*/
         static constexpr int icon                    = 0x00002713 ;/*10003*/
         static constexpr int address                 = 0x00002714 ;/*10004*/
         static constexpr int BtnGo                   = 0x00002715 ;/*10005*/
         static constexpr int TextUrl                 = 0x00002716 ;/*10006*/
         static constexpr int toolbar                 = 0x00002717 ;/*10007*/
         static constexpr int WebView01               = 0x00002718 ;/*10008*/
         static constexpr int editText1               = 0x00002719 ;/*10009*/
         static constexpr int editText2               = 0x0000271A ;/*10010*/
         static constexpr int textcontainer           = 0x0000271B ;/*10011*/
         static constexpr int button1                 = 0x0000271C ;/*10012*/
         static constexpr int textview1               = 0x0000271D ;/*10013*/
         static constexpr int light                   = 0x0000271E ;/*10014*/
         static constexpr int tv1                     = 0x0000271F ;/*10015*/
         static constexpr int et1                     = 0x00002720 ;/*10016*/
         static constexpr int tv2                     = 0x00002721 ;/*10017*/
         static constexpr int et2                     = 0x00002722 ;/*10018*/
         static constexpr int btnadd                  = 0x00002723 ;/*10019*/
         static constexpr int table                   = 0x00002724 ;/*10020*/
         static constexpr int exitbutton              = 0x00002725 ;/*10021*/
         static constexpr int tablayout               = 0x00002726 ;/*10022*/
         static constexpr int viewpager               = 0x00002727 ;/*10023*/
    };/*namespace id*/

    namespace strings{
    };/*namespace strings*/

};//endof namespace R

}//endof namespace

