#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace printerdemo{

namespace R{
    namespace anim{
        enum : int {
            slide_in_left = 0x7f010000,
            slide_in_right = 0x7f010001,
            slide_out_left = 0x7f010002,
            slide_out_right = 0x7f010003,
        };
    }/*namespace anim*/

    namespace attr{
        enum : int {
            buttonGravity = 0x7f020000,
            cardBackground = 0x7f020001,
            colorSurfaceVariant = 0x7f020002,
            destination = 0x7f020003,
            progressTrack = 0x7f020004,
            route = 0x7f020005,
            showAsAction = 0x7f020006,
            startDestination = 0x7f020007,
        };
    }/*namespace attr*/

    namespace color{
        enum : int {
            app_text_primary = 0x7f030000,
            app_text_primary_dark = 0x7f030001,
            app_text_secondary = 0x7f030002,
            app_text_secondary_dark = 0x7f030003,
            nav_item_icon = 0x7f030004,
            nav_item_text = 0x7f030005,
        };
    }/*namespace color*/

    namespace drawable{
        enum : int {
            bg_screen = 0x7f040000,
            btn_card_accent = 0x7f040001,
            btn_card_amber = 0x7f040002,
            btn_card_green = 0x7f040003,
            btn_card_purple = 0x7f040004,
            btn_primary = 0x7f040005,
            card_bg = 0x7f040006,
            card_bg_dark = 0x7f040007,
            circle_deco = 0x7f040008,
            divider_dashed = 0x7f040009,
            hero_bg = 0x7f04000a,
            ic_back = 0x7f04000b,
            ic_home = 0x7f04000c,
            ic_nav_build = 0x7f04000d,
            ic_nav_copy = 0x7f04000e,
            ic_nav_home = 0x7f04000f,
            ic_nav_scan = 0x7f040010,
            ic_nav_settings = 0x7f040011,
            icon_chip_bg = 0x7f040012,
            nav_item_background = 0x7f040013,
            paper_bg = 0x7f040014,
            pill_bg = 0x7f040015,
            progress_track_bg = 0x7f040016,
            progress_track_bg_dark = 0x7f040017,
            status_dot = 0x7f040018,
            toolbar_bg = 0x7f040019,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            about = 0x7f050000,
            about_arch = 0x7f050001,
            about_features = 0x7f050002,
            about_intro = 0x7f050003,
            about_usecases = 0x7f050004,
            action_about = 0x7f050005,
            action_home_to_copy = 0x7f050006,
            action_home_to_maintain = 0x7f050007,
            action_home_to_scan = 0x7f050008,
            action_home_to_settings = 0x7f050009,
            action_toggle_language = 0x7f05000a,
            action_toggle_theme = 0x7f05000b,
            always = 0x7f05000c,
            bottom = 0x7f05000d,
            bottom_navigation = 0x7f05000e,
            btn_minus = 0x7f05000f,
            btn_plus = 0x7f050010,
            btn_scan = 0x7f050011,
            btn_start = 0x7f050012,
            card_copy = 0x7f050013,
            card_maintain = 0x7f050014,
            card_scan = 0x7f050015,
            card_settings = 0x7f050016,
            center_vertical = 0x7f050017,
            collapseActionView = 0x7f050018,
            copy = 0x7f050019,
            hero = 0x7f05001a,
            home = 0x7f05001b,
            ifRoom = 0x7f05001c,
            ink_c_fill = 0x7f05001d,
            ink_c_pct = 0x7f05001e,
            ink_c_space = 0x7f05001f,
            ink_k_fill = 0x7f050020,
            ink_k_pct = 0x7f050021,
            ink_k_space = 0x7f050022,
            ink_m_fill = 0x7f050023,
            ink_m_pct = 0x7f050024,
            ink_m_space = 0x7f050025,
            ink_y_fill = 0x7f050026,
            ink_y_pct = 0x7f050027,
            ink_y_space = 0x7f050028,
            m_align = 0x7f050029,
            m_clean = 0x7f05002a,
            m_nozzle = 0x7f05002b,
            m_selftest = 0x7f05002c,
            maint_fill = 0x7f05002d,
            maint_overlay = 0x7f05002e,
            maint_status = 0x7f05002f,
            maint_track = 0x7f050030,
            maintain = 0x7f050031,
            nav_graph = 0x7f050032,
            nav_host_container = 0x7f050033,
            network_text = 0x7f050034,
            never = 0x7f050035,
            paper_fill = 0x7f050036,
            paper_name = 0x7f050037,
            paper_pct = 0x7f050038,
            paper_sheets = 0x7f050039,
            paper_space = 0x7f05003a,
            print_fill = 0x7f05003b,
            print_overlay = 0x7f05003c,
            print_status = 0x7f05003d,
            print_track = 0x7f05003e,
            rb_bw = 0x7f05003f,
            rb_color = 0x7f050040,
            rg_color = 0x7f050041,
            rg_paper = 0x7f050042,
            rg_quality = 0x7f050043,
            scan = 0x7f050044,
            scan_beam = 0x7f050045,
            scan_end = 0x7f050046,
            scan_preview = 0x7f050047,
            scan_start = 0x7f050048,
            scan_status = 0x7f050049,
            seek_brightness = 0x7f05004a,
            seek_zoom = 0x7f05004b,
            settings = 0x7f05004c,
            stat_copies = 0x7f05004d,
            stat_maint = 0x7f05004e,
            stat_prints = 0x7f05004f,
            stat_scans = 0x7f050050,
            status_text = 0x7f050051,
            sw_sleep = 0x7f050052,
            sw_sound = 0x7f050053,
            toolbar = 0x7f050054,
            top = 0x7f050055,
            tv_brightness = 0x7f050056,
            tv_copies = 0x7f050057,
            tv_zoom = 0x7f050058,
            withText = 0x7f050059,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            fragment_about = 0x7f060000,
            fragment_copy = 0x7f060001,
            fragment_home = 0x7f060002,
            fragment_maintain = 0x7f060003,
            fragment_scan = 0x7f060004,
            fragment_settings = 0x7f060005,
            main = 0x7f060006,
        };
    }/*namespace layout*/

    namespace menu{
        enum : int {
            bottom_navigation = 0x7f070000,
            main = 0x7f070001,
        };
    }/*namespace menu*/

    namespace navigation{
        enum : int {
            nav_graph = 0x7f080000,
        };
    }/*namespace navigation*/

    namespace string{
        enum : int {
            about_device = 0x7f090000,
            about_features = 0x7f090001,
            about_highlights = 0x7f090002,
            about_intro = 0x7f090003,
            about_subtitle = 0x7f090004,
            about_use_cases = 0x7f090005,
            action_copy = 0x7f090006,
            action_maintain = 0x7f090007,
            action_scan = 0x7f090008,
            action_settings = 0x7f090009,
            app_name = 0x7f09000a,
            copy_busy = 0x7f09000b,
            copy_copies = 0x7f09000c,
            copy_label = 0x7f09000d,
            copy_start = 0x7f09000e,
            home_functions = 0x7f09000f,
            home_health = 0x7f090010,
            home_label = 0x7f090011,
            home_overview = 0x7f090012,
            home_supplies = 0x7f090013,
            home_tagline = 0x7f090014,
            ink_black = 0x7f090015,
            ink_color_cmy = 0x7f090016,
            label_color = 0x7f090017,
            label_ink = 0x7f090018,
            label_ip = 0x7f090019,
            label_paper = 0x7f09001a,
            label_quality = 0x7f09001b,
            label_resolution = 0x7f09001c,
            label_scale = 0x7f09001d,
            lang_zh = 0x7f09001e,
            loading = 0x7f09001f,
            maintain_align = 0x7f090020,
            maintain_align_desc = 0x7f090021,
            maintain_busy = 0x7f090022,
            maintain_clean = 0x7f090023,
            maintain_deep_desc = 0x7f090024,
            maintain_diagnose = 0x7f090025,
            maintain_head = 0x7f090026,
            maintain_label = 0x7f090027,
            maintain_last = 0x7f090028,
            maintain_nozzle_check = 0x7f090029,
            maintain_selftest = 0x7f09002a,
            maintain_test_desc = 0x7f09002b,
            menu_about = 0x7f09002c,
            menu_toggle_language = 0x7f09002d,
            menu_toggle_theme = 0x7f09002e,
            mode_color = 0x7f09002f,
            mode_mono = 0x7f090030,
            more_detail = 0x7f090031,
            network_good = 0x7f090032,
            paper_remaining = 0x7f090033,
            paper_tray = 0x7f090034,
            quality_draft = 0x7f090035,
            quality_standard = 0x7f090036,
            scan_last_mode = 0x7f090037,
            scan_start = 0x7f090038,
            settings_brightness = 0x7f090039,
            settings_datetime = 0x7f09003a,
            settings_display = 0x7f09003b,
            settings_label = 0x7f09003c,
            settings_language = 0x7f09003d,
            settings_network = 0x7f09003e,
            settings_pref = 0x7f09003f,
            settings_sleep = 0x7f090040,
            settings_sound = 0x7f090041,
            settings_system = 0x7f090042,
            stat_lifetime = 0x7f090043,
            stat_total_pages = 0x7f090044,
            stat_total_print = 0x7f090045,
            stat_total_scan = 0x7f090046,
            status_ready = 0x7f090047,
            status_ready_full = 0x7f090048,
        };
    }/*namespace string*/

    namespace style{
        enum : int {
            AppTheme = 0x7f0a0000,
            AppTheme_Dark = 0x7f0a0001,
            ToolbarTitle = 0x7f0a0002,
        };
    }/*namespace style*/

    namespace xml{
        enum : int {
            scene_scan = 0x7f0b0000,
        };
    }/*namespace xml*/

    namespace styleable{
    }/*namespace styleable*/

};//endof namespace R

}//endof namespace
