#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace gui_test{

namespace R{
    namespace anim{
        enum : int {
            slide_in_left = 0x7f010000,
        };
    }/*namespace anim*/

    namespace animator{
        enum : int {
            fade_in = 0x7f020000,
            keyframes_test = 0x7f020001,
            pathxy_test = 0x7f020002,
            statelist_scale = 0x7f020003,
            statelist_test = 0x7f020004,
        };
    }/*namespace animator*/

    namespace array{
        enum : int {
            difficulty = 0x7f030000,
            string_array_test = 0x7f030001,
        };
    }/*namespace array*/

    namespace attr{
        enum : int {
            testString = 0x7f040000,
            type1 = 0x7f040001,
            type10 = 0x7f040002,
            type11 = 0x7f040003,
            type12 = 0x7f040004,
            type13 = 0x7f040005,
            type14 = 0x7f040006,
            type15 = 0x7f040007,
            type16 = 0x7f040008,
            type17 = 0x7f040009,
            type18 = 0x7f04000a,
            type2 = 0x7f04000b,
            type3 = 0x7f04000c,
            type4 = 0x7f04000d,
            type5 = 0x7f04000e,
            type6 = 0x7f04000f,
            type7 = 0x7f040010,
            type8 = 0x7f040011,
            type9 = 0x7f040012,
            typeEmpty = 0x7f040013,
            typeUndefined = 0x7f040014,
        };
    }/*namespace attr*/

    namespace color{
        enum : int {
            ctd_text_primary = 0x7f050000,
            ctd_text_primary_dark = 0x7f050001,
            test_colors = 0x7f050002,
            typedarray_green = 0x7f050003,
        };
    }/*namespace color*/

    namespace drawable{
        enum : int {
            ctd_scrollbar_thumb = 0x7f060000,
            cts_apply_theme_color = 0x7f060001,
            cts_level_list_correct = 0x7f060002,
            cts_ripple_effect = 0x7f060003,
            cts_ripple_radius = 0x7f060004,
            cts_selector_correct = 0x7f060005,
            cts_vector_icon = 0x7f060006,
            cts_vector_size_1 = 0x7f060007,
            cts_vector_size_2 = 0x7f060008,
            gradientdrawable = 0x7f060009,
            nine_patch_odd_insets = 0x7f06000a,
            ninepatch_0 = 0x7f06000b,
            ninepatch_1 = 0x7f06000c,
            pass = 0x7f06000d,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            args_test = 0x7f070000,
            as_end = 0x7f070001,
            as_start = 0x7f070002,
            as_target = 0x7f070003,
            at_A = 0x7f070004,
            at_B = 0x7f070005,
            at_target = 0x7f070006,
            ca_target = 0x7f070007,
            cs_target = 0x7f070008,
            csa_end = 0x7f070009,
            csa_start = 0x7f07000a,
            csa_target = 0x7f07000b,
            ctd_scrollbars = 0x7f07000c,
            ctd_themed_attr = 0x7f07000d,
            ctd_themed_default = 0x7f07000e,
            dc_base = 0x7f07000f,
            dc_derived = 0x7f070010,
            dc_one = 0x7f070011,
            dc_three = 0x7f070012,
            dc_two = 0x7f070013,
            finish = 0x7f070014,
            finish_self = 0x7f070015,
            ift_end = 0x7f070016,
            ift_start = 0x7f070017,
            ift_tag_key = 0x7f070018,
            ift_target = 0x7f070019,
            kf_target = 0x7f07001a,
            lu_target = 0x7f07001b,
            mk_target = 0x7f07001c,
            ms_end = 0x7f07001d,
            ms_start = 0x7f07001e,
            ms_target = 0x7f07001f,
            nav_args = 0x7f070020,
            nav_host_test = 0x7f070021,
            nav_root = 0x7f070022,
            rv_end = 0x7f070023,
            rv_start = 0x7f070024,
            rv_target = 0x7f070025,
            second = 0x7f070026,
            second_fragment = 0x7f070027,
            second_test = 0x7f070028,
            self = 0x7f070029,
            st_base = 0x7f07002a,
            st_default = 0x7f07002b,
            st_target = 0x7f07002c,
            st_wide = 0x7f07002d,
            start_fragment = 0x7f07002e,
            start_test = 0x7f07002f,
            stg_tag_key = 0x7f070030,
            stg_target = 0x7f070031,
            sv_end = 0x7f070032,
            sv_key = 0x7f070033,
            sv_start = 0x7f070034,
            sv_target = 0x7f070035,
            sw_base = 0x7f070036,
            sw_large = 0x7f070037,
            sw_small = 0x7f070038,
            sw_target = 0x7f070039,
            t1 = 0x7f07003a,
            t2 = 0x7f07003b,
            trA = 0x7f07003c,
            trB = 0x7f07003d,
            trC = 0x7f07003e,
            vdd_target = 0x7f07003f,
            vdl_target = 0x7f070040,
            vds_target = 0x7f070041,
            vt1 = 0x7f070042,
            vt_all = 0x7f070043,
            vt_anim = 0x7f070044,
            vt_cur = 0x7f070045,
            vt_gate = 0x7f070046,
            vt_hold = 0x7f070047,
            vt_merge = 0x7f070048,
            vt_regex = 0x7f070049,
            vt_rev = 0x7f07004a,
            vt_shared = 0x7f07004b,
            vt_tag = 0x7f07004c,
            vtd_target = 0x7f07004d,
            vtn_target = 0x7f07004e,
            vtp_target = 0x7f07004f,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            ctd_themed_text = 0x7f080000,
        };
    }/*namespace layout*/

    namespace navigation{
        enum : int {
            nav_args_test = 0x7f090000,
            nav_host_test = 0x7f090001,
            nav_simple_test = 0x7f090002,
        };
    }/*namespace navigation*/

    namespace style{
        enum : int {
            StyleA = 0x7f0a0000,
            Theme_Empty = 0x7f0a0001,
            Theme_InlineString = 0x7f0a0002,
            Theme_OrientationDependent = 0x7f0a0003,
            Whatever = 0x7f0a0004,
            ctdThemeDark = 0x7f0a0005,
            ctdThemeLight = 0x7f0a0006,
            theme_face_probe = 0x7f0a0007,
        };
    }/*namespace style*/

    namespace xml{
        enum : int {
            constraintset_customattr = 0x7f0b0000,
            constraintset_parse = 0x7f0b0001,
            empty = 0x7f0b0002,
            keyframes_parse = 0x7f0b0003,
            motion_scene_autotransition = 0x7f0b0004,
            motion_scene_derive = 0x7f0b0005,
            motion_scene_lookup = 0x7f0b0006,
            motion_scene_parse = 0x7f0b0007,
            motion_scene_vt_allstates = 0x7f0b0008,
            motion_scene_vt_currentstate = 0x7f0b0009,
            motion_scene_vt_downup = 0x7f0b000a,
            motion_scene_vt_iftag = 0x7f0b000b,
            motion_scene_vt_merge = 0x7f0b000c,
            motion_scene_vt_nostate = 0x7f0b000d,
            motion_scene_vt_parse = 0x7f0b000e,
            motion_scene_vt_reverse = 0x7f0b000f,
            motion_scene_vt_setstag = 0x7f0b0010,
            motion_scene_vt_shared = 0x7f0b0011,
            motion_scene_vt_tagregex = 0x7f0b0012,
            stateset_match = 0x7f0b0013,
            stateset_switch = 0x7f0b0014,
            test_color = 0x7f0b0015,
            vt_customattr_setlevel = 0x7f0b0016,
            vt_delta_default = 0x7f0b0017,
            vt_delta_layout = 0x7f0b0018,
            vt_delta_scale = 0x7f0b0019,
        };
    }/*namespace xml*/

};//endof namespace R

}//endof namespace
