// GENERATED by gen_styleable.py — do not edit by hand.
// Source: attrs.xml  (fw-ids: framework_attrids.txt)
#ifndef __WIDGETEX_STYLEABLE_H__
#define __WIDGETEX_STYLEABLE_H__
#include <cstdint>
#include <cstddef>
namespace cdroid {
namespace fw_attr {
    namespace CoordinatorLayout {
        constexpr uint32_t keylines = 0x7f010000;
        constexpr uint32_t statusBarBackground = 0x7f010001;
    }
    namespace CoordinatorLayoutLayout {
        constexpr uint32_t layout_gravity = 0x010100b3;
        constexpr uint32_t layout_behavior = 0x7f010002;
        constexpr uint32_t layout_anchor = 0x7f010003;
        constexpr uint32_t layout_keyline = 0x7f010004;
        constexpr uint32_t layout_anchorGravity = 0x7f010005;
        constexpr uint32_t layout_insetEdge = 0x7f010006;
        constexpr uint32_t layout_dodgeInsetEdges = 0x7f010007;
    }
    namespace FlexboxLayout {
        constexpr uint32_t flexDirection = 0x7f010008;
        constexpr uint32_t flexWrap = 0x7f010009;
        constexpr uint32_t justifyContent = 0x7f01000a;
        constexpr uint32_t alignItems = 0x7f01000b;
        constexpr uint32_t alignContent = 0x7f01000c;
    }
    namespace FlexboxLayoutLayout {
        constexpr uint32_t layout_order = 0x7f01000d;
        constexpr uint32_t layout_flexBasisPercent = 0x7f01000e;
        constexpr uint32_t layout_flexGrow = 0x7f01000f;
        constexpr uint32_t layout_flexShrink = 0x7f010010;
        constexpr uint32_t layout_alignSelf = 0x7f010011;
        constexpr uint32_t layout_wrapBefore = 0x7f010012;
    }
} // namespace fw_attr

namespace styleable {
    namespace CoordinatorLayout {
        enum { keylines, statusBarBackground, COUNT };
        extern const uint32_t IDS[];
    }
    namespace CoordinatorLayoutLayout {
        enum { layout_gravity, layout_behavior, layout_anchor, layout_keyline, layout_anchorGravity, layout_insetEdge, layout_dodgeInsetEdges, COUNT };
        extern const uint32_t IDS[];
    }
    namespace FlexboxLayout {
        enum { flexDirection, flexWrap, justifyContent, alignItems, alignContent, COUNT };
        extern const uint32_t IDS[];
    }
    namespace FlexboxLayoutLayout {
        enum { layout_order, layout_flexBasisPercent, layout_flexGrow, layout_flexShrink, layout_alignSelf, layout_wrapBefore, COUNT };
        extern const uint32_t IDS[];
    }
} // namespace styleable
} // namespace cdroid
#endif // __WIDGETEX_STYLEABLE_H__
