// GENERATED by gen_styleable.py — do not edit by hand.
// Source: attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml  (fw-ids: framework_attrids.txt)
#ifndef __WIDGETEX_STYLEABLE_H__
#define __WIDGETEX_STYLEABLE_H__
#include <cstdint>
#include <cstddef>
namespace cdroid {
namespace internal { namespace R { namespace attr {
    // Standalone widgetEx-declared attrs (top-level <attr> in attrs.xml;
    // ids pinned in the component res/values/public.xml, 0x02 shared-lib)
    constexpr uint32_t animateCircleAngleTo = 0x02010071;
    constexpr uint32_t animateRelativeTo = 0x02010070;
    constexpr uint32_t barrierAllowsGoneWidgets = 0x02010017;
    constexpr uint32_t barrierDirection = 0x02010016;
    constexpr uint32_t barrierMargin = 0x02010018;
    constexpr uint32_t chainUseRtl = 0x0201001b;
    constexpr uint32_t circularflow_angles = 0x0201002f;
    constexpr uint32_t circularflow_defaultAngle = 0x02010032;
    constexpr uint32_t circularflow_defaultRadius = 0x02010031;
    constexpr uint32_t circularflow_radiusInDP = 0x0201002e;
    constexpr uint32_t circularflow_viewCenter = 0x02010030;
    constexpr uint32_t constraintSet = 0x02010015;
    constexpr uint32_t constraint_referenced_ids = 0x02010019;
    constexpr uint32_t constraint_referenced_tags = 0x0201001a;
    constexpr uint32_t curveFit = 0x02010099;
    constexpr uint32_t defaultDuration = 0x020100bb;
    constexpr uint32_t dragDirection = 0x0201008e;
    constexpr uint32_t drawPath = 0x02010076;
    constexpr uint32_t flow_firstHorizontalBias = 0x02010028;
    constexpr uint32_t flow_firstHorizontalStyle = 0x02010026;
    constexpr uint32_t flow_firstVerticalBias = 0x02010029;
    constexpr uint32_t flow_firstVerticalStyle = 0x02010027;
    constexpr uint32_t flow_horizontalAlign = 0x02010023;
    constexpr uint32_t flow_horizontalBias = 0x02010025;
    constexpr uint32_t flow_horizontalGap = 0x02010020;
    constexpr uint32_t flow_horizontalStyle = 0x0201001c;
    constexpr uint32_t flow_lastHorizontalBias = 0x0201002c;
    constexpr uint32_t flow_lastHorizontalStyle = 0x0201002a;
    constexpr uint32_t flow_lastVerticalBias = 0x0201002d;
    constexpr uint32_t flow_lastVerticalStyle = 0x0201002b;
    constexpr uint32_t flow_maxElementsWrap = 0x0201001f;
    constexpr uint32_t flow_verticalAlign = 0x02010022;
    constexpr uint32_t flow_verticalBias = 0x02010024;
    constexpr uint32_t flow_verticalGap = 0x02010021;
    constexpr uint32_t flow_verticalStyle = 0x0201001d;
    constexpr uint32_t flow_wrapMode = 0x0201001e;
    constexpr uint32_t framePosition = 0x02010097;
    constexpr uint32_t guidelineUseRtl = 0x02010039;
    constexpr uint32_t layoutDescription = 0x02010014;
    constexpr uint32_t layoutDuringTransition = 0x0201007f;
    constexpr uint32_t layout_constrainedHeight = 0x02010054;
    constexpr uint32_t layout_constrainedWidth = 0x02010053;
    constexpr uint32_t layout_constraintBaseline_creator = 0x02010063;
    constexpr uint32_t layout_constraintBaseline_toBaselineOf = 0x02010042;
    constexpr uint32_t layout_constraintBaseline_toBottomOf = 0x02010044;
    constexpr uint32_t layout_constraintBaseline_toTopOf = 0x02010043;
    constexpr uint32_t layout_constraintBottom_creator = 0x02010062;
    constexpr uint32_t layout_constraintBottom_toBottomOf = 0x02010041;
    constexpr uint32_t layout_constraintBottom_toTopOf = 0x02010040;
    constexpr uint32_t layout_constraintCircle = 0x02010033;
    constexpr uint32_t layout_constraintCircleAngle = 0x02010035;
    constexpr uint32_t layout_constraintCircleRadius = 0x02010034;
    constexpr uint32_t layout_constraintDimensionRatio = 0x02010064;
    constexpr uint32_t layout_constraintEnd_toEndOf = 0x02010048;
    constexpr uint32_t layout_constraintEnd_toStartOf = 0x02010047;
    constexpr uint32_t layout_constraintGuide_begin = 0x02010036;
    constexpr uint32_t layout_constraintGuide_end = 0x02010037;
    constexpr uint32_t layout_constraintGuide_percent = 0x02010038;
    constexpr uint32_t layout_constraintHeight = 0x02010052;
    constexpr uint32_t layout_constraintHeight_max = 0x0201005d;
    constexpr uint32_t layout_constraintHeight_min = 0x0201005c;
    constexpr uint32_t layout_constraintHeight_percent = 0x0201005e;
    constexpr uint32_t layout_constraintHorizontal_bias = 0x02010055;
    constexpr uint32_t layout_constraintHorizontal_chainStyle = 0x02010067;
    constexpr uint32_t layout_constraintHorizontal_weight = 0x02010065;
    constexpr uint32_t layout_constraintLeft_creator = 0x0201005f;
    constexpr uint32_t layout_constraintLeft_toLeftOf = 0x0201003a;
    constexpr uint32_t layout_constraintLeft_toRightOf = 0x0201003b;
    constexpr uint32_t layout_constraintRight_creator = 0x02010061;
    constexpr uint32_t layout_constraintRight_toLeftOf = 0x0201003c;
    constexpr uint32_t layout_constraintRight_toRightOf = 0x0201003d;
    constexpr uint32_t layout_constraintStart_toEndOf = 0x02010045;
    constexpr uint32_t layout_constraintStart_toStartOf = 0x02010046;
    constexpr uint32_t layout_constraintTag = 0x0201006b;
    constexpr uint32_t layout_constraintTop_creator = 0x02010060;
    constexpr uint32_t layout_constraintTop_toBottomOf = 0x0201003f;
    constexpr uint32_t layout_constraintTop_toTopOf = 0x0201003e;
    constexpr uint32_t layout_constraintVertical_bias = 0x02010056;
    constexpr uint32_t layout_constraintVertical_chainStyle = 0x02010068;
    constexpr uint32_t layout_constraintVertical_weight = 0x02010066;
    constexpr uint32_t layout_constraintWidth = 0x02010051;
    constexpr uint32_t layout_constraintWidth_max = 0x0201005a;
    constexpr uint32_t layout_constraintWidth_min = 0x02010059;
    constexpr uint32_t layout_constraintWidth_percent = 0x0201005b;
    constexpr uint32_t layout_editor_absoluteX = 0x02010069;
    constexpr uint32_t layout_editor_absoluteY = 0x0201006a;
    constexpr uint32_t layout_goneMarginBaseline = 0x0201004f;
    constexpr uint32_t layout_goneMarginBottom = 0x0201004c;
    constexpr uint32_t layout_goneMarginEnd = 0x0201004e;
    constexpr uint32_t layout_goneMarginLeft = 0x02010049;
    constexpr uint32_t layout_goneMarginRight = 0x0201004b;
    constexpr uint32_t layout_goneMarginStart = 0x0201004d;
    constexpr uint32_t layout_goneMarginTop = 0x0201004a;
    constexpr uint32_t layout_marginBaseline = 0x02010050;
    constexpr uint32_t layout_wrapBehaviorInParent = 0x0201006c;
    constexpr uint32_t motionPathRotate = 0x020100ba;
    constexpr uint32_t motionProgress = 0x02010077;
    constexpr uint32_t motionStagger = 0x02010078;
    constexpr uint32_t motionTarget = 0x02010098;
    constexpr uint32_t onStateTransition = 0x020100b2;
    constexpr uint32_t pathMotionArc = 0x02010073;
    constexpr uint32_t pivotAnchor = 0x0201006e;
    constexpr uint32_t polarRelativeTo = 0x02010074;
    constexpr uint32_t quantizeMotionInterpolator = 0x0201007b;
    constexpr uint32_t quantizeMotionPhase = 0x0201007a;
    constexpr uint32_t quantizeMotionSteps = 0x02010079;
    constexpr uint32_t sizePercent = 0x0201009f;
    constexpr uint32_t touchAnchorId = 0x0201008f;
    constexpr uint32_t touchAnchorSide = 0x02010090;
    constexpr uint32_t transformPivotTarget = 0x0201006f;
    constexpr uint32_t transitionDisable = 0x0201007e;
    constexpr uint32_t transitionEasing = 0x02010072;
    constexpr uint32_t transitionPathRotate = 0x02010075;
    constexpr uint32_t viewTransitionMode = 0x020100b1;
    constexpr uint32_t visibilityMode = 0x0201006d;
    constexpr uint32_t waveDecay = 0x020100a5;
    constexpr uint32_t waveOffset = 0x020100a3;
    constexpr uint32_t wavePeriod = 0x020100a2;
    constexpr uint32_t wavePhase = 0x020100a1;
    constexpr uint32_t waveShape = 0x020100a0;
    constexpr uint32_t waveVariesBy = 0x020100a4;
    constexpr uint32_t placeholder_emptyVisibility = 0x02010110;
    constexpr uint32_t grid_rows = 0x0201010a;
    constexpr uint32_t grid_columns = 0x02010106;
    constexpr uint32_t grid_spans = 0x0201010c;
    constexpr uint32_t grid_skips = 0x0201010b;
    constexpr uint32_t grid_rowWeights = 0x02010109;
    constexpr uint32_t grid_columnWeights = 0x02010105;
    constexpr uint32_t grid_orientation = 0x02010108;
    constexpr uint32_t grid_horizontalGaps = 0x02010107;
    constexpr uint32_t grid_verticalGaps = 0x0201010f;
    constexpr uint32_t grid_validateInputs = 0x0201010e;
    constexpr uint32_t grid_useRtl = 0x0201010d;
    constexpr uint32_t carousel_firstView = 0x020100fc;
    constexpr uint32_t carousel_backwardTransition = 0x020100fa;
    constexpr uint32_t carousel_forwardTransition = 0x020100fd;
    constexpr uint32_t carousel_previousState = 0x02010100;
    constexpr uint32_t carousel_nextState = 0x020100ff;
    constexpr uint32_t carousel_emptyViews_behavior = 0x020100fb;
    constexpr uint32_t carousel_touchUp_dampeningFactor = 0x02010101;
    constexpr uint32_t carousel_touchUpMode = 0x02010103;
    constexpr uint32_t carousel_touchUp_velocityThreshold = 0x02010102;
    constexpr uint32_t carousel_infinite = 0x020100fe;
    constexpr uint32_t recyclerViewStyle = 0x0201014d;
    constexpr uint32_t tabStyle = 0x020100f6;
    constexpr uint32_t tabSecondaryStyle = 0x020100f7;
    constexpr uint32_t startDestination = 0x02010120;
    constexpr uint32_t route = 0x02010121;
    constexpr uint32_t destination = 0x02010122;
    constexpr uint32_t popUpTo = 0x02010123;
    constexpr uint32_t popUpToInclusive = 0x02010124;
    constexpr uint32_t popUpToSaveState = 0x02010125;
    constexpr uint32_t restoreState = 0x02010126;
    constexpr uint32_t launchSingleTop = 0x02010127;
    constexpr uint32_t enterAnim = 0x02010128;
    constexpr uint32_t exitAnim = 0x02010129;
    constexpr uint32_t popEnterAnim = 0x0201012a;
    constexpr uint32_t popExitAnim = 0x0201012b;
    constexpr uint32_t graph = 0x0201012c;
    constexpr uint32_t argType = 0x0201012e;
    constexpr uint32_t nullable = 0x0201012f;
    constexpr uint32_t dataPattern = 0x02010132;
} } } // namespace internal::R::attr
namespace internal { namespace R { namespace styleable {
    // CoordinatorLayout (2 attrs)
    extern const uint32_t CoordinatorLayout[];
    constexpr int CoordinatorLayout_keylines = 0;
    constexpr int CoordinatorLayout_statusBarBackground = 1;

    // CoordinatorLayoutLayout (7 attrs)
    extern const uint32_t CoordinatorLayoutLayout[];
    constexpr int CoordinatorLayoutLayout_layout_gravity = 0;
    constexpr int CoordinatorLayoutLayout_layout_behavior = 1;
    constexpr int CoordinatorLayoutLayout_layout_anchor = 2;
    constexpr int CoordinatorLayoutLayout_layout_keyline = 3;
    constexpr int CoordinatorLayoutLayout_layout_anchorGravity = 4;
    constexpr int CoordinatorLayoutLayout_layout_insetEdge = 5;
    constexpr int CoordinatorLayoutLayout_layout_dodgeInsetEdges = 6;

    // FlexboxLayout (12 attrs)
    extern const uint32_t FlexboxLayout[];
    constexpr int FlexboxLayout_flexDirection = 0;
    constexpr int FlexboxLayout_flexWrap = 1;
    constexpr int FlexboxLayout_justifyContent = 2;
    constexpr int FlexboxLayout_alignItems = 3;
    constexpr int FlexboxLayout_alignContent = 4;
    constexpr int FlexboxLayout_dividerDrawable = 5;
    constexpr int FlexboxLayout_dividerDrawableHorizontal = 6;
    constexpr int FlexboxLayout_dividerDrawableVertical = 7;
    constexpr int FlexboxLayout_showDivider = 8;
    constexpr int FlexboxLayout_showDividerHorizontal = 9;
    constexpr int FlexboxLayout_showDividerVertical = 10;
    constexpr int FlexboxLayout_maxLine = 11;

    // FlexboxLayoutLayout (10 attrs)
    extern const uint32_t FlexboxLayoutLayout[];
    constexpr int FlexboxLayoutLayout_layout_order = 0;
    constexpr int FlexboxLayoutLayout_layout_flexGrow = 1;
    constexpr int FlexboxLayoutLayout_layout_flexShrink = 2;
    constexpr int FlexboxLayoutLayout_layout_flexBasisPercent = 3;
    constexpr int FlexboxLayoutLayout_layout_alignSelf = 4;
    constexpr int FlexboxLayoutLayout_layout_minWidth = 5;
    constexpr int FlexboxLayoutLayout_layout_minHeight = 6;
    constexpr int FlexboxLayoutLayout_layout_maxWidth = 7;
    constexpr int FlexboxLayoutLayout_layout_maxHeight = 8;
    constexpr int FlexboxLayoutLayout_layout_wrapBefore = 9;

    // ConstraintLayoutLayout (115 attrs)
    extern const uint32_t ConstraintLayoutLayout[];
    constexpr int ConstraintLayoutLayout_orientation = 0;
    constexpr int ConstraintLayoutLayout_minWidth = 1;
    constexpr int ConstraintLayoutLayout_minHeight = 2;
    constexpr int ConstraintLayoutLayout_maxWidth = 3;
    constexpr int ConstraintLayoutLayout_maxHeight = 4;
    constexpr int ConstraintLayoutLayout_visibility = 5;
    constexpr int ConstraintLayoutLayout_elevation = 6;
    constexpr int ConstraintLayoutLayout_layout_optimizationLevel = 7;
    constexpr int ConstraintLayoutLayout_layoutDescription = 8;
    constexpr int ConstraintLayoutLayout_constraintSet = 9;
    constexpr int ConstraintLayoutLayout_barrierDirection = 10;
    constexpr int ConstraintLayoutLayout_barrierAllowsGoneWidgets = 11;
    constexpr int ConstraintLayoutLayout_barrierMargin = 12;
    constexpr int ConstraintLayoutLayout_constraint_referenced_ids = 13;
    constexpr int ConstraintLayoutLayout_constraint_referenced_tags = 14;
    constexpr int ConstraintLayoutLayout_chainUseRtl = 15;
    constexpr int ConstraintLayoutLayout_flow_horizontalStyle = 16;
    constexpr int ConstraintLayoutLayout_flow_verticalStyle = 17;
    constexpr int ConstraintLayoutLayout_flow_wrapMode = 18;
    constexpr int ConstraintLayoutLayout_flow_maxElementsWrap = 19;
    constexpr int ConstraintLayoutLayout_flow_horizontalGap = 20;
    constexpr int ConstraintLayoutLayout_flow_verticalGap = 21;
    constexpr int ConstraintLayoutLayout_padding = 22;
    constexpr int ConstraintLayoutLayout_paddingTop = 23;
    constexpr int ConstraintLayoutLayout_paddingBottom = 24;
    constexpr int ConstraintLayoutLayout_paddingLeft = 25;
    constexpr int ConstraintLayoutLayout_paddingRight = 26;
    constexpr int ConstraintLayoutLayout_paddingStart = 27;
    constexpr int ConstraintLayoutLayout_paddingEnd = 28;
    constexpr int ConstraintLayoutLayout_flow_verticalAlign = 29;
    constexpr int ConstraintLayoutLayout_flow_horizontalAlign = 30;
    constexpr int ConstraintLayoutLayout_flow_verticalBias = 31;
    constexpr int ConstraintLayoutLayout_flow_horizontalBias = 32;
    constexpr int ConstraintLayoutLayout_flow_firstHorizontalStyle = 33;
    constexpr int ConstraintLayoutLayout_flow_firstVerticalStyle = 34;
    constexpr int ConstraintLayoutLayout_flow_firstHorizontalBias = 35;
    constexpr int ConstraintLayoutLayout_flow_firstVerticalBias = 36;
    constexpr int ConstraintLayoutLayout_flow_lastHorizontalStyle = 37;
    constexpr int ConstraintLayoutLayout_flow_lastVerticalStyle = 38;
    constexpr int ConstraintLayoutLayout_flow_lastHorizontalBias = 39;
    constexpr int ConstraintLayoutLayout_flow_lastVerticalBias = 40;
    constexpr int ConstraintLayoutLayout_circularflow_radiusInDP = 41;
    constexpr int ConstraintLayoutLayout_circularflow_angles = 42;
    constexpr int ConstraintLayoutLayout_circularflow_viewCenter = 43;
    constexpr int ConstraintLayoutLayout_circularflow_defaultRadius = 44;
    constexpr int ConstraintLayoutLayout_circularflow_defaultAngle = 45;
    constexpr int ConstraintLayoutLayout_layout_constraintCircle = 46;
    constexpr int ConstraintLayoutLayout_layout_constraintCircleRadius = 47;
    constexpr int ConstraintLayoutLayout_layout_constraintCircleAngle = 48;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_begin = 49;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_end = 50;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_percent = 51;
    constexpr int ConstraintLayoutLayout_guidelineUseRtl = 52;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_toLeftOf = 53;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_toRightOf = 54;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_toLeftOf = 55;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_toRightOf = 56;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_toTopOf = 57;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_toBottomOf = 58;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_toTopOf = 59;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_toBottomOf = 60;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toBaselineOf = 61;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toTopOf = 62;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toBottomOf = 63;
    constexpr int ConstraintLayoutLayout_layout_constraintStart_toEndOf = 64;
    constexpr int ConstraintLayoutLayout_layout_constraintStart_toStartOf = 65;
    constexpr int ConstraintLayoutLayout_layout_constraintEnd_toStartOf = 66;
    constexpr int ConstraintLayoutLayout_layout_constraintEnd_toEndOf = 67;
    constexpr int ConstraintLayoutLayout_layout_goneMarginLeft = 68;
    constexpr int ConstraintLayoutLayout_layout_goneMarginTop = 69;
    constexpr int ConstraintLayoutLayout_layout_goneMarginRight = 70;
    constexpr int ConstraintLayoutLayout_layout_goneMarginBottom = 71;
    constexpr int ConstraintLayoutLayout_layout_goneMarginStart = 72;
    constexpr int ConstraintLayoutLayout_layout_goneMarginEnd = 73;
    constexpr int ConstraintLayoutLayout_layout_goneMarginBaseline = 74;
    constexpr int ConstraintLayoutLayout_layout_marginBaseline = 75;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth = 76;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight = 77;
    constexpr int ConstraintLayoutLayout_layout_width = 78;
    constexpr int ConstraintLayoutLayout_layout_height = 79;
    constexpr int ConstraintLayoutLayout_layout_margin = 80;
    constexpr int ConstraintLayoutLayout_layout_marginHorizontal = 81;
    constexpr int ConstraintLayoutLayout_layout_marginVertical = 82;
    constexpr int ConstraintLayoutLayout_layout_marginLeft = 83;
    constexpr int ConstraintLayoutLayout_layout_marginRight = 84;
    constexpr int ConstraintLayoutLayout_layout_marginTop = 85;
    constexpr int ConstraintLayoutLayout_layout_marginBottom = 86;
    constexpr int ConstraintLayoutLayout_layout_marginStart = 87;
    constexpr int ConstraintLayoutLayout_layout_marginEnd = 88;
    constexpr int ConstraintLayoutLayout_layout_constrainedWidth = 89;
    constexpr int ConstraintLayoutLayout_layout_constrainedHeight = 90;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_bias = 91;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_bias = 92;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_default = 93;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_default = 94;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_min = 95;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_max = 96;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_percent = 97;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_min = 98;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_max = 99;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_percent = 100;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_creator = 101;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_creator = 102;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_creator = 103;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_creator = 104;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_creator = 105;
    constexpr int ConstraintLayoutLayout_layout_constraintDimensionRatio = 106;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_weight = 107;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_weight = 108;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_chainStyle = 109;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_chainStyle = 110;
    constexpr int ConstraintLayoutLayout_layout_editor_absoluteX = 111;
    constexpr int ConstraintLayoutLayout_layout_editor_absoluteY = 112;
    constexpr int ConstraintLayoutLayout_layout_constraintTag = 113;
    constexpr int ConstraintLayoutLayout_layout_wrapBehaviorInParent = 114;

    // Constraint (124 attrs)
    extern const uint32_t Constraint[];
    constexpr int Constraint_orientation = 0;
    constexpr int Constraint_id = 1;
    constexpr int Constraint_visibility = 2;
    constexpr int Constraint_visibilityMode = 3;
    constexpr int Constraint_alpha = 4;
    constexpr int Constraint_elevation = 5;
    constexpr int Constraint_rotation = 6;
    constexpr int Constraint_rotationX = 7;
    constexpr int Constraint_rotationY = 8;
    constexpr int Constraint_scaleX = 9;
    constexpr int Constraint_scaleY = 10;
    constexpr int Constraint_pivotAnchor = 11;
    constexpr int Constraint_transformPivotX = 12;
    constexpr int Constraint_transformPivotY = 13;
    constexpr int Constraint_transformPivotTarget = 14;
    constexpr int Constraint_translationX = 15;
    constexpr int Constraint_translationY = 16;
    constexpr int Constraint_translationZ = 17;
    constexpr int Constraint_layout_width = 18;
    constexpr int Constraint_layout_height = 19;
    constexpr int Constraint_layout_constraintWidth = 20;
    constexpr int Constraint_layout_constraintHeight = 21;
    constexpr int Constraint_layout_marginStart = 22;
    constexpr int Constraint_layout_marginBottom = 23;
    constexpr int Constraint_layout_marginTop = 24;
    constexpr int Constraint_layout_marginEnd = 25;
    constexpr int Constraint_layout_marginLeft = 26;
    constexpr int Constraint_layout_marginRight = 27;
    constexpr int Constraint_layout_constraintCircle = 28;
    constexpr int Constraint_layout_constraintCircleRadius = 29;
    constexpr int Constraint_layout_constraintCircleAngle = 30;
    constexpr int Constraint_layout_constraintGuide_begin = 31;
    constexpr int Constraint_layout_constraintGuide_end = 32;
    constexpr int Constraint_layout_constraintGuide_percent = 33;
    constexpr int Constraint_guidelineUseRtl = 34;
    constexpr int Constraint_layout_constraintLeft_toLeftOf = 35;
    constexpr int Constraint_layout_constraintLeft_toRightOf = 36;
    constexpr int Constraint_layout_constraintRight_toLeftOf = 37;
    constexpr int Constraint_layout_constraintRight_toRightOf = 38;
    constexpr int Constraint_layout_constraintTop_toTopOf = 39;
    constexpr int Constraint_layout_constraintTop_toBottomOf = 40;
    constexpr int Constraint_layout_constraintBottom_toTopOf = 41;
    constexpr int Constraint_layout_constraintBottom_toBottomOf = 42;
    constexpr int Constraint_layout_constraintBaseline_toBaselineOf = 43;
    constexpr int Constraint_layout_constraintBaseline_toTopOf = 44;
    constexpr int Constraint_layout_constraintBaseline_toBottomOf = 45;
    constexpr int Constraint_layout_constraintStart_toEndOf = 46;
    constexpr int Constraint_layout_constraintStart_toStartOf = 47;
    constexpr int Constraint_layout_constraintEnd_toStartOf = 48;
    constexpr int Constraint_layout_constraintEnd_toEndOf = 49;
    constexpr int Constraint_layout_goneMarginLeft = 50;
    constexpr int Constraint_layout_goneMarginTop = 51;
    constexpr int Constraint_layout_goneMarginRight = 52;
    constexpr int Constraint_layout_goneMarginBottom = 53;
    constexpr int Constraint_layout_goneMarginStart = 54;
    constexpr int Constraint_layout_goneMarginEnd = 55;
    constexpr int Constraint_layout_goneMarginBaseline = 56;
    constexpr int Constraint_layout_marginBaseline = 57;
    constexpr int Constraint_layout_constrainedWidth = 58;
    constexpr int Constraint_layout_constrainedHeight = 59;
    constexpr int Constraint_layout_constraintHorizontal_bias = 60;
    constexpr int Constraint_layout_constraintVertical_bias = 61;
    constexpr int Constraint_layout_constraintWidth_default = 62;
    constexpr int Constraint_layout_constraintHeight_default = 63;
    constexpr int Constraint_layout_constraintWidth_min = 64;
    constexpr int Constraint_layout_constraintWidth_max = 65;
    constexpr int Constraint_layout_constraintWidth_percent = 66;
    constexpr int Constraint_layout_constraintHeight_min = 67;
    constexpr int Constraint_layout_constraintHeight_max = 68;
    constexpr int Constraint_layout_constraintHeight_percent = 69;
    constexpr int Constraint_layout_constraintLeft_creator = 70;
    constexpr int Constraint_layout_constraintTop_creator = 71;
    constexpr int Constraint_layout_constraintRight_creator = 72;
    constexpr int Constraint_layout_constraintBottom_creator = 73;
    constexpr int Constraint_layout_constraintBaseline_creator = 74;
    constexpr int Constraint_layout_constraintDimensionRatio = 75;
    constexpr int Constraint_layout_constraintHorizontal_weight = 76;
    constexpr int Constraint_layout_constraintVertical_weight = 77;
    constexpr int Constraint_layout_constraintHorizontal_chainStyle = 78;
    constexpr int Constraint_layout_constraintVertical_chainStyle = 79;
    constexpr int Constraint_layout_editor_absoluteX = 80;
    constexpr int Constraint_layout_editor_absoluteY = 81;
    constexpr int Constraint_layout_wrapBehaviorInParent = 82;
    constexpr int Constraint_barrierDirection = 83;
    constexpr int Constraint_barrierMargin = 84;
    constexpr int Constraint_constraint_referenced_ids = 85;
    constexpr int Constraint_constraint_referenced_tags = 86;
    constexpr int Constraint_maxHeight = 87;
    constexpr int Constraint_maxWidth = 88;
    constexpr int Constraint_minHeight = 89;
    constexpr int Constraint_minWidth = 90;
    constexpr int Constraint_barrierAllowsGoneWidgets = 91;
    constexpr int Constraint_chainUseRtl = 92;
    constexpr int Constraint_flow_horizontalStyle = 93;
    constexpr int Constraint_flow_verticalStyle = 94;
    constexpr int Constraint_flow_verticalAlign = 95;
    constexpr int Constraint_flow_horizontalAlign = 96;
    constexpr int Constraint_flow_verticalBias = 97;
    constexpr int Constraint_flow_horizontalBias = 98;
    constexpr int Constraint_flow_wrapMode = 99;
    constexpr int Constraint_flow_maxElementsWrap = 100;
    constexpr int Constraint_flow_horizontalGap = 101;
    constexpr int Constraint_flow_verticalGap = 102;
    constexpr int Constraint_flow_firstHorizontalStyle = 103;
    constexpr int Constraint_flow_firstVerticalStyle = 104;
    constexpr int Constraint_flow_firstHorizontalBias = 105;
    constexpr int Constraint_flow_firstVerticalBias = 106;
    constexpr int Constraint_flow_lastHorizontalStyle = 107;
    constexpr int Constraint_flow_lastVerticalStyle = 108;
    constexpr int Constraint_flow_lastHorizontalBias = 109;
    constexpr int Constraint_flow_lastVerticalBias = 110;
    constexpr int Constraint_animateRelativeTo = 111;
    constexpr int Constraint_animateCircleAngleTo = 112;
    constexpr int Constraint_transitionEasing = 113;
    constexpr int Constraint_pathMotionArc = 114;
    constexpr int Constraint_polarRelativeTo = 115;
    constexpr int Constraint_transitionPathRotate = 116;
    constexpr int Constraint_drawPath = 117;
    constexpr int Constraint_motionProgress = 118;
    constexpr int Constraint_layout_constraintTag = 119;
    constexpr int Constraint_motionStagger = 120;
    constexpr int Constraint_quantizeMotionSteps = 121;
    constexpr int Constraint_quantizeMotionPhase = 122;
    constexpr int Constraint_quantizeMotionInterpolator = 123;

    // Transition (11 attrs)
    extern const uint32_t Transition[];
    constexpr int Transition_id = 0;
    constexpr int Transition_constraintSetStart = 1;
    constexpr int Transition_constraintSetEnd = 2;
    constexpr int Transition_transitionDisable = 3;
    constexpr int Transition_layoutDuringTransition = 4;
    constexpr int Transition_pathMotionArc = 5;
    constexpr int Transition_autoTransition = 6;
    constexpr int Transition_motionInterpolator = 7;
    constexpr int Transition_duration = 8;
    constexpr int Transition_staggered = 9;
    constexpr int Transition_transitionFlags = 10;

    // MotionScene (2 attrs)
    extern const uint32_t MotionScene[];
    constexpr int MotionScene_defaultDuration = 0;
    constexpr int MotionScene_layoutDuringTransition = 1;

    // OnSwipe (19 attrs)
    extern const uint32_t OnSwipe[];
    constexpr int OnSwipe_dragScale = 0;
    constexpr int OnSwipe_dragThreshold = 1;
    constexpr int OnSwipe_autoCompleteMode = 2;
    constexpr int OnSwipe_maxVelocity = 3;
    constexpr int OnSwipe_maxAcceleration = 4;
    constexpr int OnSwipe_springMass = 5;
    constexpr int OnSwipe_springStiffness = 6;
    constexpr int OnSwipe_springDamping = 7;
    constexpr int OnSwipe_springStopThreshold = 8;
    constexpr int OnSwipe_springBoundary = 9;
    constexpr int OnSwipe_dragDirection = 10;
    constexpr int OnSwipe_touchAnchorId = 11;
    constexpr int OnSwipe_touchAnchorSide = 12;
    constexpr int OnSwipe_rotationCenterId = 13;
    constexpr int OnSwipe_touchRegionId = 14;
    constexpr int OnSwipe_limitBoundsTo = 15;
    constexpr int OnSwipe_nestedScrollFlags = 16;
    constexpr int OnSwipe_moveWhenScrollAtTop = 17;
    constexpr int OnSwipe_onTouchUp = 18;

    // OnClick (2 attrs)
    extern const uint32_t OnClick[];
    constexpr int OnClick_targetId = 0;
    constexpr int OnClick_clickAction = 1;

    // KeyAttribute (19 attrs)
    extern const uint32_t KeyAttribute[];
    constexpr int KeyAttribute_framePosition = 0;
    constexpr int KeyAttribute_motionTarget = 1;
    constexpr int KeyAttribute_transitionEasing = 2;
    constexpr int KeyAttribute_curveFit = 3;
    constexpr int KeyAttribute_motionProgress = 4;
    constexpr int KeyAttribute_alpha = 5;
    constexpr int KeyAttribute_elevation = 6;
    constexpr int KeyAttribute_rotation = 7;
    constexpr int KeyAttribute_rotationX = 8;
    constexpr int KeyAttribute_rotationY = 9;
    constexpr int KeyAttribute_transformPivotX = 10;
    constexpr int KeyAttribute_transformPivotY = 11;
    constexpr int KeyAttribute_transformPivotTarget = 12;
    constexpr int KeyAttribute_transitionPathRotate = 13;
    constexpr int KeyAttribute_scaleX = 14;
    constexpr int KeyAttribute_scaleY = 15;
    constexpr int KeyAttribute_translationX = 16;
    constexpr int KeyAttribute_translationY = 17;
    constexpr int KeyAttribute_translationZ = 18;

    // KeyPosition (12 attrs)
    extern const uint32_t KeyPosition[];
    constexpr int KeyPosition_keyPositionType = 0;
    constexpr int KeyPosition_percentX = 1;
    constexpr int KeyPosition_percentY = 2;
    constexpr int KeyPosition_percentWidth = 3;
    constexpr int KeyPosition_percentHeight = 4;
    constexpr int KeyPosition_framePosition = 5;
    constexpr int KeyPosition_motionTarget = 6;
    constexpr int KeyPosition_transitionEasing = 7;
    constexpr int KeyPosition_pathMotionArc = 8;
    constexpr int KeyPosition_curveFit = 9;
    constexpr int KeyPosition_drawPath = 10;
    constexpr int KeyPosition_sizePercent = 11;

    // KeyCycle (21 attrs)
    extern const uint32_t KeyCycle[];
    constexpr int KeyCycle_motionTarget = 0;
    constexpr int KeyCycle_curveFit = 1;
    constexpr int KeyCycle_framePosition = 2;
    constexpr int KeyCycle_transitionEasing = 3;
    constexpr int KeyCycle_motionProgress = 4;
    constexpr int KeyCycle_waveShape = 5;
    constexpr int KeyCycle_wavePhase = 6;
    constexpr int KeyCycle_wavePeriod = 7;
    constexpr int KeyCycle_waveOffset = 8;
    constexpr int KeyCycle_waveVariesBy = 9;
    constexpr int KeyCycle_transitionPathRotate = 10;
    constexpr int KeyCycle_alpha = 11;
    constexpr int KeyCycle_elevation = 12;
    constexpr int KeyCycle_rotation = 13;
    constexpr int KeyCycle_rotationX = 14;
    constexpr int KeyCycle_rotationY = 15;
    constexpr int KeyCycle_scaleX = 16;
    constexpr int KeyCycle_scaleY = 17;
    constexpr int KeyCycle_translationX = 18;
    constexpr int KeyCycle_translationY = 19;
    constexpr int KeyCycle_translationZ = 20;

    // KeyTimeCycle (21 attrs)
    extern const uint32_t KeyTimeCycle[];
    constexpr int KeyTimeCycle_framePosition = 0;
    constexpr int KeyTimeCycle_motionTarget = 1;
    constexpr int KeyTimeCycle_transitionEasing = 2;
    constexpr int KeyTimeCycle_curveFit = 3;
    constexpr int KeyTimeCycle_waveShape = 4;
    constexpr int KeyTimeCycle_wavePeriod = 5;
    constexpr int KeyTimeCycle_motionProgress = 6;
    constexpr int KeyTimeCycle_waveOffset = 7;
    constexpr int KeyTimeCycle_wavePhase = 8;
    constexpr int KeyTimeCycle_waveDecay = 9;
    constexpr int KeyTimeCycle_alpha = 10;
    constexpr int KeyTimeCycle_elevation = 11;
    constexpr int KeyTimeCycle_rotation = 12;
    constexpr int KeyTimeCycle_rotationX = 13;
    constexpr int KeyTimeCycle_rotationY = 14;
    constexpr int KeyTimeCycle_transitionPathRotate = 15;
    constexpr int KeyTimeCycle_scaleX = 16;
    constexpr int KeyTimeCycle_scaleY = 17;
    constexpr int KeyTimeCycle_translationX = 18;
    constexpr int KeyTimeCycle_translationY = 19;
    constexpr int KeyTimeCycle_translationZ = 20;

    // Motion (10 attrs)
    extern const uint32_t Motion[];
    constexpr int Motion_animateRelativeTo = 0;
    constexpr int Motion_animateCircleAngleTo = 1;
    constexpr int Motion_transitionEasing = 2;
    constexpr int Motion_pathMotionArc = 3;
    constexpr int Motion_motionPathRotate = 4;
    constexpr int Motion_motionStagger = 5;
    constexpr int Motion_drawPath = 6;
    constexpr int Motion_quantizeMotionSteps = 7;
    constexpr int Motion_quantizeMotionPhase = 8;
    constexpr int Motion_quantizeMotionInterpolator = 9;

    // KeyTrigger (13 attrs)
    extern const uint32_t KeyTrigger[];
    constexpr int KeyTrigger_framePosition = 0;
    constexpr int KeyTrigger_motionTarget = 1;
    constexpr int KeyTrigger_triggerReceiver = 2;
    constexpr int KeyTrigger_onNegativeCross = 3;
    constexpr int KeyTrigger_onPositiveCross = 4;
    constexpr int KeyTrigger_onCross = 5;
    constexpr int KeyTrigger_viewTransitionOnNegativeCross = 6;
    constexpr int KeyTrigger_viewTransitionOnPositiveCross = 7;
    constexpr int KeyTrigger_viewTransitionOnCross = 8;
    constexpr int KeyTrigger_triggerSlack = 9;
    constexpr int KeyTrigger_triggerId = 10;
    constexpr int KeyTrigger_motion_postLayoutCollision = 11;
    constexpr int KeyTrigger_motion_triggerOnCollision = 12;

    // ViewTransition (15 attrs)
    extern const uint32_t ViewTransition[];
    constexpr int ViewTransition_id = 0;
    constexpr int ViewTransition_motionTarget = 1;
    constexpr int ViewTransition_viewTransitionMode = 2;
    constexpr int ViewTransition_onStateTransition = 3;
    constexpr int ViewTransition_duration = 4;
    constexpr int ViewTransition_upDuration = 5;
    constexpr int ViewTransition_transitionDisable = 6;
    constexpr int ViewTransition_pathMotionArc = 7;
    constexpr int ViewTransition_motionInterpolator = 8;
    constexpr int ViewTransition_SharedValueId = 9;
    constexpr int ViewTransition_SharedValue = 10;
    constexpr int ViewTransition_setsTag = 11;
    constexpr int ViewTransition_clearsTag = 12;
    constexpr int ViewTransition_ifTagSet = 13;
    constexpr int ViewTransition_ifTagNotSet = 14;

    // MotionEffect (8 attrs)
    extern const uint32_t MotionEffect[];
    constexpr int MotionEffect_motionEffect_start = 0;
    constexpr int MotionEffect_motionEffect_end = 1;
    constexpr int MotionEffect_motionEffect_translationX = 2;
    constexpr int MotionEffect_motionEffect_translationY = 3;
    constexpr int MotionEffect_motionEffect_alpha = 4;
    constexpr int MotionEffect_motionEffect_viewTransition = 5;
    constexpr int MotionEffect_motionEffect_move = 6;
    constexpr int MotionEffect_motionEffect_strict = 7;

    // Placeholder (2 attrs)
    extern const uint32_t Placeholder[];
    constexpr int Placeholder_content = 0;
    constexpr int Placeholder_placeholder_emptyVisibility = 1;

    // Grid (11 attrs)
    extern const uint32_t Grid[];
    constexpr int Grid_grid_rows = 0;
    constexpr int Grid_grid_columns = 1;
    constexpr int Grid_grid_spans = 2;
    constexpr int Grid_grid_skips = 3;
    constexpr int Grid_grid_rowWeights = 4;
    constexpr int Grid_grid_columnWeights = 5;
    constexpr int Grid_grid_orientation = 6;
    constexpr int Grid_grid_horizontalGaps = 7;
    constexpr int Grid_grid_verticalGaps = 8;
    constexpr int Grid_grid_validateInputs = 9;
    constexpr int Grid_grid_useRtl = 10;

    // Carousel (10 attrs)
    extern const uint32_t Carousel[];
    constexpr int Carousel_carousel_firstView = 0;
    constexpr int Carousel_carousel_backwardTransition = 1;
    constexpr int Carousel_carousel_forwardTransition = 2;
    constexpr int Carousel_carousel_previousState = 3;
    constexpr int Carousel_carousel_nextState = 4;
    constexpr int Carousel_carousel_emptyViews_behavior = 5;
    constexpr int Carousel_carousel_touchUp_dampeningFactor = 6;
    constexpr int Carousel_carousel_touchUpMode = 7;
    constexpr int Carousel_carousel_touchUp_velocityThreshold = 8;
    constexpr int Carousel_carousel_infinite = 9;

    // RecyclerView (13 attrs)
    extern const uint32_t RecyclerView[];
    constexpr int RecyclerView_layoutManager = 0;
    constexpr int RecyclerView_orientation = 1;
    constexpr int RecyclerView_descendantFocusability = 2;
    constexpr int RecyclerView_clipToPadding = 3;
    constexpr int RecyclerView_spanCount = 4;
    constexpr int RecyclerView_reverseLayout = 5;
    constexpr int RecyclerView_stackFromEnd = 6;
    constexpr int RecyclerView_fastScrollEnabled = 7;
    constexpr int RecyclerView_fastScrollVerticalThumbDrawable = 8;
    constexpr int RecyclerView_fastScrollVerticalTrackDrawable = 9;
    constexpr int RecyclerView_fastScrollHorizontalThumbDrawable = 10;
    constexpr int RecyclerView_fastScrollHorizontalTrackDrawable = 11;
    constexpr int RecyclerView_isScrollToTopEnabled = 12;

    // TabLayout (28 attrs)
    extern const uint32_t TabLayout[];
    constexpr int TabLayout_tabIndicatorColor = 0;
    constexpr int TabLayout_tabIndicatorHeight = 1;
    constexpr int TabLayout_tabContentStart = 2;
    constexpr int TabLayout_tabBackground = 3;
    constexpr int TabLayout_tabIndicator = 4;
    constexpr int TabLayout_tabIndicatorGravity = 5;
    constexpr int TabLayout_tabIndicatorAnimationDuration = 6;
    constexpr int TabLayout_tabIndicatorFullWidth = 7;
    constexpr int TabLayout_tabIndicatorAnimationMode = 8;
    constexpr int TabLayout_tabMode = 9;
    constexpr int TabLayout_tabGravity = 10;
    constexpr int TabLayout_tabInlineLabel = 11;
    constexpr int TabLayout_tabMinWidth = 12;
    constexpr int TabLayout_tabMaxWidth = 13;
    constexpr int TabLayout_tabTextAppearance = 14;
    constexpr int TabLayout_tabTextColor = 15;
    constexpr int TabLayout_tabSelectedTextColor = 16;
    constexpr int TabLayout_tabSelectedTextAppearance = 17;
    constexpr int TabLayout_tabPaddingStart = 18;
    constexpr int TabLayout_tabPaddingTop = 19;
    constexpr int TabLayout_tabPaddingEnd = 20;
    constexpr int TabLayout_tabPaddingBottom = 21;
    constexpr int TabLayout_tabPadding = 22;
    constexpr int TabLayout_tabIconTint = 23;
    constexpr int TabLayout_tabIconTintMode = 24;
    constexpr int TabLayout_tabRippleColor = 25;
    constexpr int TabLayout_tabUnboundedRipple = 26;
    constexpr int TabLayout_smoothScroll = 27;

    // TabItem (3 attrs)
    extern const uint32_t TabItem[];
    constexpr int TabItem_text = 0;
    constexpr int TabItem_icon = 1;
    constexpr int TabItem_layout = 2;

    // AppBarLayout (1 attrs)
    extern const uint32_t AppBarLayout[];
    constexpr int AppBarLayout_expanded = 0;

    // AppBarLayoutLayout (1 attrs)
    extern const uint32_t AppBarLayoutLayout[];
    constexpr int AppBarLayoutLayout_layout_scrollFlags = 0;

    // CollapsingToolbarLayout (5 attrs)
    extern const uint32_t CollapsingToolbarLayout[];
    constexpr int CollapsingToolbarLayout_titleCollapseMode = 0;
    constexpr int CollapsingToolbarLayout_expandedTitleMargin = 1;
    constexpr int CollapsingToolbarLayout_toolbarId = 2;
    constexpr int CollapsingToolbarLayout_contentScrim = 3;
    constexpr int CollapsingToolbarLayout_statusBarScrim = 4;

    // CollapsingToolbarLayoutLayout (2 attrs)
    extern const uint32_t CollapsingToolbarLayoutLayout[];
    constexpr int CollapsingToolbarLayoutLayout_layout_collapseMode = 0;
    constexpr int CollapsingToolbarLayoutLayout_layout_collapseParallaxMultiplier = 1;

    // QRCodeView (5 attrs)
    extern const uint32_t QRCodeView[];
    constexpr int QRCodeView_eccLevel = 0;
    constexpr int QRCodeView_encodeMode = 1;
    constexpr int QRCodeView_dotColor = 2;
    constexpr int QRCodeView_barBgColor = 3;
    constexpr int QRCodeView_logo = 4;

    // NavigationView (20 attrs)
    extern const uint32_t NavigationView[];
    constexpr int NavigationView_menu = 0;
    constexpr int NavigationView_headerLayout = 1;
    constexpr int NavigationView_itemIconSize = 2;
    constexpr int NavigationView_itemIconTint = 3;
    constexpr int NavigationView_itemTextAppearance = 4;
    constexpr int NavigationView_itemTextColor = 5;
    constexpr int NavigationView_itemBackground = 6;
    constexpr int NavigationView_itemHorizontalPadding = 7;
    constexpr int NavigationView_itemVerticalPadding = 8;
    constexpr int NavigationView_itemIconPadding = 9;
    constexpr int NavigationView_itemMaxLines = 10;
    constexpr int NavigationView_subheaderColor = 11;
    constexpr int NavigationView_subheaderTextAppearance = 12;
    constexpr int NavigationView_subheaderInsetStart = 13;
    constexpr int NavigationView_subheaderInsetEnd = 14;
    constexpr int NavigationView_dividerInsetStart = 15;
    constexpr int NavigationView_dividerInsetEnd = 16;
    constexpr int NavigationView_itemTextAppearanceActiveBoldEnabled = 17;
    constexpr int NavigationView_topInsetScrimEnabled = 18;
    constexpr int NavigationView_bottomInsetScrimEnabled = 19;

    // NavigationBarView (19 attrs)
    extern const uint32_t NavigationBarView[];
    constexpr int NavigationBarView_itemIconTint = 0;
    constexpr int NavigationBarView_itemIconSize = 1;
    constexpr int NavigationBarView_itemTextColor = 2;
    constexpr int NavigationBarView_itemBackground = 3;
    constexpr int NavigationBarView_menu = 4;
    constexpr int NavigationBarView_itemGravity = 5;
    constexpr int NavigationBarView_itemIconGravity = 6;
    constexpr int NavigationBarView_labelVisibilityMode = 7;
    constexpr int NavigationBarView_itemTextAppearanceInactive = 8;
    constexpr int NavigationBarView_itemTextAppearanceActive = 9;
    constexpr int NavigationBarView_horizontalItemTextAppearanceInactive = 10;
    constexpr int NavigationBarView_horizontalItemTextAppearanceActive = 11;
    constexpr int NavigationBarView_itemTextAppearanceActiveBoldEnabled = 12;
    constexpr int NavigationBarView_itemRippleColor = 13;
    constexpr int NavigationBarView_itemPaddingTop = 14;
    constexpr int NavigationBarView_itemPaddingBottom = 15;
    constexpr int NavigationBarView_activeIndicatorLabelPadding = 16;
    constexpr int NavigationBarView_iconLabelHorizontalSpacing = 17;
    constexpr int NavigationBarView_itemActiveIndicatorStyle = 18;

    // BottomNavigationActiveIndicator (4 attrs)
    extern const uint32_t BottomNavigationActiveIndicator[];
    constexpr int BottomNavigationActiveIndicator_width = 0;
    constexpr int BottomNavigationActiveIndicator_height = 1;
    constexpr int BottomNavigationActiveIndicator_marginX = 2;
    constexpr int BottomNavigationActiveIndicator_color = 3;

    // BottomNavigationView (1 attrs)
    extern const uint32_t BottomNavigationView[];
    constexpr int BottomNavigationView_itemHorizontalTranslationEnabled = 0;

    // NavGraph (2 attrs)
    extern const uint32_t NavGraph[];
    constexpr int NavGraph_startDestination = 0;
    constexpr int NavGraph_route = 1;

    // NavDestination (3 attrs)
    extern const uint32_t NavDestination[];
    constexpr int NavDestination_id = 0;
    constexpr int NavDestination_label = 1;
    constexpr int NavDestination_route = 2;

    // NavAction (11 attrs)
    extern const uint32_t NavAction[];
    constexpr int NavAction_id = 0;
    constexpr int NavAction_destination = 1;
    constexpr int NavAction_launchSingleTop = 2;
    constexpr int NavAction_popUpTo = 3;
    constexpr int NavAction_popUpToInclusive = 4;
    constexpr int NavAction_popUpToSaveState = 5;
    constexpr int NavAction_restoreState = 6;
    constexpr int NavAction_enterAnim = 7;
    constexpr int NavAction_exitAnim = 8;
    constexpr int NavAction_popEnterAnim = 9;
    constexpr int NavAction_popExitAnim = 10;

    // NavArgument (4 attrs)
    extern const uint32_t NavArgument[];
    constexpr int NavArgument_name = 0;
    constexpr int NavArgument_defaultValue = 1;
    constexpr int NavArgument_argType = 2;
    constexpr int NavArgument_nullable = 3;

} } } // namespace internal::R::styleable
} // namespace cdroid
#endif // __WIDGETEX_STYLEABLE_H__
