// GENERATED by gen_styleable.py — do not edit by hand.
#include "widgetex_styleable.h"
namespace cdroid {
namespace styleable {
    namespace CoordinatorLayout {
        const uint32_t IDS[] = { fw_attr::CoordinatorLayout::keylines, fw_attr::CoordinatorLayout::statusBarBackground };
    }
    namespace CoordinatorLayoutLayout {
        const uint32_t IDS[] = { fw_attr::CoordinatorLayoutLayout::layout_gravity, fw_attr::CoordinatorLayoutLayout::layout_behavior, fw_attr::CoordinatorLayoutLayout::layout_anchor, fw_attr::CoordinatorLayoutLayout::layout_keyline, fw_attr::CoordinatorLayoutLayout::layout_anchorGravity, fw_attr::CoordinatorLayoutLayout::layout_insetEdge, fw_attr::CoordinatorLayoutLayout::layout_dodgeInsetEdges };
    }
    namespace FlexboxLayout {
        const uint32_t IDS[] = { fw_attr::FlexboxLayout::flexDirection, fw_attr::FlexboxLayout::flexWrap, fw_attr::FlexboxLayout::justifyContent, fw_attr::FlexboxLayout::alignItems, fw_attr::FlexboxLayout::alignContent };
    }
    namespace FlexboxLayoutLayout {
        const uint32_t IDS[] = { fw_attr::FlexboxLayoutLayout::layout_order, fw_attr::FlexboxLayoutLayout::layout_flexBasisPercent, fw_attr::FlexboxLayoutLayout::layout_flexGrow, fw_attr::FlexboxLayoutLayout::layout_flexShrink, fw_attr::FlexboxLayoutLayout::layout_alignSelf, fw_attr::FlexboxLayoutLayout::layout_wrapBefore };
    }
} // namespace styleable
} // namespace cdroid
