// GENERATED by gen_styleable.py — do not edit by hand.
// Source: attrs.xml, attrs.xml, attrs.xml, attrs.xml, attrs.xml  (fw-ids: framework_attrids.txt)
#ifndef __WIDGETEX_STYLEABLE_H__
#define __WIDGETEX_STYLEABLE_H__
#include <cstdint>
#include <cstddef>
namespace cdroid {
namespace internal { namespace R { namespace styleable {
    // CoordinatorLayout (2 attrs)
    extern const uint32_t CoordinatorLayout[];
    constexpr int CoordinatorLayout_keylines = 0;
    constexpr int CoordinatorLayout_statusBarBackground = 1;

    // CoordinatorLayoutLayout (7 attrs)
    extern const uint32_t CoordinatorLayoutLayout[];
    constexpr int CoordinatorLayoutLayout_layout_gravity = 0;
    constexpr int CoordinatorLayoutLayout_layout_behavior = 1;
    constexpr int CoordinatorLayoutLayout_layout_anchor = 2;
    constexpr int CoordinatorLayoutLayout_layout_keyline = 3;
    constexpr int CoordinatorLayoutLayout_layout_anchorGravity = 4;
    constexpr int CoordinatorLayoutLayout_layout_insetEdge = 5;
    constexpr int CoordinatorLayoutLayout_layout_dodgeInsetEdges = 6;

    // FlexboxLayout (12 attrs)
    extern const uint32_t FlexboxLayout[];
    constexpr int FlexboxLayout_flexDirection = 0;
    constexpr int FlexboxLayout_flexWrap = 1;
    constexpr int FlexboxLayout_justifyContent = 2;
    constexpr int FlexboxLayout_alignItems = 3;
    constexpr int FlexboxLayout_alignContent = 4;
    constexpr int FlexboxLayout_dividerDrawable = 5;
    constexpr int FlexboxLayout_dividerDrawableHorizontal = 6;
    constexpr int FlexboxLayout_dividerDrawableVertical = 7;
    constexpr int FlexboxLayout_showDivider = 8;
    constexpr int FlexboxLayout_showDividerHorizontal = 9;
    constexpr int FlexboxLayout_showDividerVertical = 10;
    constexpr int FlexboxLayout_maxLine = 11;

    // FlexboxLayoutLayout (10 attrs)
    extern const uint32_t FlexboxLayoutLayout[];
    constexpr int FlexboxLayoutLayout_layout_order = 0;
    constexpr int FlexboxLayoutLayout_layout_flexGrow = 1;
    constexpr int FlexboxLayoutLayout_layout_flexShrink = 2;
    constexpr int FlexboxLayoutLayout_layout_flexBasisPercent = 3;
    constexpr int FlexboxLayoutLayout_layout_alignSelf = 4;
    constexpr int FlexboxLayoutLayout_layout_minWidth = 5;
    constexpr int FlexboxLayoutLayout_layout_minHeight = 6;
    constexpr int FlexboxLayoutLayout_layout_maxWidth = 7;
    constexpr int FlexboxLayoutLayout_layout_maxHeight = 8;
    constexpr int FlexboxLayoutLayout_layout_wrapBefore = 9;

    // ConstraintLayoutLayout (115 attrs)
    extern const uint32_t ConstraintLayoutLayout[];
    constexpr int ConstraintLayoutLayout_orientation = 0;
    constexpr int ConstraintLayoutLayout_minWidth = 1;
    constexpr int ConstraintLayoutLayout_minHeight = 2;
    constexpr int ConstraintLayoutLayout_maxWidth = 3;
    constexpr int ConstraintLayoutLayout_maxHeight = 4;
    constexpr int ConstraintLayoutLayout_visibility = 5;
    constexpr int ConstraintLayoutLayout_elevation = 6;
    constexpr int ConstraintLayoutLayout_layout_optimizationLevel = 7;
    constexpr int ConstraintLayoutLayout_layoutDescription = 8;
    constexpr int ConstraintLayoutLayout_constraintSet = 9;
    constexpr int ConstraintLayoutLayout_barrierDirection = 10;
    constexpr int ConstraintLayoutLayout_barrierAllowsGoneWidgets = 11;
    constexpr int ConstraintLayoutLayout_barrierMargin = 12;
    constexpr int ConstraintLayoutLayout_constraint_referenced_ids = 13;
    constexpr int ConstraintLayoutLayout_constraint_referenced_tags = 14;
    constexpr int ConstraintLayoutLayout_chainUseRtl = 15;
    constexpr int ConstraintLayoutLayout_flow_horizontalStyle = 16;
    constexpr int ConstraintLayoutLayout_flow_verticalStyle = 17;
    constexpr int ConstraintLayoutLayout_flow_wrapMode = 18;
    constexpr int ConstraintLayoutLayout_flow_maxElementsWrap = 19;
    constexpr int ConstraintLayoutLayout_flow_horizontalGap = 20;
    constexpr int ConstraintLayoutLayout_flow_verticalGap = 21;
    constexpr int ConstraintLayoutLayout_padding = 22;
    constexpr int ConstraintLayoutLayout_paddingTop = 23;
    constexpr int ConstraintLayoutLayout_paddingBottom = 24;
    constexpr int ConstraintLayoutLayout_paddingLeft = 25;
    constexpr int ConstraintLayoutLayout_paddingRight = 26;
    constexpr int ConstraintLayoutLayout_paddingStart = 27;
    constexpr int ConstraintLayoutLayout_paddingEnd = 28;
    constexpr int ConstraintLayoutLayout_flow_verticalAlign = 29;
    constexpr int ConstraintLayoutLayout_flow_horizontalAlign = 30;
    constexpr int ConstraintLayoutLayout_flow_verticalBias = 31;
    constexpr int ConstraintLayoutLayout_flow_horizontalBias = 32;
    constexpr int ConstraintLayoutLayout_flow_firstHorizontalStyle = 33;
    constexpr int ConstraintLayoutLayout_flow_firstVerticalStyle = 34;
    constexpr int ConstraintLayoutLayout_flow_firstHorizontalBias = 35;
    constexpr int ConstraintLayoutLayout_flow_firstVerticalBias = 36;
    constexpr int ConstraintLayoutLayout_flow_lastHorizontalStyle = 37;
    constexpr int ConstraintLayoutLayout_flow_lastVerticalStyle = 38;
    constexpr int ConstraintLayoutLayout_flow_lastHorizontalBias = 39;
    constexpr int ConstraintLayoutLayout_flow_lastVerticalBias = 40;
    constexpr int ConstraintLayoutLayout_circularflow_radiusInDP = 41;
    constexpr int ConstraintLayoutLayout_circularflow_angles = 42;
    constexpr int ConstraintLayoutLayout_circularflow_viewCenter = 43;
    constexpr int ConstraintLayoutLayout_circularflow_defaultRadius = 44;
    constexpr int ConstraintLayoutLayout_circularflow_defaultAngle = 45;
    constexpr int ConstraintLayoutLayout_layout_constraintCircle = 46;
    constexpr int ConstraintLayoutLayout_layout_constraintCircleRadius = 47;
    constexpr int ConstraintLayoutLayout_layout_constraintCircleAngle = 48;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_begin = 49;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_end = 50;
    constexpr int ConstraintLayoutLayout_layout_constraintGuide_percent = 51;
    constexpr int ConstraintLayoutLayout_guidelineUseRtl = 52;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_toLeftOf = 53;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_toRightOf = 54;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_toLeftOf = 55;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_toRightOf = 56;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_toTopOf = 57;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_toBottomOf = 58;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_toTopOf = 59;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_toBottomOf = 60;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toBaselineOf = 61;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toTopOf = 62;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_toBottomOf = 63;
    constexpr int ConstraintLayoutLayout_layout_constraintStart_toEndOf = 64;
    constexpr int ConstraintLayoutLayout_layout_constraintStart_toStartOf = 65;
    constexpr int ConstraintLayoutLayout_layout_constraintEnd_toStartOf = 66;
    constexpr int ConstraintLayoutLayout_layout_constraintEnd_toEndOf = 67;
    constexpr int ConstraintLayoutLayout_layout_goneMarginLeft = 68;
    constexpr int ConstraintLayoutLayout_layout_goneMarginTop = 69;
    constexpr int ConstraintLayoutLayout_layout_goneMarginRight = 70;
    constexpr int ConstraintLayoutLayout_layout_goneMarginBottom = 71;
    constexpr int ConstraintLayoutLayout_layout_goneMarginStart = 72;
    constexpr int ConstraintLayoutLayout_layout_goneMarginEnd = 73;
    constexpr int ConstraintLayoutLayout_layout_goneMarginBaseline = 74;
    constexpr int ConstraintLayoutLayout_layout_marginBaseline = 75;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth = 76;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight = 77;
    constexpr int ConstraintLayoutLayout_layout_width = 78;
    constexpr int ConstraintLayoutLayout_layout_height = 79;
    constexpr int ConstraintLayoutLayout_layout_margin = 80;
    constexpr int ConstraintLayoutLayout_layout_marginHorizontal = 81;
    constexpr int ConstraintLayoutLayout_layout_marginVertical = 82;
    constexpr int ConstraintLayoutLayout_layout_marginLeft = 83;
    constexpr int ConstraintLayoutLayout_layout_marginRight = 84;
    constexpr int ConstraintLayoutLayout_layout_marginTop = 85;
    constexpr int ConstraintLayoutLayout_layout_marginBottom = 86;
    constexpr int ConstraintLayoutLayout_layout_marginStart = 87;
    constexpr int ConstraintLayoutLayout_layout_marginEnd = 88;
    constexpr int ConstraintLayoutLayout_layout_constrainedWidth = 89;
    constexpr int ConstraintLayoutLayout_layout_constrainedHeight = 90;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_bias = 91;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_bias = 92;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_default = 93;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_default = 94;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_min = 95;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_max = 96;
    constexpr int ConstraintLayoutLayout_layout_constraintWidth_percent = 97;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_min = 98;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_max = 99;
    constexpr int ConstraintLayoutLayout_layout_constraintHeight_percent = 100;
    constexpr int ConstraintLayoutLayout_layout_constraintLeft_creator = 101;
    constexpr int ConstraintLayoutLayout_layout_constraintTop_creator = 102;
    constexpr int ConstraintLayoutLayout_layout_constraintRight_creator = 103;
    constexpr int ConstraintLayoutLayout_layout_constraintBottom_creator = 104;
    constexpr int ConstraintLayoutLayout_layout_constraintBaseline_creator = 105;
    constexpr int ConstraintLayoutLayout_layout_constraintDimensionRatio = 106;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_weight = 107;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_weight = 108;
    constexpr int ConstraintLayoutLayout_layout_constraintHorizontal_chainStyle = 109;
    constexpr int ConstraintLayoutLayout_layout_constraintVertical_chainStyle = 110;
    constexpr int ConstraintLayoutLayout_layout_editor_absoluteX = 111;
    constexpr int ConstraintLayoutLayout_layout_editor_absoluteY = 112;
    constexpr int ConstraintLayoutLayout_layout_constraintTag = 113;
    constexpr int ConstraintLayoutLayout_layout_wrapBehaviorInParent = 114;

    // Constraint (124 attrs)
    extern const uint32_t Constraint[];
    constexpr int Constraint_orientation = 0;
    constexpr int Constraint_id = 1;
    constexpr int Constraint_visibility = 2;
    constexpr int Constraint_visibilityMode = 3;
    constexpr int Constraint_alpha = 4;
    constexpr int Constraint_elevation = 5;
    constexpr int Constraint_rotation = 6;
    constexpr int Constraint_rotationX = 7;
    constexpr int Constraint_rotationY = 8;
    constexpr int Constraint_scaleX = 9;
    constexpr int Constraint_scaleY = 10;
    constexpr int Constraint_pivotAnchor = 11;
    constexpr int Constraint_transformPivotX = 12;
    constexpr int Constraint_transformPivotY = 13;
    constexpr int Constraint_transformPivotTarget = 14;
    constexpr int Constraint_translationX = 15;
    constexpr int Constraint_translationY = 16;
    constexpr int Constraint_translationZ = 17;
    constexpr int Constraint_layout_width = 18;
    constexpr int Constraint_layout_height = 19;
    constexpr int Constraint_layout_constraintWidth = 20;
    constexpr int Constraint_layout_constraintHeight = 21;
    constexpr int Constraint_layout_marginStart = 22;
    constexpr int Constraint_layout_marginBottom = 23;
    constexpr int Constraint_layout_marginTop = 24;
    constexpr int Constraint_layout_marginEnd = 25;
    constexpr int Constraint_layout_marginLeft = 26;
    constexpr int Constraint_layout_marginRight = 27;
    constexpr int Constraint_layout_constraintCircle = 28;
    constexpr int Constraint_layout_constraintCircleRadius = 29;
    constexpr int Constraint_layout_constraintCircleAngle = 30;
    constexpr int Constraint_layout_constraintGuide_begin = 31;
    constexpr int Constraint_layout_constraintGuide_end = 32;
    constexpr int Constraint_layout_constraintGuide_percent = 33;
    constexpr int Constraint_guidelineUseRtl = 34;
    constexpr int Constraint_layout_constraintLeft_toLeftOf = 35;
    constexpr int Constraint_layout_constraintLeft_toRightOf = 36;
    constexpr int Constraint_layout_constraintRight_toLeftOf = 37;
    constexpr int Constraint_layout_constraintRight_toRightOf = 38;
    constexpr int Constraint_layout_constraintTop_toTopOf = 39;
    constexpr int Constraint_layout_constraintTop_toBottomOf = 40;
    constexpr int Constraint_layout_constraintBottom_toTopOf = 41;
    constexpr int Constraint_layout_constraintBottom_toBottomOf = 42;
    constexpr int Constraint_layout_constraintBaseline_toBaselineOf = 43;
    constexpr int Constraint_layout_constraintBaseline_toTopOf = 44;
    constexpr int Constraint_layout_constraintBaseline_toBottomOf = 45;
    constexpr int Constraint_layout_constraintStart_toEndOf = 46;
    constexpr int Constraint_layout_constraintStart_toStartOf = 47;
    constexpr int Constraint_layout_constraintEnd_toStartOf = 48;
    constexpr int Constraint_layout_constraintEnd_toEndOf = 49;
    constexpr int Constraint_layout_goneMarginLeft = 50;
    constexpr int Constraint_layout_goneMarginTop = 51;
    constexpr int Constraint_layout_goneMarginRight = 52;
    constexpr int Constraint_layout_goneMarginBottom = 53;
    constexpr int Constraint_layout_goneMarginStart = 54;
    constexpr int Constraint_layout_goneMarginEnd = 55;
    constexpr int Constraint_layout_goneMarginBaseline = 56;
    constexpr int Constraint_layout_marginBaseline = 57;
    constexpr int Constraint_layout_constrainedWidth = 58;
    constexpr int Constraint_layout_constrainedHeight = 59;
    constexpr int Constraint_layout_constraintHorizontal_bias = 60;
    constexpr int Constraint_layout_constraintVertical_bias = 61;
    constexpr int Constraint_layout_constraintWidth_default = 62;
    constexpr int Constraint_layout_constraintHeight_default = 63;
    constexpr int Constraint_layout_constraintWidth_min = 64;
    constexpr int Constraint_layout_constraintWidth_max = 65;
    constexpr int Constraint_layout_constraintWidth_percent = 66;
    constexpr int Constraint_layout_constraintHeight_min = 67;
    constexpr int Constraint_layout_constraintHeight_max = 68;
    constexpr int Constraint_layout_constraintHeight_percent = 69;
    constexpr int Constraint_layout_constraintLeft_creator = 70;
    constexpr int Constraint_layout_constraintTop_creator = 71;
    constexpr int Constraint_layout_constraintRight_creator = 72;
    constexpr int Constraint_layout_constraintBottom_creator = 73;
    constexpr int Constraint_layout_constraintBaseline_creator = 74;
    constexpr int Constraint_layout_constraintDimensionRatio = 75;
    constexpr int Constraint_layout_constraintHorizontal_weight = 76;
    constexpr int Constraint_layout_constraintVertical_weight = 77;
    constexpr int Constraint_layout_constraintHorizontal_chainStyle = 78;
    constexpr int Constraint_layout_constraintVertical_chainStyle = 79;
    constexpr int Constraint_layout_editor_absoluteX = 80;
    constexpr int Constraint_layout_editor_absoluteY = 81;
    constexpr int Constraint_layout_wrapBehaviorInParent = 82;
    constexpr int Constraint_barrierDirection = 83;
    constexpr int Constraint_barrierMargin = 84;
    constexpr int Constraint_constraint_referenced_ids = 85;
    constexpr int Constraint_constraint_referenced_tags = 86;
    constexpr int Constraint_maxHeight = 87;
    constexpr int Constraint_maxWidth = 88;
    constexpr int Constraint_minHeight = 89;
    constexpr int Constraint_minWidth = 90;
    constexpr int Constraint_barrierAllowsGoneWidgets = 91;
    constexpr int Constraint_chainUseRtl = 92;
    constexpr int Constraint_flow_horizontalStyle = 93;
    constexpr int Constraint_flow_verticalStyle = 94;
    constexpr int Constraint_flow_verticalAlign = 95;
    constexpr int Constraint_flow_horizontalAlign = 96;
    constexpr int Constraint_flow_verticalBias = 97;
    constexpr int Constraint_flow_horizontalBias = 98;
    constexpr int Constraint_flow_wrapMode = 99;
    constexpr int Constraint_flow_maxElementsWrap = 100;
    constexpr int Constraint_flow_horizontalGap = 101;
    constexpr int Constraint_flow_verticalGap = 102;
    constexpr int Constraint_flow_firstHorizontalStyle = 103;
    constexpr int Constraint_flow_firstVerticalStyle = 104;
    constexpr int Constraint_flow_firstHorizontalBias = 105;
    constexpr int Constraint_flow_firstVerticalBias = 106;
    constexpr int Constraint_flow_lastHorizontalStyle = 107;
    constexpr int Constraint_flow_lastVerticalStyle = 108;
    constexpr int Constraint_flow_lastHorizontalBias = 109;
    constexpr int Constraint_flow_lastVerticalBias = 110;
    constexpr int Constraint_animateRelativeTo = 111;
    constexpr int Constraint_animateCircleAngleTo = 112;
    constexpr int Constraint_transitionEasing = 113;
    constexpr int Constraint_pathMotionArc = 114;
    constexpr int Constraint_polarRelativeTo = 115;
    constexpr int Constraint_transitionPathRotate = 116;
    constexpr int Constraint_drawPath = 117;
    constexpr int Constraint_motionProgress = 118;
    constexpr int Constraint_layout_constraintTag = 119;
    constexpr int Constraint_motionStagger = 120;
    constexpr int Constraint_quantizeMotionSteps = 121;
    constexpr int Constraint_quantizeMotionPhase = 122;
    constexpr int Constraint_quantizeMotionInterpolator = 123;

    // Transition (11 attrs)
    extern const uint32_t Transition[];
    constexpr int Transition_id = 0;
    constexpr int Transition_constraintSetStart = 1;
    constexpr int Transition_constraintSetEnd = 2;
    constexpr int Transition_transitionDisable = 3;
    constexpr int Transition_layoutDuringTransition = 4;
    constexpr int Transition_pathMotionArc = 5;
    constexpr int Transition_autoTransition = 6;
    constexpr int Transition_motionInterpolator = 7;
    constexpr int Transition_duration = 8;
    constexpr int Transition_staggered = 9;
    constexpr int Transition_transitionFlags = 10;

    // MotionScene (2 attrs)
    extern const uint32_t MotionScene[];
    constexpr int MotionScene_defaultDuration = 0;
    constexpr int MotionScene_layoutDuringTransition = 1;

    // OnSwipe (19 attrs)
    extern const uint32_t OnSwipe[];
    constexpr int OnSwipe_dragScale = 0;
    constexpr int OnSwipe_dragThreshold = 1;
    constexpr int OnSwipe_autoCompleteMode = 2;
    constexpr int OnSwipe_maxVelocity = 3;
    constexpr int OnSwipe_maxAcceleration = 4;
    constexpr int OnSwipe_springMass = 5;
    constexpr int OnSwipe_springStiffness = 6;
    constexpr int OnSwipe_springDamping = 7;
    constexpr int OnSwipe_springStopThreshold = 8;
    constexpr int OnSwipe_springBoundary = 9;
    constexpr int OnSwipe_dragDirection = 10;
    constexpr int OnSwipe_touchAnchorId = 11;
    constexpr int OnSwipe_touchAnchorSide = 12;
    constexpr int OnSwipe_rotationCenterId = 13;
    constexpr int OnSwipe_touchRegionId = 14;
    constexpr int OnSwipe_limitBoundsTo = 15;
    constexpr int OnSwipe_nestedScrollFlags = 16;
    constexpr int OnSwipe_moveWhenScrollAtTop = 17;
    constexpr int OnSwipe_onTouchUp = 18;

    // OnClick (2 attrs)
    extern const uint32_t OnClick[];
    constexpr int OnClick_targetId = 0;
    constexpr int OnClick_clickAction = 1;

    // KeyAttribute (19 attrs)
    extern const uint32_t KeyAttribute[];
    constexpr int KeyAttribute_framePosition = 0;
    constexpr int KeyAttribute_motionTarget = 1;
    constexpr int KeyAttribute_transitionEasing = 2;
    constexpr int KeyAttribute_curveFit = 3;
    constexpr int KeyAttribute_motionProgress = 4;
    constexpr int KeyAttribute_alpha = 5;
    constexpr int KeyAttribute_elevation = 6;
    constexpr int KeyAttribute_rotation = 7;
    constexpr int KeyAttribute_rotationX = 8;
    constexpr int KeyAttribute_rotationY = 9;
    constexpr int KeyAttribute_transformPivotX = 10;
    constexpr int KeyAttribute_transformPivotY = 11;
    constexpr int KeyAttribute_transformPivotTarget = 12;
    constexpr int KeyAttribute_transitionPathRotate = 13;
    constexpr int KeyAttribute_scaleX = 14;
    constexpr int KeyAttribute_scaleY = 15;
    constexpr int KeyAttribute_translationX = 16;
    constexpr int KeyAttribute_translationY = 17;
    constexpr int KeyAttribute_translationZ = 18;

    // KeyPosition (12 attrs)
    extern const uint32_t KeyPosition[];
    constexpr int KeyPosition_keyPositionType = 0;
    constexpr int KeyPosition_percentX = 1;
    constexpr int KeyPosition_percentY = 2;
    constexpr int KeyPosition_percentWidth = 3;
    constexpr int KeyPosition_percentHeight = 4;
    constexpr int KeyPosition_framePosition = 5;
    constexpr int KeyPosition_motionTarget = 6;
    constexpr int KeyPosition_transitionEasing = 7;
    constexpr int KeyPosition_pathMotionArc = 8;
    constexpr int KeyPosition_curveFit = 9;
    constexpr int KeyPosition_drawPath = 10;
    constexpr int KeyPosition_sizePercent = 11;

    // KeyCycle (21 attrs)
    extern const uint32_t KeyCycle[];
    constexpr int KeyCycle_motionTarget = 0;
    constexpr int KeyCycle_curveFit = 1;
    constexpr int KeyCycle_framePosition = 2;
    constexpr int KeyCycle_transitionEasing = 3;
    constexpr int KeyCycle_motionProgress = 4;
    constexpr int KeyCycle_waveShape = 5;
    constexpr int KeyCycle_wavePhase = 6;
    constexpr int KeyCycle_wavePeriod = 7;
    constexpr int KeyCycle_waveOffset = 8;
    constexpr int KeyCycle_waveVariesBy = 9;
    constexpr int KeyCycle_transitionPathRotate = 10;
    constexpr int KeyCycle_alpha = 11;
    constexpr int KeyCycle_elevation = 12;
    constexpr int KeyCycle_rotation = 13;
    constexpr int KeyCycle_rotationX = 14;
    constexpr int KeyCycle_rotationY = 15;
    constexpr int KeyCycle_scaleX = 16;
    constexpr int KeyCycle_scaleY = 17;
    constexpr int KeyCycle_translationX = 18;
    constexpr int KeyCycle_translationY = 19;
    constexpr int KeyCycle_translationZ = 20;

    // KeyTimeCycle (21 attrs)
    extern const uint32_t KeyTimeCycle[];
    constexpr int KeyTimeCycle_framePosition = 0;
    constexpr int KeyTimeCycle_motionTarget = 1;
    constexpr int KeyTimeCycle_transitionEasing = 2;
    constexpr int KeyTimeCycle_curveFit = 3;
    constexpr int KeyTimeCycle_waveShape = 4;
    constexpr int KeyTimeCycle_wavePeriod = 5;
    constexpr int KeyTimeCycle_motionProgress = 6;
    constexpr int KeyTimeCycle_waveOffset = 7;
    constexpr int KeyTimeCycle_wavePhase = 8;
    constexpr int KeyTimeCycle_waveDecay = 9;
    constexpr int KeyTimeCycle_alpha = 10;
    constexpr int KeyTimeCycle_elevation = 11;
    constexpr int KeyTimeCycle_rotation = 12;
    constexpr int KeyTimeCycle_rotationX = 13;
    constexpr int KeyTimeCycle_rotationY = 14;
    constexpr int KeyTimeCycle_transitionPathRotate = 15;
    constexpr int KeyTimeCycle_scaleX = 16;
    constexpr int KeyTimeCycle_scaleY = 17;
    constexpr int KeyTimeCycle_translationX = 18;
    constexpr int KeyTimeCycle_translationY = 19;
    constexpr int KeyTimeCycle_translationZ = 20;

    // Motion (10 attrs)
    extern const uint32_t Motion[];
    constexpr int Motion_animateRelativeTo = 0;
    constexpr int Motion_animateCircleAngleTo = 1;
    constexpr int Motion_transitionEasing = 2;
    constexpr int Motion_pathMotionArc = 3;
    constexpr int Motion_motionPathRotate = 4;
    constexpr int Motion_motionStagger = 5;
    constexpr int Motion_drawPath = 6;
    constexpr int Motion_quantizeMotionSteps = 7;
    constexpr int Motion_quantizeMotionPhase = 8;
    constexpr int Motion_quantizeMotionInterpolator = 9;

    // KeyTrigger (13 attrs)
    extern const uint32_t KeyTrigger[];
    constexpr int KeyTrigger_framePosition = 0;
    constexpr int KeyTrigger_motionTarget = 1;
    constexpr int KeyTrigger_triggerReceiver = 2;
    constexpr int KeyTrigger_onNegativeCross = 3;
    constexpr int KeyTrigger_onPositiveCross = 4;
    constexpr int KeyTrigger_onCross = 5;
    constexpr int KeyTrigger_viewTransitionOnNegativeCross = 6;
    constexpr int KeyTrigger_viewTransitionOnPositiveCross = 7;
    constexpr int KeyTrigger_viewTransitionOnCross = 8;
    constexpr int KeyTrigger_triggerSlack = 9;
    constexpr int KeyTrigger_triggerId = 10;
    constexpr int KeyTrigger_motion_postLayoutCollision = 11;
    constexpr int KeyTrigger_motion_triggerOnCollision = 12;

    // ViewTransition (15 attrs)
    extern const uint32_t ViewTransition[];
    constexpr int ViewTransition_id = 0;
    constexpr int ViewTransition_motionTarget = 1;
    constexpr int ViewTransition_viewTransitionMode = 2;
    constexpr int ViewTransition_onStateTransition = 3;
    constexpr int ViewTransition_duration = 4;
    constexpr int ViewTransition_upDuration = 5;
    constexpr int ViewTransition_transitionDisable = 6;
    constexpr int ViewTransition_pathMotionArc = 7;
    constexpr int ViewTransition_motionInterpolator = 8;
    constexpr int ViewTransition_SharedValueId = 9;
    constexpr int ViewTransition_SharedValue = 10;
    constexpr int ViewTransition_setsTag = 11;
    constexpr int ViewTransition_clearsTag = 12;
    constexpr int ViewTransition_ifTagSet = 13;
    constexpr int ViewTransition_ifTagNotSet = 14;

    // MotionEffect (8 attrs)
    extern const uint32_t MotionEffect[];
    constexpr int MotionEffect_motionEffect_start = 0;
    constexpr int MotionEffect_motionEffect_end = 1;
    constexpr int MotionEffect_motionEffect_translationX = 2;
    constexpr int MotionEffect_motionEffect_translationY = 3;
    constexpr int MotionEffect_motionEffect_alpha = 4;
    constexpr int MotionEffect_motionEffect_viewTransition = 5;
    constexpr int MotionEffect_motionEffect_move = 6;
    constexpr int MotionEffect_motionEffect_strict = 7;

    // Placeholder (2 attrs)
    extern const uint32_t Placeholder[];
    constexpr int Placeholder_content = 0;
    constexpr int Placeholder_placeholder_emptyVisibility = 1;

    // Grid (11 attrs)
    extern const uint32_t Grid[];
    constexpr int Grid_grid_rows = 0;
    constexpr int Grid_grid_columns = 1;
    constexpr int Grid_grid_spans = 2;
    constexpr int Grid_grid_skips = 3;
    constexpr int Grid_grid_rowWeights = 4;
    constexpr int Grid_grid_columnWeights = 5;
    constexpr int Grid_grid_orientation = 6;
    constexpr int Grid_grid_horizontalGaps = 7;
    constexpr int Grid_grid_verticalGaps = 8;
    constexpr int Grid_grid_validateInputs = 9;
    constexpr int Grid_grid_useRtl = 10;

    // Carousel (10 attrs)
    extern const uint32_t Carousel[];
    constexpr int Carousel_carousel_firstView = 0;
    constexpr int Carousel_carousel_backwardTransition = 1;
    constexpr int Carousel_carousel_forwardTransition = 2;
    constexpr int Carousel_carousel_previousState = 3;
    constexpr int Carousel_carousel_nextState = 4;
    constexpr int Carousel_carousel_emptyViews_behavior = 5;
    constexpr int Carousel_carousel_touchUp_dampeningFactor = 6;
    constexpr int Carousel_carousel_touchUpMode = 7;
    constexpr int Carousel_carousel_touchUp_velocityThreshold = 8;
    constexpr int Carousel_carousel_infinite = 9;

    // RecyclerView (13 attrs)
    extern const uint32_t RecyclerView[];
    constexpr int RecyclerView_layoutManager = 0;
    constexpr int RecyclerView_orientation = 1;
    constexpr int RecyclerView_descendantFocusability = 2;
    constexpr int RecyclerView_clipToPadding = 3;
    constexpr int RecyclerView_spanCount = 4;
    constexpr int RecyclerView_reverseLayout = 5;
    constexpr int RecyclerView_stackFromEnd = 6;
    constexpr int RecyclerView_fastScrollEnabled = 7;
    constexpr int RecyclerView_fastScrollVerticalThumbDrawable = 8;
    constexpr int RecyclerView_fastScrollVerticalTrackDrawable = 9;
    constexpr int RecyclerView_fastScrollHorizontalThumbDrawable = 10;
    constexpr int RecyclerView_fastScrollHorizontalTrackDrawable = 11;
    constexpr int RecyclerView_isScrollToTopEnabled = 12;

    // TabLayout (28 attrs)
    extern const uint32_t TabLayout[];
    constexpr int TabLayout_tabIndicatorColor = 0;
    constexpr int TabLayout_tabIndicatorHeight = 1;
    constexpr int TabLayout_tabContentStart = 2;
    constexpr int TabLayout_tabBackground = 3;
    constexpr int TabLayout_tabIndicator = 4;
    constexpr int TabLayout_tabIndicatorGravity = 5;
    constexpr int TabLayout_tabIndicatorAnimationDuration = 6;
    constexpr int TabLayout_tabIndicatorFullWidth = 7;
    constexpr int TabLayout_tabIndicatorAnimationMode = 8;
    constexpr int TabLayout_tabMode = 9;
    constexpr int TabLayout_tabGravity = 10;
    constexpr int TabLayout_tabInlineLabel = 11;
    constexpr int TabLayout_tabMinWidth = 12;
    constexpr int TabLayout_tabMaxWidth = 13;
    constexpr int TabLayout_tabTextAppearance = 14;
    constexpr int TabLayout_tabTextColor = 15;
    constexpr int TabLayout_tabSelectedTextColor = 16;
    constexpr int TabLayout_tabSelectedTextAppearance = 17;
    constexpr int TabLayout_tabPaddingStart = 18;
    constexpr int TabLayout_tabPaddingTop = 19;
    constexpr int TabLayout_tabPaddingEnd = 20;
    constexpr int TabLayout_tabPaddingBottom = 21;
    constexpr int TabLayout_tabPadding = 22;
    constexpr int TabLayout_tabIconTint = 23;
    constexpr int TabLayout_tabIconTintMode = 24;
    constexpr int TabLayout_tabRippleColor = 25;
    constexpr int TabLayout_tabUnboundedRipple = 26;
    constexpr int TabLayout_smoothScroll = 27;

    // TabItem (3 attrs)
    extern const uint32_t TabItem[];
    constexpr int TabItem_text = 0;
    constexpr int TabItem_icon = 1;
    constexpr int TabItem_layout = 2;

} } } // namespace internal::R::styleable
} // namespace cdroid
#endif // __WIDGETEX_STYLEABLE_H__
