SET(DRAWABLE_SOURCES
    drawable/adaptiveicondrawable.cc
    drawable/animatedimagedrawable.cc
    drawable/animatedrotatedrawable.cc
    drawable/animatedstatelistdrawable.cc
    drawable/animatedvectordrawable.cc
    drawable/animationdrawable.cc
    drawable/animationscalelistdrawable.cc
    drawable/bitmapdrawable.cc
    drawable/blur.cc
    drawable/clipdrawable.cc
    drawable/colordrawable.cc
    drawable/colorfilters.cc
    drawable/colormatrix.cc
    drawable/colorstatelist.cc
    drawable/drawable.cc
    drawable/drawablecontainer.cc
    drawable/drawableinflater.cc
    drawable/drawablewrapper.cc
    drawable/gaussianblur.cc
    drawable/gradientdrawable.cc
    drawable/hwpathparser.cc
    drawable/hwvectordrawable.cc
    drawable/hwvectordrawableutils.cc
    drawable/insetdrawable.cc
    drawable/layerdrawable.cc
    drawable/levellistdrawable.cc
    drawable/ninepatch.cc
    drawable/ninepatchrenderer.cc
    drawable/ninepatchdrawable.cc
    drawable/paintdrawable.cc
    drawable/pathparser.cc
    drawable/picturedrawable.cc
    drawable/propertyvaluesanimatorset.cc
    drawable/ripplebackground.cc
    drawable/rippledrawable.cc
    drawable/rippleforeground.cc
    drawable/rotatedrawable.cc
    drawable/scaledrawable.cc
    drawable/shape.cc
    drawable/shapedrawable.cc
    drawable/statelistdrawable.cc
    drawable/stateset.cc
    drawable/transitiondrawable.cc
    drawable/vectordrawable.cc
)
