#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace preferencedemo{

namespace R{
    namespace anim{
        enum : int {
            slide_in_left = 0x7f010000,
            slide_in_right = 0x7f010001,
            slide_out_left = 0x7f010002,
            slide_out_right = 0x7f010003,
        };
    }/*namespace anim*/

    namespace array{
        enum : int {
            prefdemo_assistant_entries = 0x7f020000,
            prefdemo_assistant_values = 0x7f020001,
            prefdemo_browser_entries = 0x7f020002,
            prefdemo_browser_values = 0x7f020003,
            prefdemo_channel_entries = 0x7f020004,
            prefdemo_channel_values = 0x7f020005,
            prefdemo_font_size_entries = 0x7f020006,
            prefdemo_font_size_values = 0x7f020007,
            prefdemo_language_entries = 0x7f020008,
            prefdemo_language_values = 0x7f020009,
            prefdemo_location_mode_entries = 0x7f02000a,
            prefdemo_location_mode_values = 0x7f02000b,
            prefdemo_lock_type_entries = 0x7f02000c,
            prefdemo_lock_type_values = 0x7f02000d,
            prefdemo_lockscreen_entries = 0x7f02000e,
            prefdemo_lockscreen_values = 0x7f02000f,
            prefdemo_ringtone_entries = 0x7f020010,
            prefdemo_ringtone_values = 0x7f020011,
            prefdemo_screen_timeout_entries = 0x7f020012,
            prefdemo_screen_timeout_values = 0x7f020013,
            prefdemo_timezone_entries = 0x7f020014,
            prefdemo_timezone_values = 0x7f020015,
            prefdemo_wifi_sleep_entries = 0x7f020016,
            prefdemo_wifi_sleep_values = 0x7f020017,
        };
    }/*namespace array*/

    namespace drawable{
        enum : int {
            ic_chevron_right = 0x7f030000,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            prefdemo_chevron = 0x7f040000,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            prefdemo_chevron = 0x7f050000,
        };
    }/*namespace layout*/

    namespace xml{
        enum : int {
            settings_about = 0x7f060000,
            settings_accessibility = 0x7f060001,
            settings_apps = 0x7f060002,
            settings_battery = 0x7f060003,
            settings_connected = 0x7f060004,
            settings_display = 0x7f060005,
            settings_location = 0x7f060006,
            settings_network = 0x7f060007,
            settings_notifications = 0x7f060008,
            settings_privacy = 0x7f060009,
            settings_root = 0x7f06000a,
            settings_security = 0x7f06000b,
            settings_sound = 0x7f06000c,
            settings_storage = 0x7f06000d,
            settings_system = 0x7f06000e,
        };
    }/*namespace xml*/

};//endof namespace R

}//endof namespace
