SET(DRAWABLE_SOURCES
    drawables/adaptiveicondrawable.cc
    drawables/animatedimagedrawable.cc
    drawables/animatedrotatedrawable.cc
    drawables/animatedstatelistdrawable.cc
    drawables/animatedvectordrawable.cc
    drawables/animationdrawable.cc
    drawables/animationscalelistdrawable.cc
    drawables/bitmapdrawable.cc
    drawables/blur.cc
    drawables/clipdrawable.cc
    drawables/colordrawable.cc
    drawables/colorfilters.cc
    drawables/colormatrix.cc
    drawables/colorstatelist.cc
    drawables/drawable.cc
    drawables/drawablecontainer.cc
    drawables/drawableinflater.cc
    drawables/drawablewrapper.cc
    drawables/gaussianblur.cc
    drawables/gradientdrawable.cc
    drawables/hwpathparser.cc
    drawables/hwvectordrawable.cc
    drawables/hwvectordrawableutils.cc
    drawables/insetdrawable.cc
    drawables/layerdrawable.cc
    drawables/levellistdrawable.cc
    drawables/ninepatch.cc
    drawables/ninepatchdrawable.cc
    drawables/paintdrawable.cc
    drawables/pathparser.cc
    drawables/picturedrawable.cc
    drawables/propertyvaluesanimatorset.cc
    drawables/ripplebackground.cc
    drawables/rippledrawable.cc
    drawables/rippleforeground.cc
    drawables/rotatedrawable.cc
    drawables/scaledrawable.cc
    drawables/shape.cc
    drawables/shapedrawable.cc
    drawables/statelistdrawable.cc
    drawables/stateset.cc
    drawables/transitiondrawable.cc
    drawables/vectordrawable.cc
)
