#pragma once

/*Generated by aapt2_gen_rh.py, do not edit*/

namespace weardemos{

namespace R{
    namespace color{
        enum : int {
            cpl_black = 0x7f010000,
            cpl_light_blue = 0x7f010001,
            cpl_light_green = 0x7f010002,
            cpl_light_red = 0x7f010003,
            cpl_light_yellow = 0x7f010004,
            rd_background_color = 0x7f010005,
            rd_foreground_color = 0x7f010006,
        };
    }/*namespace color*/

    namespace dimen{
        enum : int {
            rd_image_view_edge = 0x7f020000,
            rd_image_view_half_edge = 0x7f020001,
        };
    }/*namespace dimen*/

    namespace drawable{
        enum : int {
            app_sample_code = 0x7f030000,
            rd_inner_drawable = 0x7f030001,
        };
    }/*namespace drawable*/

    namespace id{
        enum : int {
            action_drawer = 0x7f040000,
            activity_overlay_button = 0x7f040001,
            circularProgressLayout_child = 0x7f040002,
            circularProgressLayout_layout = 0x7f040003,
            content = 0x7f040004,
            fragment_container = 0x7f040005,
            framework_dialog_button = 0x7f040006,
            item_1 = 0x7f040007,
            item_2 = 0x7f040008,
            item_3 = 0x7f040009,
            item_4 = 0x7f04000a,
            linear_layout = 0x7f04000b,
            nav_drawer = 0x7f04000c,
            nested_scroll_view = 0x7f04000d,
            rd_image = 0x7f04000e,
            rv_container = 0x7f04000f,
            v7_dialog_button = 0x7f040010,
            view_overlay_button = 0x7f040011,
            wrv_container = 0x7f040012,
        };
    }/*namespace id*/

    namespace layout{
        enum : int {
            alert_dialog_demo = 0x7f050000,
            confirmation_overlay_demo = 0x7f050001,
            cpl_demo = 0x7f050002,
            nested_sv_demo = 0x7f050003,
            rd_demo = 0x7f050004,
            rv_demo = 0x7f050005,
            switch_demo = 0x7f050006,
            wearable_drawers_demo = 0x7f050007,
            wearable_drawers_frame_layout_demo = 0x7f050008,
            wearable_drawers_scroll_view_demo = 0x7f050009,
            wrv_demo = 0x7f05000a,
        };
    }/*namespace layout*/

    namespace menu{
        enum : int {
            action_drawer_menu = 0x7f060000,
        };
    }/*namespace menu*/

    namespace string{
        enum : int {
            cpl_click_me = 0x7f070000,
            cpl_clicked = 0x7f070001,
            cpl_finished = 0x7f070002,
            lorem_ipsum = 0x7f070003,
        };
    }/*namespace string*/

    namespace style{
        enum : int {
            WearTheme = 0x7f080000,
        };
    }/*namespace style*/

};//endof namespace R

}//endof namespace
