#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# aapt2_gen_rh.py — generate R.h from aapt2 dump resources (arsc real IDs).
#
# Replaces idgen.py's dict2RH: instead of scanning @id/@+id and assigning
# sequential ints (1000+/10000+), this reads the actual resource IDs that aapt2
# baked into the arsc (0x01020000 framework / 0x7f020000 app), so R::id::xxx
# matches what runtime arsc resolution (ResTable::getIdentifier) returns →
# single id source, fixes the idgen-vs-arsc mismatch (LayerDrawable lost layer).
#
# Usage:
#   aapt2_gen_rh.py <apk/pak> --aapt2 <path> --namespace cdroid -o <R.h>
#
# `aapt2 dump resources <apk>` lines look like:
#   " resource 0x01020000 id/background PUBLIC"
# → R::id::background = 0x01020000
# ----------------------------------------------------------------------------
import sys
import os
import re
import argparse
import subprocess

RES_RE = re.compile(r'resource (0x[0-9a-fA-F]{8})\s+(\w+)/(\S+)')

# C++ reserved words. aapt2 dumps the FULL framework arsc, which contains
# resource names that are C++ keywords (e.g. id/auto, id/bool, id/default,
# id/signed, string/delete). Using them verbatim as `constexpr int <name>` is a
# hard compile error, so cident() appends a trailing '_' (idiomatic C++).
CPP_KEYWORDS = {
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor',
    'bool', 'break', 'case', 'catch', 'char', 'char8_t', 'char16_t', 'char32_t',
    'class', 'compl', 'concept', 'const', 'consteval', 'constexpr', 'constinit',
    'const_cast', 'continue', 'co_await', 'co_return', 'co_yield', 'decltype',
    'default', 'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum',
    'explicit', 'export', 'extern', 'false', 'float', 'for', 'friend', 'goto',
    'if', 'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept',
    'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private',
    'protected', 'public', 'register', 'reinterpret_cast', 'requires', 'return',
    'short', 'signed', 'sizeof', 'static', 'static_assert', 'static_cast',
    'struct', 'switch', 'template', 'this', 'thread_local', 'throw', 'true',
    'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'using',
    'virtual', 'void', 'volatile', 'wchar_t', 'while', 'xor', 'xor_eq',
}


def cident(name):
    """resource key -> C++ identifier (illegal chars -> _, leading digit -> _,
    C++ keyword -> trailing '_')."""
    s = re.sub(r'[^0-9A-Za-z_]', '_', name)
    if s and s[0].isdigit():
        s = '_' + s
    if s in CPP_KEYWORDS:
        s = s + '_'
    return s


# Resource TYPE -> C++ namespace name. Android ships a `<bool>` resource type
# (R.bool.*), but `bool` is a C++ keyword so `namespace bool{}` is a hard error.
# Rename it to `boolean` (the only keyword type the framework defines); any other
# keyword type falls back to cident()'s trailing '_'.
TYPE_RENAME = {'bool': 'boolean'}


def ctype(rtype):
    if rtype in TYPE_RENAME:
        return TYPE_RENAME[rtype]
    return cident(rtype)


def main():
    ap = argparse.ArgumentParser(description="Generate R.h from aapt2 dump resources.")
    ap.add_argument('apk', help='apk/pak with resources.arsc (e.g. cdroid.pak / app.apk)')
    ap.add_argument('--aapt2', required=True, help='aapt2 binary path')
    ap.add_argument('--namespace', required=True, help='C++ namespace (cdroid / app name)')
    ap.add_argument('-o', '--output', required=True, help='output R.h path')
    args = ap.parse_args()

    r = subprocess.run([args.aapt2, 'dump', 'resources', args.apk],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write("aapt2 dump failed: %s\n" % r.stderr[:500])
        sys.exit(1)

    by_type = {}  # ctype -> {cident_key: hex_id}
    for line in r.stdout.splitlines():
        m = RES_RE.search(line)
        if m:
            rid, rtype, rkey = m.group(1), m.group(2), m.group(3)
            tns = ctype(rtype)
            ck = cident(rkey)
            d = by_type.setdefault(tns, {})
            if ck in d and d[ck] != rid:
                sys.stderr.write("WARNING: R.h id collision in %s: %s (0x%s vs 0x%s)\n"
                                 % (tns, ck, d[ck], rid))
            d[ck] = rid

    with open(args.output, 'w') as f:
        f.write('#pragma once\n\n/*Generated by aapt2_gen_rh.py, do not edit*/\n\n')
        f.write('namespace %s{\n\n' % args.namespace)
        f.write('namespace R{\n')
        for tns in sorted(by_type):
            # enum : int (not static constexpr int): enumerators are constants,
            # not objects, so they have no address and are never ODR-used -> no
            # linker errors and no need for (int) casts at use sites (C++14 has
            # no inline constexpr). All resource IDs fit in int (0x01../0x7f..).
            f.write('    namespace %s{\n' % tns)
            f.write('        enum : int {\n')
            for key, rid in sorted(by_type[tns].items()):
                f.write('            %s = %s,\n' % (key, rid))
            f.write('        };\n')
            f.write('    }/*namespace %s*/\n\n' % tns)
        f.write('};//endof namespace R\n\n')
        f.write('}//endof namespace\n')
    sys.stderr.write('aapt2_gen_rh: %d types, %d resources -> %s\n'
                     % (len(by_type), sum(len(v) for v in by_type.values()), args.output))


if __name__ == '__main__':
    main()
