#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# aapt2_gen_rh.py — generate R.h from aapt2 dump resources (arsc real IDs).
#
# Replaces idgen.py's dict2RH: reads the actual resource IDs that aapt2 baked
# into the arsc (0x01020000 framework / 0x7f020000 app), so R::id::xxx matches
# what runtime arsc resolution returns.
#
# Flags:
#   --only-public   Output ONLY PUBLIC resources (aapt2 marks them PUBLIC).
#                   Default OFF = output ALL resources (public + private).
#   --internal      Wrap output in <namespace>::internal::R instead of
#                   <namespace>::R. Used for internal_R.h (com.android.internal.R).
#
# Framework (cdroid) build calls this TWICE via pakbuilder:
#   1. --only-public -o R.h           → cdroid::R (public only, android.R equiv)
#   2. --internal -o internal_R.h     → cdroid::internal::R (ALL, internal.R equiv)
#
# App build calls once (no flags):
#   aapt2_gen_rh.py app.apk -o R.h    → app::R (all app resources)
# ----------------------------------------------------------------------------
import sys, os, re, argparse, subprocess

RES_RE = re.compile(r'resource (0x[0-9a-fA-F]{8})\s+([^/\s]+)/(\S+)')

CPP_KEYWORDS = {
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor',
    'bool', 'break', 'case', 'catch', 'char', 'char8_t', 'char16_t', 'char32_t',
    'class', 'compl', 'concept', 'const', 'consteval', 'constexpr', 'constinit',
    'const_cast', 'continue', 'co_await', 'co_return', 'co_yield', 'decltype',
    'default', 'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum',
    'explicit', 'export', 'extern', 'false', 'float', 'for', 'friend', 'goto',
    'if', 'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept',
    'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private',
    'protected', 'public', 'register', 'reinterpret_cast', 'requires', 'return',
    'short', 'signed', 'sizeof', 'static', 'static_assert', 'static_cast',
    'struct', 'switch', 'template', 'this', 'thread_local', 'throw', 'true',
    'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'using',
    'virtual', 'void', 'volatile', 'wchar_t', 'while', 'xor', 'xor_eq',
}

TYPE_RENAME = {'bool': 'boolean'}

def cident(name):
    s = re.sub(r'[^0-9A-Za-z_]', '_', name)
    if s and s[0].isdigit(): s = '_' + s
    if s in CPP_KEYWORDS: s = s + '_'
    return s

def ctype(rtype):
    return TYPE_RENAME.get(rtype, cident(rtype))

def main():
    ap = argparse.ArgumentParser(description="Generate R.h from aapt2 dump resources.")
    ap.add_argument('apk')
    ap.add_argument('--aapt2', required=True)
    ap.add_argument('--namespace', required=True)
    ap.add_argument('-o', '--output', required=True)
    ap.add_argument('--only-public', action='store_true', default=False,
                    help='Output ONLY PUBLIC resources. Default: ALL (public + private).')
    ap.add_argument('--internal', action='store_true', default=False,
                    help='Wrap in <ns>::internal::R instead of <ns>::R.')
    args = ap.parse_args()

    r = subprocess.run([args.aapt2, 'dump', 'resources', args.apk],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write("aapt2 dump failed: %s\n" % r.stderr[:500])
        sys.exit(1)

    by_type = {}  # ctype -> {cident_key: hex_id}
    for line in r.stdout.splitlines():
        m = RES_RE.search(line)
        if not m or '$' in m.group(3):
            continue
        rid, rtype, rkey = m.group(1), m.group(2), m.group(3)
        is_public = ' PUBLIC' in line
        if args.only_public and not is_public:
            continue  # skip private when --only-public
        ck = cident(rkey)
        tns = 'attr' if rtype == '^attr-private' else ctype(rtype)
        by_type.setdefault(tns, {})[ck] = rid

    # Write output
    with open(args.output, 'w') as f:
        f.write('#pragma once\n\n/*Generated by aapt2_gen_rh.py, do not edit*/\n\n')
        f.write('namespace %s{\n\n' % args.namespace)
        if args.internal:
            f.write('namespace internal{\n')
        f.write('namespace R{\n')
        for tns in sorted(by_type):
            f.write('    namespace %s{\n' % tns)
            f.write('        enum : int {\n')
            for key in sorted(by_type[tns]):
                f.write('            %s = %s,\n' % (key, by_type[tns][key]))
            f.write('        };\n')
            f.write('    }/*namespace %s*/\n\n' % tns)
        f.write('};//endof namespace R\n\n')
        if args.internal:
            f.write('}//namespace internal\n')
        f.write('}//endof namespace\n')

    count = sum(len(v) for v in by_type.values())
    scope = 'internal::R' if args.internal else 'R'
    pub = ' (public only)' if args.only_public else ' (ALL)'
    sys.stderr.write('aapt2_gen_rh: %d types/%d resources%s -> %s::%s\n'
                     % (len(by_type), count, pub, args.namespace, scope))

if __name__ == '__main__':
    main()
