#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# aapt2_gen_rh.py — generate R.h from aapt2 dump resources (arsc real IDs).
#
# Replaces idgen.py's dict2RH: instead of scanning @id/@+id and assigning
# sequential ints (1000+/10000+), this reads the actual resource IDs that aapt2
# baked into the arsc (0x01020000 framework / 0x7f020000 app), so R::id::xxx
# matches what runtime arsc resolution (ResTable::getIdentifier) returns →
# single id source, fixes the idgen-vs-arsc mismatch (LayerDrawable lost layer).
#
# Usage:
#   aapt2_gen_rh.py <apk/pak> --aapt2 <path> --namespace cdroid -o <R.h>
#
# `aapt2 dump resources <apk>` lines look like:
#   " resource 0x01020000 id/background PUBLIC"
# → R::id::background = 0x01020000
# ----------------------------------------------------------------------------
import sys
import os
import re
import argparse
import subprocess

RES_RE = re.compile(r'resource (0x[0-9a-fA-F]{8})\s+(\w+)/(\S+)')


def cident(name):
    """resource key -> C++ identifier (illegal chars -> _, leading digit -> _)."""
    s = re.sub(r'[^0-9A-Za-z_]', '_', name)
    if s and s[0].isdigit():
        s = '_' + s
    return s


def main():
    ap = argparse.ArgumentParser(description="Generate R.h from aapt2 dump resources.")
    ap.add_argument('apk', help='apk/pak with resources.arsc (e.g. cdroid.pak / app.apk)')
    ap.add_argument('--aapt2', required=True, help='aapt2 binary path')
    ap.add_argument('--namespace', required=True, help='C++ namespace (cdroid / app name)')
    ap.add_argument('-o', '--output', required=True, help='output R.h path')
    args = ap.parse_args()

    r = subprocess.run([args.aapt2, 'dump', 'resources', args.apk],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write("aapt2 dump failed: %s\n" % r.stderr[:500])
        sys.exit(1)

    by_type = {}  # type -> [(cident_key, hex_id), ...]
    for line in r.stdout.splitlines():
        m = RES_RE.search(line)
        if m:
            rid, rtype, rkey = m.group(1), m.group(2), m.group(3)
            by_type.setdefault(rtype, []).append((cident(rkey), rid))

    with open(args.output, 'w') as f:
        f.write('#pragma once\n\n/*Generated by aapt2_gen_rh.py, do not edit*/\n\n')
        f.write('namespace %s{\n\n' % args.namespace)
        f.write('namespace R{\n')
        for rtype in sorted(by_type):
            f.write('    namespace %s{\n' % rtype)
            for key, rid in by_type[rtype]:
                f.write('         static constexpr int %-32s= %s ;\n' % (key, rid))
            f.write('    }/*namespace %s*/\n\n' % rtype)
        f.write('};//endof namespace R\n\n')
        f.write('}//endof namespace\n')
    sys.stderr.write('aapt2_gen_rh: %d types, %d resources -> %s\n'
                     % (len(by_type), sum(len(v) for v in by_type.values()), args.output))


if __name__ == '__main__':
    main()
