#!/usr/bin/env python3
"""gen_internal_rh.py — generate internal_R.h (unified framework-internal R).

Takes the public R.h (generated by CreatePAK) + framework_styleable.h +
widgetex_styleable.h (generated by gen_styleable.py) and produces internal_R.h:
the full R.h content re-namespaced from cdroid::R to cdroid::internal::R,
with the styleable content appended. Framework .cc files include THIS (not
R.h) so they have a single R for everything (public + private + styleable),
matching AOSP com.android.internal.R.

Usage: python3 gen_internal_rh.py <R.h> <framework_styleable.h> <widgetex_styleable.h> <output>
"""
import sys

def main():
    rh_path, fw_styleable, wx_styleable, out_path = sys.argv[1:5]

    out = []
    out.append('// internal_R.h — unified framework-internal R (ALL resources).')
    out.append('// GENERATED by gen_internal_rh.py from R.h + styleable headers.')
    out.append('// Framework .cc include THIS (not widget/R.h) +')
    out.append('//   `using namespace cdroid::internal;`')
    out.append('// App code uses its own R.h (cdroid::R, public only).')
    out.append('#pragma once')
    out.append('')

    # Read R.h, skip comment header (first 4 lines), re-namespace cdroid::R → cdroid::internal::R
    with open(rh_path) as f:
        rh_lines = f.readlines()

    # Find "namespace cdroid{" and insert "namespace internal{" after it
    # Find the final closing brace and insert internal close before cdroid close
    for i, line in enumerate(rh_lines):
        if line.strip() == 'namespace cdroid{':
            out.append(line.rstrip())
            out.append('namespace internal{')
            continue
        # The R.h closing is typically "}//endof namespace" or "}/*namespace cdroid*/"
        stripped = line.strip()
        if stripped == '}//endof namespace' or stripped == '}/*namespace cdroid*/':
            out.append('}//namespace internal')
            out.append('}//namespace cdroid')
            continue
        # Skip the first 4 comment lines (already added our own header)
        if i < 4 and (line.startswith('/*') or line.startswith('#') or
                       line.startswith('//') or line.strip() == '' or
                       'Generated' in line or 'do not edit' in line):
            continue
        out.append(line.rstrip())

    out.append('')
    out.append('// Framework styleables')
    with open(fw_styleable) as f:
        out.extend(line.rstrip() for line in f)
    out.append('')
    out.append('// WidgetEx styleables')
    with open(wx_styleable) as f:
        out.extend(line.rstrip() for line in f)

    with open(out_path, 'w') as f:
        f.write('\n'.join(out) + '\n')

    print(f'generated {out_path} ({len(out)} lines)')

if __name__ == '__main__':
    main()
