#!/usr/bin/env bash
# Regenerate framework_attrids.txt: the android framework attr name -> resource
# ID map, used by gen_styleable.py to resolve framework (android:) attrs.
#
# Source: aapt2 dump of the BUILT CDROID framework pak (outX64-Debug/cdroid.pak).
# The pak contains BOTH public attrs (attr/NAME, 0x0101xxxx) and private framework
# attrs (^attr-private/NAME, 0x010dxxxx) with the real ids aapt2 baked in. Dumping
# the pak (not android.jar) is the only way to get correct private-attr ids —
# android.jar is public-only, and the ids aapt2 assigns differ from AOSP's
# 0x0112xxxx internal range (the pak is rebuilt fresh by pakbuilder).
#
# Usage: bash scripts/gen_framework_attrids.sh [path/to/cdroid.pak] [outfile]
set -euo pipefail
PAK="${1:-/home/houzh/cdroidMaster/outX64-Debug/cdroid.pak}"
OUT="${2:-scripts/framework_attrids.txt}"
AAPT2="${AAPT2:-$(ls /opt/android-sdk/build-tools/*/aapt2 2>/dev/null | sort -V | tail -1)}"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Public (attr/NAME) and private (^attr-private/NAME) -> "0xID NAME".
"$AAPT2" dump resources "$PAK" \
  | grep -oE 'resource 0x[0-9a-f]+ (\^attr-private|attr)/[A-Za-z0-9_]+' \
  | sed 's#resource ##; s# \^attr-private/# #; s# attr/# #' \
  | sort -u > "$tmp"

{
  echo "# Framework attr name -> resource ID. GENERATED by gen_framework_attrids.sh."
  echo "# Source: aapt2 dump of the built CDROID framework pak ($(basename "$PAK"))."
  echo "# Contains public (attr/NAME, 0x0101xxxx) AND private (^attr-private/NAME,"
  echo "# 0x010dxxxx) attrs with the real ids aapt2 assigned — NOT android.jar"
  echo "# (public-only) and NOT hand-maintained (the old 0x0112xxxx values were wrong)."
  echo "# Format: 0xID NAME   (one per line; # comments allowed)"
  echo ""
  cat "$tmp"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
