#!/usr/bin/env bash
# Regenerate framework_attrids.txt from AOSP public-final.xml + CDROID private-final.xml.
# No android.jar or aapt2 dependency — both are checked-in XML files.
# Usage: bash scripts/gen_framework_attrids.sh [platform-dir] [outfile]
set -euo pipefail
PLATFORM="${1:-/opt/android-sdk/platforms/android-36}"
OUT="${2:-scripts/framework_attrids.txt}"
PUBLIC_FINAL="$PLATFORM/data/res/values/public-final.xml"
PRIVATE_FINAL="${0%/*}/private-final.xml"   # same dir as this script

python3 - "$PUBLIC_FINAL" "$PRIVATE_FINAL" "$OUT" <<'PY'
import sys, xml.etree.ElementTree as ET

pub_src, priv_src, out = sys.argv[1], sys.argv[2], sys.argv[3]

def parse_attr_ids(path):
    """Parse <public type="attr" name="X" id="0x.." /> entries."""
    attrs = []
    for el in ET.parse(path).getroot().findall('.//public'):
        if el.get('type') == 'attr' and el.get('name') and el.get('id'):
            attrs.append((int(el.get('id'), 16), el.get('name')))
    return attrs

public  = parse_attr_ids(pub_src)
private = parse_attr_ids(priv_src)
all_attrs = sorted(public + private)

with open(out, 'w') as f:
    f.write('# Framework attr name -> resource ID. GENERATED by gen_framework_attrids.sh.\n')
    f.write(f'# Public from:  {pub_src}\n')
    f.write(f'# Private from: {priv_src}\n')
    f.write('# Format: 0xID NAME\n\n')
    for idv, name in all_attrs:
        f.write(f'0x{idv:08x} {name}\n')
print(f'wrote {len(all_attrs)} attrs ({len(public)} public + {len(private)} private) to {out}')
PY
