#!/usr/bin/env bash
# Regenerate framework_attrids.txt from AOSP public-final.xml.
# No android.jar or aapt2 dependency — just parse the XML (ET).
# Usage: bash scripts/gen_framework_attrids.sh [platform-dir] [outfile]
set -euo pipefail
PLATFORM="${1:-/opt/android-sdk/platforms/android-36}"
OUT="${2:-scripts/framework_attrids.txt}"
PUBLIC_FINAL="$PLATFORM/data/res/values/public-final.xml"

python3 - "$PUBLIC_FINAL" "$OUT" <<'PY'
import sys, xml.etree.ElementTree as ET
src, out = sys.argv[1], sys.argv[2]
tree = ET.parse(src)
attrs = []
for el in tree.getroot().findall('public'):
    if el.get('type') == 'attr' and el.get('name') and el.get('id'):
        attrs.append((int(el.get('id'), 16), el.get('name')))
attrs.sort()
with open(out, 'w') as f:
    f.write('# Framework attr name -> resource ID. GENERATED by gen_framework_attrids.sh\n')
    f.write(f'# from {src} (AOSP public-final.xml — public attrs only).\n')
    f.write('# No android.jar / aapt2 dependency. Format: 0xID NAME.\n\n')
    for idv, name in attrs:
        f.write(f'0x{idv:08x} {name}\n')
    # Private attrs not in public-final.xml (hand-maintained).
    f.write('\n# --- Private framework attrs (not in public-final.xml) ---\n')
    f.write('0x01120021 calendarViewMode\n')
    f.write('0x01120109 textEditSuggestionContainerLayout\n')
    f.write('0x0112010a textEditSuggestionHighlightStyle\n')
print(f'wrote {len(attrs)} public + 3 private attrs to {out}')
PY
