#!/bin/bash
# Generate an Android-format fonts.xml from the build host's fontconfig.
#
# Desktop runs then follow the product path (curated families + ordered
# fallback) instead of enumerating every installed font at startup. The
# output uses absolute file paths, so it is only valid on the machine that
# built it — regenerate (rerun build.sh) after installing fonts.
#
# Usage: genfontsxml.sh <output-fonts.xml>

set -u
OUT="${1:?usage: genfontsxml.sh <output-fonts.xml>}"

command -v fc-match >/dev/null 2>&1 || { echo "genfontsxml: fc-match not found" >&2; exit 1; }

# Resolve one face: fc-match '<family>:weight=<w>:slant=<s>' -> file path.
# FC_WEIGHT scale: regular=80, bold=200. FC_SLANT: roman=0, italic=100.
match() {  # match <family-pattern> <weight> <slant>
    fc-match -f '%{file}\n' -- "$1:weight=$2:slant=$3" 2>/dev/null | head -n1
}

emit_family() {  # emit_family <name|-> <patterns...> (name '-' => fallback family)
    local name="$1"; shift
    # Query each (weight, slant) variant; dedup by file so a face fc-match
    # substitutes for a missing variant is emitted only once with its true
    # queried style (FC weights 80/200 -> AOSP 400/700).
    local seen="" body=""
    local pats=("$@")
    local pat fcw fcs w st f
    for pat in "${pats[@]}"; do
        while read -r fcw fcs w st; do
            f=$(match "$pat" "$fcw" "$fcs")
            [ -z "$f" ] && continue
            case ";$seen;" in *";$f;"*) continue;; esac
            seen+=";$f"
            body+="        <font weight=\"$w\" style=\"$st\">$f</font>"$'\n'
        done <<'VARIANTS'
80 0 400 normal
200 0 700 normal
80 100 400 italic
200 100 700 italic
VARIANTS
    done
    [ -z "$body" ] && return 0
    if [ "$name" = "-" ]; then
        printf '    <family>\n%s    </family>\n' "$body"
    else
        printf '    <family name="%s">\n%s    </family>\n' "$name" "$body"
    fi
}

{
    echo '<?xml version="1.0" encoding="utf-8"?>'
    echo '<!-- Generated by scripts/genfontsxml.sh from the build host fontconfig.'
    echo '     Absolute paths: valid only on this machine; regenerate after font changes. -->'
    echo '<familyset>'
    emit_family sans-serif 'sans-serif'
    emit_family serif 'serif'
    emit_family monospace 'monospace'
    # Script fallbacks (Android fonts.xml order: CJK, then complex scripts),
    # plus the build host's own locale. Coverage is VERIFIED with
    # 'fc-list :lang=<tag>' — fc-match alone always answers with some
    # best-effort font even when the script is not installed, which would
    # put a non-covering face in the chain.
    LANGS="zh-cn zh-tw ja ko ar he th hi"
    HOSTLANG=$(echo "${LANG%%_*}" | tr 'A-Z' 'a-z')
    case " $LANGS " in *" $HOSTLANG "*) ;; *) [ -n "$HOSTLANG" ] && LANGS="$LANGS $HOSTLANG";; esac
    for lg in $LANGS; do
        f=$(fc-list --format '%{file}\n' ":lang=$lg" 2>/dev/null | head -n1)
        [ -z "$f" ] && continue
        printf '    <family lang="%s">\n        <font weight="400" style="normal">%s</font>\n    </family>\n' "$lg" "$f"
    done
    echo '</familyset>'
} > "$OUT"

COUNT=$(grep -c '<font ' "$OUT" 2>/dev/null || echo 0)
echo "genfontsxml: wrote $OUT ($COUNT faces)"
