#!/usr/bin/env python3
"""Emit an Android-format fonts.xml from a directory of font files.

Usage: genfontsxml_dir.py <fontdir> <output.xml>

Each file is scanned with fc-scan (family/weight/slant). Every FACE becomes
its own <family> — the regular weight keeps the bare family name, other
weights append the weight word ("Family Medium") — because the runtime
registry resolves families by exact name and cannot select a weight inside
a multi-weight family. The first family (tree order) also backs the
sans-serif/serif/monospace aliases: an app's bundled fonts are its whole
font world, matching the legacy FONTCONFIG_FILE confinement. fc weights
(0..210; regular=80, bold=200) map to the AOSP 100..900 scale.
"""
import subprocess, sys, glob, os, re

def fc2aosp(w):
    return int(round((100 + (w / 210.0) * 800) / 100.0)) * 100

# AOSP weight number -> style word for per-weight family names.
WEIGHT_WORDS = {200: 'ExtraLight', 300: 'Light', 400: '', 500: 'Medium',
                600: 'SemiBold', 700: 'Bold', 800: 'ExtraBold', 900: 'Black'}

def family_name(fam, weight):
    word = WEIGHT_WORDS.get(weight, '')
    return fam if not word else '%s %s' % (fam, word)

def main():
    fontdir, out = sys.argv[1], sys.argv[2]
    exts = ('*.ttf', '*.otf', '*.ttc')
    files = sorted(f for e in exts for f in glob.glob(os.path.join(fontdir, e)))
    families = {}   # name -> [(weight, italic, file)] in tree order
    order = []
    for f in files:
        r = subprocess.run(['fc-scan', '--format', '%{family}|%{weight}|%{slant}\\n', f],
                           capture_output=True, text=True)
        for line in r.stdout.splitlines():
            parts = line.split('|')
            if len(parts) != 3 or not parts[0]:
                continue
            fam = parts[0].split(',')[0].strip()
            if not fam:
                continue
            weight = fc2aosp(int(parts[1] or 80))
            # one family per FACE (exact-name lookup at runtime cannot pick
            # a weight inside a merged family)
            fam = family_name(fam, weight)
            if fam not in families:
                families[fam] = []
                order.append(fam)
            families[fam].append((weight, parts[2] != '0', f))
    for fam in families:
        families[fam].sort(key=lambda v: (v[0], v[1]))  # weight asc, normal first
    with open(out, 'w') as w:
        w.write('<?xml version="1.0" encoding="utf-8"?>\n')
        w.write('<!-- Generated by genfontsxml_dir.py from %s -->\n' % fontdir)
        w.write('<familyset>\n')
        for fam in order:
            w.write('    <family name="%s">\n' % fam)
            for weight, italic, f in families[fam]:
                w.write('        <font weight="%d" style="%s">%s</font>\n'
                        % (weight, 'italic' if italic else 'normal', f))
            w.write('    </family>\n')
        if order:
            for alias in ('sans-serif', 'serif', 'monospace'):
                w.write('    <alias name="%s">%s</alias>\n' % (alias, order[0]))
        w.write('</familyset>\n')
    print('genfontsxml: wrote %s (%d faces)' % (out, sum(len(v) for v in families.values())))

if __name__ == '__main__':
    main()
