#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# pakbuilder.py — single-class resource compiler for CreatePAK.
#
# Builds the .pak zip: binary AXML (via aapt2) + resources.arsc + verbatim
# binaries. R.h is generated by aapt2_gen_rh.py (real arsc IDs). idgen (the
# early R.h/ID.xml generator) is retired and removed.
#
# lxml + Pillow are HARD dependencies: 9-patch compile needs PIL and there is no
# correct fallback without it (a .9.png stored without a cdNp chunk is treated
# as a plain bitmap at runtime). Missing either fails loud.
#
# CLI mirrors CreatePAK's 4 args:
#   pakbuilder.py <namespace> <resdir> <pakpath> <rhpath>
# Extra cmake args (e.g. kaidu_ms7's PIXMAN_INCLUDE_DIRS) are ignored.
#
# aapt2 intermediates (res copy, compiled.zip, out.apk/framework.apk) go to a
# deterministic work dir next to the pak — <pak_dir>/<namespace>_pakbuild/ in
# the out tree (e.g. outXXX/apps/aaa/aaa_pakbuild/) — wiped at each real
# rebuild and KEPT afterwards, so intermediates are attributable to the
# subproject and inspectable (no random /tmp mkdtemp names).
#
# --overlay <dir> (repeatable, later wins): AOSP static device-overlay
# semantics applied to the STAGED res copy — values*/ merge per (type,name)
# entry, everything else whole-file by relative path. App-level framework
# overlays build a per-app cdroid.pak next to the app binary (App::findSharedPak
# picks it up before the shared one); CDROID_OVERLAY does the same for the
# shared cdroid.pak. See _apply_overlays.
# ----------------------------------------------------------------------------
import os
import sys
import io
import shutil
import struct
import zlib
import zipfile

try:
    from lxml import etree
    from PIL import Image
except ImportError as e:
    sys.stderr.write("pakbuilder requires lxml and Pillow: %s\n" % e)
    sys.exit(1)

# ----------------------------------------------------------------------------
# 9-patch aapt-style compile (Android aapt2-equivalent, build-time).
#
# A source .9.png carries stretch/padding as the 1px guide border. We scan that
# border for three things — npTc (stretch/padding, big-endian Res_png_9patch),
# npLb (optical/layout-bounds from the red ticks), npOl (outline rect/radius/alpha
# via findMaxOpacity) — bundle all three into ONE custom "cdNp" chunk, STRIP the
# 1px guide border, and splice cdNp into the borderless PNG before IEND. The asset
# is stored as <name>.png (the ".9" is dropped) — aapt-style. The divs/padding/
# optical/outline are content-relative on the bordered source, which after the
# strip equals image-relative on the borderless image, so the same values apply.
# createAsDrawable detects a 9-patch by the cdNp chunk (not the filename).
# cdNp DATA = [u8 version=1][u16 npTcLen BE + bytes][u16 npLbLen BE + bytes]
#             [u16 npOlLen BE + bytes]. Sub-blob byte orders match the C++ side:
# npTc = Res_png_9patch big-endian; npLb/npOl = native little-endian (memcpy).
# The chunk TYPE is "cdNp" (not "cd9p"): PNG chunk-type names must be 4 ASCII
# letters, and byte 2's reserved bit must be 0 (uppercase) — a digit like '9' is
# rejected by libpng with "bad header (invalid type)". c/d=ancillary+private,
# N=reserved-bit-0, p=safe-to-copy.
# ----------------------------------------------------------------------------

def _np_guide(px, x, y):
    """A 9-patch guide pixel is opaque black (0xFF000000)."""
    p = px[x, y]
    return p[3] == 255 and p[0] == 0 and p[1] == 0 and p[2] == 0

def _np_runs(count, is_guide):
    """Return [(start, end), ...] inclusive-start/exclusive-end guide runs over [0,count)."""
    spans, s = [], None
    for i in range(count):
        if is_guide(i):
            if s is None:
                s = i
        elif s is not None:
            spans.append((s, i)); s = None
    if s is not None:
        spans.append((s, count))
    return spans

def _scan_9patch(im):
    """Scan the 1px guide border. Returns content-relative x_divs, y_divs (start/end
    pairs) and padding (left/right/top/bottom). Content = the inner image excluding
    the 1px border, so coords are in [0, W-2]/[0, H-2)."""
    W, H = im.size
    px = im.load()
    cw, ch = W - 2, H - 2
    h_stretch = _np_runs(cw, lambda i: _np_guide(px, i + 1, 0))        # top edge
    v_stretch = _np_runs(ch, lambda i: _np_guide(px, 0, i + 1))        # left edge
    x_divs = [v for s in h_stretch for v in (s[0], s[1])]
    y_divs = [v for s in v_stretch for v in (s[0], s[1])]
    # Padding: bottom edge = horizontal, right edge = vertical. Fall back to the
    # first/last stretch spans when no padding guide is drawn (matches PopulateBounds).
    h_pad = _np_runs(cw, lambda i: _np_guide(px, i + 1, H - 1))        # bottom edge
    if h_pad:
        s, e = h_pad[0]; pad_l, pad_r = s, cw - e
    elif h_stretch:
        pad_l, pad_r = h_stretch[0][0], cw - h_stretch[-1][1]
    else:
        pad_l = pad_r = 0
    v_pad = _np_runs(ch, lambda i: _np_guide(px, W - 1, i + 1))        # right edge
    if v_pad:
        s, e = v_pad[0]; pad_t, pad_b = s, ch - e
    elif v_stretch:
        pad_t, pad_b = v_stretch[0][0], ch - v_stretch[-1][1]
    else:
        pad_t = pad_b = 0
    return x_divs, y_divs, pad_l, pad_r, pad_t, pad_b

def _serialize_nptc(x_divs, y_divs, pad_l, pad_r, pad_t, pad_b):
    """Serialize an npTc chunk DATA block (Res_png_9patch in big-endian file order),
    matching the C++ Res_png_9patch struct layout EXACTLY:
      [0..3]   wasDeserialized/numXDivs/numYDivs/numColors
      [4..7]   xDivsOffset
      [8..11]  yDivsOffset
      [12..27] paddingLeft/Right/Top/Bottom (4 x int32)
      [28..31] colorsOffset
      [32..]   xDivs[], yDivs[]  (colors omitted: numColors=0 — CDROID's renderer
               doesn't consume region_colors, so all-NO_COLOR is fine).
    NOTE: colorsOffset comes AFTER padding (not before) — getting this order wrong
    makes the C++ read paddingLeft as colorsOffset (e.g. 48 for a 22px image)."""
    nx, ny, nc = len(x_divs), len(y_divs), 0
    x_off = 32
    y_off = x_off + nx * 4
    c_off = y_off + ny * 4
    out = struct.pack(">BBBB", 0, nx, ny, nc)                # [0..3] wasDeserialized + counts
    out += struct.pack(">II", x_off, y_off)                  # [4..11] xDivsOffset, yDivsOffset
    out += struct.pack(">iiii", pad_l, pad_r, pad_t, pad_b)  # [12..27] padding
    out += struct.pack(">I", c_off)                          # [28..31] colorsOffset
    for d in x_divs:
        out += struct.pack(">i", d)
    for d in y_divs:
        out += struct.pack(">i", d)
    return out

def _insert_chunk_before_iend(png_bytes, chunk_type, chunk_data):
    """Splice a PNG chunk (length+type+data+CRC) in just before the IEND chunk."""
    crc = zlib.crc32(chunk_type + chunk_data) & 0xffffffff
    chunk = struct.pack(">I", len(chunk_data)) + chunk_type + chunk_data + struct.pack(">I", crc)
    idx = png_bytes.rfind(b"IEND")
    if idx < 4:                       # IEND not found / malformed — leave untouched
        return png_bytes
    return png_bytes[:idx - 4] + chunk + png_bytes[idx - 4:]

# ----------------------------------------------------------------------------
# npLb (optical / layout-bounds) and npOl (outline) — computed on the BORDERED
# source (before the border is stripped), replicating NinePatchRenderer's pixel
# logic so the chunk values match today's runtime. Byte order is native LE
# (matches NinePatch::SerializeLayoutBounds / SerializeRoundedRectOutline, which
# memcpy without swapping; CDROID targets are little-endian).
#
# AUDIT of the referenced C++ (ninepatchrenderer.cc) before porting:
#  - findMaxOpacity (line 236): correct (march, track inset of new opacity max,
#    stop at 0xff). Ported verbatim.
#  - radius via diagonal findMaxOpacity: correct (this is what yields 3/6 today).
#  - outline alpha (line 339-340): BUG in C++ — maxAlphaOverCol is called with
#    endY=innerStartY (should be innerEndY), so the column scan is empty and the
#    column term is always 0; alpha degenerates to row-only. FIXED here: scan the
#    column over [innerStartY, innerEndY) and take max(row, col).
# ----------------------------------------------------------------------------

_TICK_NONE, _TICK_TICK, _TICK_LB = 0, 1, 2
_K_WHITE = 0xffffffff
_K_TICK  = 0xff000000       # opaque black  (stretch/padding guide)
_K_LB    = 0xff0000ff       # opaque red    (layout-bounds / optical guide)

def _tick_type(p, transparent):
    """Classify a guide pixel like ninepatchrenderer.cc tickType. p = (R,G,B,A)."""
    r, g, b, a = p
    color = r | (g << 8) | (b << 16) | (a << 24)
    if transparent:
        if a == 0:            return _TICK_NONE
        if color == _K_LB:    return _TICK_LB
        if color == _K_TICK:  return _TICK_TICK
        return _TICK_TICK
    if color == _K_WHITE:    return _TICK_NONE
    if color == _K_TICK:     return _TICK_TICK
    if color == _K_LB:       return _TICK_LB
    return _TICK_TICK

def _scan_layout_bounds(im):
    """Optical/layout-bounds insets from the bottom-row (L/R) and right-col (T/B) red
    guide ticks. Returns (left, top, right, bottom), content-relative. Usually all-zero."""
    W, H = im.size
    px = im.load()
    transparent = px[0, 0][3] == 0
    left = right = top = bottom = 0
    # horizontal: bottom row (y = H-1), cols 1..W-2
    if _tick_type(px[1, H - 1], transparent) == _TICK_LB:
        i = 1
        while i < W - 1:
            left += 1; i += 1
            if _tick_type(px[i, H - 1], transparent) != _TICK_LB: break
    if _tick_type(px[W - 2, H - 1], transparent) == _TICK_LB:
        i = W - 2
        while i > 1:
            right += 1; i -= 1
            if _tick_type(px[i, H - 1], transparent) != _TICK_LB: break
    # vertical: right col (x = W-1), rows 1..H-2
    if _tick_type(px[W - 1, 1], transparent) == _TICK_LB:
        i = 1
        while i < H - 1:
            top += 1; i += 1
            if _tick_type(px[W - 1, i], transparent) != _TICK_LB: break
    if _tick_type(px[W - 1, H - 2], transparent) == _TICK_LB:
        i = H - 2
        while i > 1:
            bottom += 1; i -= 1
            if _tick_type(px[W - 1, i], transparent) != _TICK_LB: break
    return left, top, right, bottom

def _find_max_opacity(px, startX, startY, endX, endY, dX, dY):
    """Port of findMaxOpacity: march (startX,startY)->(endX,endY) by (dX,dY); return the
    inset (step count) at which opacity last rose to a new max; stop at fully opaque."""
    max_op = 0; out = 0; inset = 0
    x, y = startX, startY
    while x != endX and y != endY:
        op = px[x, y][3]
        if op > max_op:
            max_op = op; out = inset
        if op == 0xff:
            return out
        x += dX; y += dY; inset += 1
    return out

def _compute_outline(im):
    """Replicate NinePatchRenderer's outline computation on the BORDERED source.
    Returns (left, top, right, bottom, radius, alpha) — edge insets + corner radius
    + content max alpha (alpha column-scan FIXED vs the C++ bug)."""
    W, H = im.size
    px = im.load()
    midX, midY = W // 2, H // 2
    endX, endY = W - 2, H - 2
    left = right = top = bottom = 0
    if W > 4:
        left  = _find_max_opacity(px, 1,    midY, midX, -1, 1, 0)
        right = _find_max_opacity(px, endX, midY, midX, -1, -1, 0)
    if H > 4:
        top    = _find_max_opacity(px, midX, 1,    -1, midY, 0, 1)
        bottom = _find_max_opacity(px, midX, endY, -1, midY, 0, -1)
    innerSX = 1 + left
    innerSY = 1 + top
    innerEX = endX - right
    innerEY = endY - bottom
    innerMX = (innerEX + innerSX) // 2
    innerMY = (innerEY + innerSY) // 2
    # alpha: max over the center row AND center column of the outline area.
    alpha = 0
    for x in range(innerSX, innerEX):
        op = px[x, innerMY][3]
        if op > alpha: alpha = op
    for y in range(innerSY, innerEY):           # FIXED: C++ passed innerStartY twice (dead col)
        op = px[innerMX, y][3]
        if op > alpha: alpha = op
    diagonal = _find_max_opacity(px, innerSX, innerSY, innerMX, innerMY, 1, 1)
    radius = int(3.4142 * diagonal)
    return left, top, right, bottom, radius, alpha

def _serialize_nplb(left, top, right, bottom):
    return struct.pack("<iiii", left, top, right, bottom)

def _serialize_outline(left, top, right, bottom, radius, alpha):
    return struct.pack("<iiiifI", left, top, right, bottom, radius, alpha)

def _serialize_cdNp(nptc, nplb, npol):
    """Bundle npTc + npLb + npOl into one "cdNp" chunk DATA blob:
    [u8 version=1] then, for each sub-blob, [u16 BE length][bytes]. Matches the
    C++ NinePatch::Create cdNp parser exactly."""
    out = bytes([1])  # version
    for blob in (nptc, nplb, npol):
        if len(blob) > 0xffff:
            raise ValueError(f"cdNp sub-blob too large ({len(blob)} bytes)")
        out += struct.pack(">H", len(blob)) + blob
    return out


# Binary asset extensions stored verbatim (PNGs are already compressed -> ZIP_STORED).
BIN_EXTS = (".png", ".jpg", ".jpeg", ".gif", ".apng", ".webp", ".ttf", ".otf", ".ttc", ".dat")


class PakBuilder:
    """One-shot resource compiler: builds the .pak zip (binary AXML via aapt2 +
    resources.arsc + verbatim binaries). R.h comes from aapt2_gen_rh (arsc dump),
    not idgen (retired). When aapt2_path + android_jar are provided, layout/drawable
    XML is compiled to binary AXML via aapt2."""

    def __init__(self, namespace, res_dir, pak_path, rh_path,
                 aapt2_path=None, android_jar=None, sdk_res=None, sdk_filter=None,
                 widgetex_apk=None, framework_apk_out=None, overlay_dirs=None):
        self.namespace = namespace
        self.res_dir = res_dir
        self.pak_path = pak_path
        self.rh_path = rh_path
        self.aapt2_path = aapt2_path
        self.android_jar = android_jar
        self.use_aapt2 = bool(aapt2_path and android_jar)
        self.use_sdk = bool(sdk_res and aapt2_path)
        self.sdk_res = sdk_res if self.use_sdk else None
        self.sdk_filter = sdk_filter  # path to JSON with densities/locales whitelist
        # widgetex.apk (fixed-id 0x02 shared lib). When present, app aapt2 link -I's
        # it so widgetEx attrs resolve to 0x02 (matching the runtime styleable)
        # instead of being re-declared at 0x7f in the app's own arsc.
        self.widgetex_apk = widgetex_apk
        # When set (cdroid SDK-mode build), the built framework.apk is ALSO copied
        # here so app paks can aapt2 link -I CDROID's own framework — the public
        # attr table incl. the 0x010d CDROID extensions (pattern/frameDuration/
        # wheelItemCount/...) that a stock android.jar doesn't expose.
        self.framework_apk_out = framework_apk_out
        # Build-time res overlay dirs (AOSP static device-overlay semantics),
        # applied in order onto the staged res copy — a later dir wins. See
        # _apply_overlays for the merge rules.
        self.overlay_dirs = list(overlay_dirs) if overlay_dirs else []

    def _workdir(self):
        """Deterministic aapt2 work dir next to the pak (in the out tree):
        <pak_dir>/<namespace>_pakbuild/ — e.g. outXXX/apps/aaa/aaa_pakbuild/.
        Replaces tempfile.mkdtemp in /tmp: random names there are unattributable
        to a subproject and the dirs are deleted even on failure, so nothing is
        left to inspect. Wiped fresh at each real rebuild (the up-to-date skip
        happens before this), kept after the build for inspection (res copy,
        compiled.zip, out.apk/framework.apk, synthesized manifest)."""
        d = os.path.join(os.path.dirname(os.path.abspath(self.pak_path)),
                         "%s_pakbuild" % self.namespace)
        shutil.rmtree(d, ignore_errors=True)
        os.makedirs(d, exist_ok=True)
        return d

    # ----- XML processing (in-memory strip; no temp dir) -----
    def _strip_xml(self, src):
        parser = etree.XMLParser(remove_comments=True)
        tree = etree.parse(src, parser)
        s = etree.tostring(tree, encoding="UTF-8", xml_declaration=True, pretty_print=False)
        non_blank = [ln for ln in s.decode("utf-8").splitlines() if ln.strip()]
        return "\n".join(non_blank).encode("utf-8")

    # ----- Build-time res overlay (AOSP static device-overlay semantics) -----
    #
    # An overlay dir shadows the STAGED res tree by relative path:
    #   values*/  -> ENTRY-level merge: an overlay entry replaces the base entry
    #                with the same (type, name) anywhere in the SAME qualifier
    #                dir (values/ and values-zh/ never mix); new entries add
    #                resources. Product overlays stay tiny (override one dimen
    #                = a 3-line file) instead of forking whole values files.
    #   anything else (drawable/layout/color/anim/raw/...) -> whole-file
    #                replacement; one file IS one resource there.
    # ID red line: tags that define the ID space are rejected with a warning —
    # overlay may only change values or add non-ID resources, so pinned
    # framework ids never move and app paks keep -I-linking the base
    # framework.apk (identical ids, only default values differ).
    _OVERLAY_FORBIDDEN_TAGS = frozenset((
        "attr", "declare-styleable", "public", "public-final",
        "public-staging", "symbols", "overlayable", "eat-comment"))

    @staticmethod
    def _value_entry_key(el):
        """(type, name) key for a values entry. Type comes from the tag, or
        from the type= attribute for <item> (e.g. <item type="dimen"
        format="float">). None for entries without a name (malformed)."""
        name = el.get("name")
        rtype = el.get("type") if el.tag == "item" else el.tag
        if name is None or rtype is None:
            return None
        return (rtype, name)

    def _apply_overlays(self, staged_res):
        """Apply self.overlay_dirs onto the staged res copy, in order (a later
        dir wins). Runs after the base scrubs, before aapt2 compile. aapt2
        rejects duplicate type+name within one compile unit, so a shadowed base
        entry is REMOVED, not coexisted."""
        if not self.overlay_dirs:
            return
        for odir in self.overlay_dirs:
            if not os.path.isdir(odir):
                raise SystemExit("pakbuilder: overlay dir not found: %s" % odir)
            plain_files, value_files = [], []
            for root, _dirs, files in os.walk(odir):
                for f in files:
                    p = os.path.join(root, f)
                    rel = os.path.relpath(p, odir).replace(os.sep, "/")
                    top = rel.split("/", 1)[0]
                    if top == "values" or top.startswith("values-"):
                        value_files.append((rel, p))
                    else:
                        plain_files.append((rel, p))
            # 1) whole-file shadow outside values dirs
            for rel, p in plain_files:
                dst = os.path.join(staged_res, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(p, dst)
            # 2) entry-level values merge, one qualifier dir at a time
            parser = etree.XMLParser(remove_comments=True)
            by_qual = {}
            for rel, p in value_files:
                by_qual.setdefault(rel.split("/", 1)[0], []).append((rel, p))
            overridden = added = 0
            for qual, ofiles in sorted(by_qual.items()):
                # Parse overlay files; validate entries; reject intra-dir dups.
                ofile_entries = {}  # file rel -> [kept elements]
                okeys = {}          # (type, name) -> file rel (for error text)
                for rel, p in ofiles:
                    root = etree.parse(p, parser).getroot()
                    if root.tag != "resources":
                        raise SystemExit("pakbuilder: overlay %s: root is <%s>, expected <resources>"
                                         % (p, root.tag))
                    kept = []
                    for el in root:
                        if not isinstance(el.tag, str):
                            continue  # comment / processing instruction
                        if el.tag in self._OVERLAY_FORBIDDEN_TAGS:
                            sys.stderr.write("overlay: ignoring forbidden entry <%s name=%r> in %s "
                                             "(ID space is pinned; overlay may only change values)\n"
                                             % (el.tag, el.get("name"), rel))
                            continue
                        key = self._value_entry_key(el)
                        if key is None:
                            raise SystemExit("pakbuilder: overlay entry without name/type in %s: <%s>"
                                             % (rel, el.tag))
                        if key in okeys:
                            raise SystemExit("pakbuilder: overlay defines %s/%s twice (%s and %s)"
                                             % (key[0], key[1], okeys[key], rel))
                        okeys[key] = rel
                        kept.append(el)
                    ofile_entries[rel] = kept
                # Remove shadowed base entries from the staged qualifier dir.
                # Only files we actually touch are rewritten; a file left with
                # no resource children is deleted.
                staged_qual = os.path.join(staged_res, qual)
                hit = set()
                if os.path.isdir(staged_qual):
                    for vf in sorted(os.listdir(staged_qual)):
                        if not vf.endswith(".xml"):
                            continue
                        vpath = os.path.join(staged_qual, vf)
                        try:
                            vtree = etree.parse(vpath)
                        except etree.XMLSyntaxError as e:
                            raise SystemExit("pakbuilder: cannot parse %s: %s" % (vpath, e))
                        vroot = vtree.getroot()
                        changed = False
                        for el in list(vroot):
                            if not isinstance(el.tag, str):
                                continue
                            key = self._value_entry_key(el)
                            if key in okeys:
                                vroot.remove(el)
                                hit.add(key)
                                changed = True
                        if changed:
                            if not [e for e in vroot if isinstance(e.tag, str)]:
                                os.remove(vpath)
                            else:
                                vtree.write(vpath, encoding="UTF-8", xml_declaration=True)
                overridden += len(hit)
                added += len(okeys) - len(hit)
                # Land the overlay entries: append into the staged file of the
                # same rel (base duplicates already removed above), or write a
                # fresh file with only the kept entries.
                for rel, kept in ofile_entries.items():
                    dst = os.path.join(staged_res, rel)
                    if os.path.exists(dst):
                        dtree = etree.parse(dst)
                        for el in kept:
                            dtree.getroot().append(el)
                        dtree.write(dst, encoding="UTF-8", xml_declaration=True)
                    elif kept:
                        nroot = etree.Element("resources")
                        for el in kept:
                            nroot.append(el)
                        etree.ElementTree(nroot).write(dst, encoding="UTF-8",
                                                        xml_declaration=True)
            sys.stderr.write("overlay %s: %d file(s) shadowed, %d values overridden, %d added\n"
                             % (odir, len(plain_files), overridden, added))

    # ----- 9-patch aapt compile: returns borderless+cdNp bytes, or None to store as-is -----
    def _compile_9patch(self, path):
        im = Image.open(path); im.load()
        if im.mode != "RGBA":
            im = im.convert("RGBA")
        W, H = im.size
        if W < 3 or H < 3:
            return None
        xd, yd, pl, pr, pt, pb = _scan_9patch(im)
        cdNp = _serialize_cdNp(
            _serialize_nptc(xd, yd, pl, pr, pt, pb),
            _serialize_nplb(*_scan_layout_bounds(im)),
            _serialize_outline(*_compute_outline(im)))
        # strip the 1px guide border -> inner (W-2)x(H-2), re-encode, splice cdNp
        buf = io.BytesIO()
        im.crop((1, 1, W - 1, H - 1)).save(buf, format="PNG")
        return _insert_chunk_before_iend(buf.getvalue(), b"cdNp", cdNp)

    # ----- Apply density/locale filter to reduce arsc size -----
    def _apply_sdk_filter(self, tmpres):
        """Remove unwanted qualifier directories based on sdk_filter JSON.
        Config format: {"densities": ["hdpi","xhdpi"], "locales": ["zh"]}
        Empty/missing arrays = keep all. Default (no qualifier) always kept.
        nodpi/anydpi are always kept (density-independent fallbacks)."""
        import json, shutil as sh
        if not self.sdk_filter or not os.path.exists(self.sdk_filter):
            return
        with open(self.sdk_filter) as f:
            cfg = json.load(f)
        densities = cfg.get("densities", [])
        locales = cfg.get("locales", [])
        if not densities and not locales:
            return  # keep everything
        # Always keep these (density-independent fallbacks).
        keep_density = set(densities) | {"nodpi", "anydpi"}
        density_quals = {"ldpi","mdpi","hdpi","tvdpi","xhdpi","xxhdpi","xxxhdpi","nodpi","anydpi"}
        removed = 0
        for entry in os.listdir(tmpres):
            epath = os.path.join(tmpres, entry)
            if not os.path.isdir(epath): continue
            parts = entry.split("-", 1)
            if len(parts) < 2: continue  # no qualifier (default) → keep
            base, qual = parts[0], parts[1]
            should_remove = False
            if densities and base in ("drawable", "mipmap"):
                if qual in density_quals and qual not in keep_density:
                    should_remove = True
            if locales and base == "values":
                lang = qual.split("-")[0].split("v")[0]
                if len(lang) <= 3 and lang.isalpha() and lang not in locales:
                    should_remove = True
            if should_remove:
                sh.rmtree(epath)
                removed += 1
        # Clean up symbols.xml: remove declarations for resources that no longer
        # exist (some drawables only had one density variant, now deleted).
        symbols = os.path.join(tmpres, "values", "symbols.xml")
        if removed and os.path.exists(symbols):
            self._clean_symbols(tmpres, symbols)
        if removed:
            sys.stderr.write("SDK filter: removed %d dirs (densities=%s locales=%s)\n"
                             % (removed, densities, locales))

    def _clean_symbols(self, tmpres, symbols_path):
        """Remove <symbol> entries from symbols.xml whose resource files were deleted."""
        import xml.etree.ElementTree as ET
        tree = ET.parse(symbols_path)
        root = tree.getroot()
        removed = 0
        for sym in list(root):
            rtype = sym.get("type", "")
            rname = sym.get("name", "")
            if not rtype or not rname: continue
            # Check if ANY file for this resource still exists.
            found = False
            for entry in os.listdir(tmpres):
                if not entry.startswith(rtype): continue
                candidate = os.path.join(tmpres, entry, rname + ".xml")
                if os.path.exists(candidate): found = True; break
                candidate = os.path.join(tmpres, entry, rname + ".png")
                if os.path.exists(candidate): found = True; break
                candidate = os.path.join(tmpres, entry, rname + ".9.png")
                if os.path.exists(candidate): found = True; break
                candidate = os.path.join(tmpres, entry, rname + ".webp")
                if os.path.exists(candidate): found = True; break
            if not found:
                root.remove(sym)
                removed += 1
        tree.write(symbols_path, encoding="utf-8", xml_declaration=True)
        if removed:
            sys.stderr.write("SDK filter: cleaned %d orphan symbols\n" % removed)

    # ----- SDK framework build: compile SDK data/res/ via aapt2 -x (framework mode) -----
    def _compile_sdk_res(self):
        """Build framework.apk from SDK data/res/ via aapt2 -x. Returns {rel_path: bytes}
        with binary AXML layouts + resources.arsc + drawables (all with 'res/' prefix
        stripped to match pak naming convention)."""
        import subprocess, shutil, json
        tmpdir = self._workdir()   # out tree; kept after the build (inspectable)
        try:
            tmpres = os.path.join(tmpdir, "res")
            shutil.copytree(self.sdk_res, tmpres)
            # build()'s final zip walk reads the staged copy (not the source
            # sdk_res) so overlay changes to text entries (color/*.xml) ship.
            self._sdk_staged_res = tmpres
            # remove symbols.xml / public-staging.xml: these are full-framework symbol
            # tables declaring ids that the slim res subset doesn't define → dangling
            # symbol link errors. framework -x locks IDs via public.xml, not symbols.
            for _sf in ("values/symbols.xml", "values/public-staging.xml"):
                _p = os.path.join(tmpres, _sf)
                if os.path.exists(_p):
                    os.remove(_p)
            # Strip <staging-public-group-final> blocks from public-final.xml: they
            # hold staging-group symbol ranges (0x01fe/0x01ff...) that only newer
            # aapt2 understands — Ubuntu's aapt2 2.19 rejects them as an unknown
            # resource type. They carry no ID pinning (the <public> entries do), so
            # dropping them is safe for the framework -x link.
            import re as _re
            _pf = os.path.join(tmpres, "values", "public-final.xml")
            if os.path.exists(_pf):
                with open(_pf, encoding="utf-8") as _fh:
                    _txt = _fh.read()
                _txt = _re.sub(r'<staging-public-group-final\b.*?</staging-public-group-final>\s*',
                               '', _txt, flags=_re.S)
                with open(_pf, "w", encoding="utf-8") as _fh:
                    _fh.write(_txt)

            # Density/locale trimming via aapt2 -c (config mode). Unlike folder
            # deletion (which left dangling symbol declarations and broke link),
            # -c lets aapt2 drop unused configs itself. Build the config list
            # from sdk_filter.json (default config is always kept implicitly).
            configs = []
            if self.sdk_filter and os.path.exists(self.sdk_filter):
                with open(self.sdk_filter) as fh:
                    cfg = json.load(fh)
                configs = list(cfg.get("locales", [])) + list(cfg.get("densities", []))
            configs = sorted(set(configs) | {"nodpi", "anydpi"})  # always keep fallbacks

            # Fix 1: strip android:featureFlag lines from dimens.xml.
            dimens = os.path.join(tmpres, "values", "dimens.xml")
            if os.path.exists(dimens):
                with open(dimens) as f: lines = f.readlines()
                with open(dimens, "w") as f:
                    f.writelines(l for l in lines if "android:featureFlag" not in l)
            # Fix 2: stub widget radii ONLY if not already defined. SDK data/res
            # needs the stub (Fix1 stripped its featureFlag'd originals); a slim
            # base like src/gui/assets may already define them (would conflict).
            dimens_path = os.path.join(tmpres, "values", "dimens.xml")
            dimens_text = open(dimens_path).read() if os.path.exists(dimens_path) else ""
            if "system_app_widget_background_radius" not in dimens_text:
                with open(os.path.join(tmpres, "values", "_sdk_fixes.xml"), "w") as f:
                    f.write('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
                            '  <dimen name="system_app_widget_background_radius">0dp</dimen>\n'
                            '  <dimen name="system_app_widget_inner_radius">0dp</dimen>\n'
                            '</resources>\n')
                pf = os.path.join(tmpres, "values", "public-final.xml")
                if os.path.exists(pf):
                    with open(pf) as f: lines = f.readlines()
                    with open(pf, "w") as f:
                        f.writelines(l for l in lines
                                     if "system_app_widget_background_radius" not in l
                                     and "system_app_widget_inner_radius" not in l)
            # Overlays land AFTER the scrubs/fixes above: what they change is
            # what aapt2 sees, and they can never reintroduce a scrubbed file
            # (symbols.xml entries are forbidden tags in overlays anyway).
            self._apply_overlays(tmpres)
            # Synthesize manifest (framework: package=android).
            manifest = ('<?xml version="1.0" encoding="utf-8"?>\n'
                        '<manifest xmlns:android="http://schemas.android.com/apk/res/android"'
                        ' package="android">'
                        '<uses-sdk android:minSdkVersion="26" android:targetSdkVersion="36"/>'
                        '</manifest>')
            mpath = os.path.join(tmpdir, "AndroidManifest.xml")
            with open(mpath, "w") as f: f.write(manifest)
            compiled = os.path.join(tmpdir, "compiled.zip")
            out_apk = os.path.join(tmpdir, "framework.apk")
            sys.stderr.write("SDK res: compiling %s via aapt2 -x...\n" % self.sdk_res)
            subprocess.run([self.aapt2_path, "compile", "--dir", tmpres, "-o", compiled],
                           check=True, capture_output=True)
            link_cmd = [self.aapt2_path, "link", "-x", "--manifest", mpath,
                        "-o", out_apk]
            if configs:
                link_cmd += ["-c", ",".join(configs)]
                sys.stderr.write("SDK res: trimming to configs %s\n" % ",".join(configs))
            # --preferred-density strips non-matching density entries (aapt2 keeps
            # the closest match for density-only resources, so no dangling symbols —
            # unlike dir-level deletion which breaks link via public-final.xml).
            # -c does NOT trim density for framework -x; --preferred-density does.
            density_quals = {"ldpi","mdpi","hdpi","tvdpi","xhdpi","xxhdpi","xxxhdpi"}
            pref_dens = next((c for c in configs if c in density_quals), None)
            if pref_dens:
                link_cmd += ["--preferred-density", pref_dens]
                sys.stderr.write("SDK res: preferred density %s (strips others)\n" % pref_dens)
            link_cmd += [compiled]
            _r = subprocess.run(link_cmd, capture_output=True)
            if _r.returncode != 0:
                sys.stderr.write("SDK res link FAILED stderr:\n%s\n" % _r.stderr.decode()[:3000])
                raise subprocess.CalledProcessError(_r.returncode, link_cmd)
            # Extract everything, stripping 'res/' prefix to match pak convention
            # (the legacy string-based resource lookups build no-'res/' names; the
            # arsc↔pak res/ mismatch is papered over at runtime). Aligning res/
            # everywhere requires retiring the string-key system first — see the
            # string-key migration plan (TODO).
            result = {}
            with zipfile.ZipFile(out_apk) as zf:
                for name in zf.namelist():
                    if name.endswith("/"): continue
                    rel = name[4:] if name.startswith("res/") else name
                    result[rel] = zf.read(name)
            sys.stderr.write("SDK res: %d entries (binary AXML + arsc + drawables)\n" % len(result))
            # Persist the framework apk for app -I linking (see __init__).
            if getattr(self, 'framework_apk_out', None):
                shutil.copy(out_apk, self.framework_apk_out)
                sys.stderr.write("framework.apk saved to %s (app -I framework)\n"
                                 % self.framework_apk_out)
            # idgen retirement: R.h from aapt2 dump of framework.apk (real arsc IDs,
            # not idgen sequential ints). aapt2 dump needs the apk (has manifest),
            # NOT cdroid.pak (no manifest → "could not identify format").
            if getattr(self, 'rh_path', None) and self.rh_path:
                _gen = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'aapt2_gen_rh.py')
                _rh_dir = os.path.dirname(os.path.abspath(self.rh_path))
                # Framework: generate TWO R headers (AOSP android.R / internal.R split):
                #   R.h           = public only (cdroid::R)         — app-facing
                #   internal_R.h  = ALL resources (cdroid::internal::R) — framework-internal
                _r1 = subprocess.run([sys.executable, _gen, out_apk,
                                '--aapt2', self.aapt2_path,
                                '--namespace', self.namespace,
                                '-o', self.rh_path,
                                '--only-public', 'true'],
                               capture_output=True, text=True)
                _internal_rh = os.path.join(_rh_dir, 'internal_R.h')
                _r2 = subprocess.run([sys.executable, _gen, out_apk,
                                '--aapt2', self.aapt2_path,
                                '--namespace', self.namespace + '::internal',
                                '-o', _internal_rh],
                               capture_output=True, text=True)
                sys.stderr.write("aapt2_gen_rh R.h: rc=%d %s\n"
                                 % (_r1.returncode, (_r1.stderr or _r1.stdout)[:200]))
                sys.stderr.write("aapt2_gen_rh internal_R.h: rc=%d %s\n"
                                 % (_r2.returncode, (_r2.stderr or _r2.stdout)[:200]))
            return result
        except subprocess.CalledProcessError as e:
            # aapt2's own diagnostics are in e.stderr/e.stdout — surface them
            # instead of the bare "non-zero exit" so link/compile errors (e.g.
            # "attribute xxx not found") are visible.
            err = (e.stderr or b"").decode("utf-8", "replace").strip()
            out = (e.stdout or b"").decode("utf-8", "replace").strip()
            raise SystemExit("pakbuilder: SDK-res aapt2 failed (rc=%d) — refusing to "
                             "fall back (a partial framework pak breaks the runtime "
                             "attr tables).\n%s\n%s" % (e.returncode, err, out))
        except Exception as e:
            raise SystemExit("pakbuilder: SDK-res compile failed — no fallback. %s" % e)
        # No cleanup: the work dir stays in the out tree for inspection.

    # ----- aapt2 compile: compile res/ to binary AXML, return {rel_path: bytes} -----
    def _merge_widgetex_attrs(self, tmpres):
        """Merge each widgetEx component's res/ tree (src/gui/widgetEx/<comp>/res/)
        into the app's temp res/. Every app pak (use_aapt2, not use_sdk) gets
        widgetEx resources this way so ConstraintLayout/Flexbox/TabLayout/...
        app:xxx attrs link and resolve at runtime. widgetEx attrs aren't declared
        in the app's own res, so aapt2 link would fail "attribute not found";
        declaring them fixes link. (Only used when widgetex.apk is NOT -I-linked;
        with -I the attrs resolve from the shared lib instead.) Each component's
        res/values/public.xml pins its attrs at stable 0x02 ids, but for app paks
        that public.xml is irrelevant — the runtime resolves widgetEx attrs via
        widgetex.pak at package-id 0x02.

        Per-component layout: each widgetEx/<comp>/res/ tree is walked; its
        values/* files are copied to tmpres/values/<comp>_<basename> (aapt2 merges
        all values/*.xml by resource name, so renaming avoids clobbering the app's
        own values/attrs.xml/dimens.xml/...). Non-values files keep their relative
        path. A residual shared src/gui/widgetEx/res/ tree (legacy) is merged with
        the 'widgetex' component label if present."""
        sdir = os.path.dirname(os.path.abspath(__file__))
        repo = os.path.dirname(sdir)
        values = os.path.join(tmpres, "values")
        os.makedirs(values, exist_ok=True)
        wroot = os.path.join(repo, "src", "gui", "widgetEx")
        # Collect component res trees: widgetEx/<comp>/res/ (+ legacy widgetEx/res/).
        res_trees = []  # (component_label, tree_path)
        if os.path.isdir(wroot):
            for name in sorted(os.listdir(wroot)):
                comp_res = os.path.join(wroot, name, "res")
                if name != "res" and os.path.isdir(comp_res):
                    res_trees.append((name, comp_res))
            legacy = os.path.join(wroot, "res")
            if os.path.isdir(legacy):
                res_trees.append(("widgetex", legacy))
        # Navigation (androidx.navigation port) lives outside widgetEx/ but its
        # attrs ship in the same 0x02 shared lib so app nav graphs can reference
        # them via the cdroid.widgetex namespace.
        navres = os.path.join(repo, "src", "gui", "navigation", "res")
        if os.path.isdir(navres):
            res_trees.append(("navigation", navres))
        for comp, tree in res_trees:
            for root, dirs, files in os.walk(tree):
                dirs.sort(); files.sort()
                for f in files:
                    src = os.path.join(root, f)
                    rel = os.path.relpath(src, tree).replace(os.sep, "/")
                    head = rel.split("/", 1)
                    if len(head) == 2 and head[0] == "values":
                        # values/<file> -> values/<comp>_<file> (aapt2 merges; no clobber)
                        dst = os.path.join(values, "%s_%s" % (comp, head[1]))
                    else:
                        dst = os.path.join(tmpres, rel)
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.copyfile(src, dst)
        # NOTE: NO public.xml ID pinning for app paks — the widgetEx attr IDs in
        # the app arsc are auto-assigned by aapt2 and UNUSED at runtime (the
        # runtime resolves widgetEx attrs via widgetex.pak at package-id 0x02).
        # The public.xml pinning (0x0201xxxx) is done ONLY in _compile_shared_lib
        # for widgetex.pak. Pinning 0x02 IDs in a 0x7f app pak would fail aapt2.

    _RES_AUTO_URI = "http://schemas.android.com/apk/res-auto"
    _WIDGETEX_URI = "http://schemas.android.com/apk/res/cdroid.widgetex"
    _ANDROID_URI = "http://schemas.android.com/apk/res/android"

    def _widgetex_attr_names(self):
        """All attr names declared by the widgetEx components (values*/attrs*.xml
        under src/gui/widgetEx/<comp>/res/, legacy widgetEx/res/, and
        src/gui/navigation/res/ — the same trees _merge_widgetex_attrs walks)."""
        import xml.etree.ElementTree as ET
        sdir = os.path.dirname(os.path.abspath(__file__))
        wroot = os.path.join(os.path.dirname(sdir), "src", "gui", "widgetEx")
        names = set()
        res_trees = []
        if os.path.isdir(wroot):
            for name in sorted(os.listdir(wroot)):
                comp_res = os.path.join(wroot, name, "res")
                if name != "res" and os.path.isdir(comp_res):
                    res_trees.append(comp_res)
            legacy = os.path.join(wroot, "res")
            if os.path.isdir(legacy):
                res_trees.append(legacy)
        navres = os.path.join(os.path.dirname(sdir), "src", "gui", "navigation", "res")
        if os.path.isdir(navres):
            res_trees.append(navres)
        for tree_path in res_trees:
            for root, dirs, files in os.walk(tree_path):
                dirs.sort(); files.sort()
                if not os.path.basename(root).startswith("values"):
                    continue  # attr names live in values*/attrs*.xml only
                for f in files:
                    if f.startswith("attrs") and f.endswith(".xml"):
                        try:
                            for el in ET.parse(os.path.join(root, f)).getroot().iter():
                                if el.tag.split("}")[-1] == "attr" and el.get("name"):
                                    names.add(el.get("name"))
                        except Exception:
                            pass
        return names

    def _rewrite_res_auto_widgetex_attrs(self, tmpres):
        """In the staged res tree, move attrs bound to ...res-auto whose local
        name is a widgetEx attr onto the cdroid.widgetex namespace so aapt2
        resolves them via -I widgetex.apk (0x02 ids). Source files are never
        touched — only the build's temp copy. Names the app declares in its own
        values/attrs.xml stay on res-auto (app package wins, Android order)."""
        import xml.etree.ElementTree as ET
        ET.register_namespace("android", self._ANDROID_URI)
        ET.register_namespace("app", self._RES_AUTO_URI)
        ET.register_namespace("widgetex", self._WIDGETEX_URI)
        ET.register_namespace("tools", "http://schemas.android.com/tools")
        widgetex_names = self._widgetex_attr_names()
        if not widgetex_names:
            return
        app_names = set()  # attrs the app declares itself — res-auto keeps them
        values_dir = os.path.join(tmpres, "values")
        if os.path.isdir(values_dir):
            for f in sorted(os.listdir(values_dir)):
                if not f.endswith(".xml"):
                    continue
                try:
                    for el in ET.parse(os.path.join(values_dir, f)).getroot().iter():
                        if el.tag.split("}")[-1] == "attr" and el.get("name"):
                            app_names.add(el.get("name"))
                except Exception:
                    pass
        res_auto = "{" + self._RES_AUTO_URI + "}"
        widgetex = "{" + self._WIDGETEX_URI + "}"
        for root, dirs, files in os.walk(tmpres):
            dirs.sort(); files.sort()
            if os.path.relpath(root, tmpres).split(os.sep)[0] == "values":
                continue  # attr names in values files are not namespaced
            for f in files:
                if not f.endswith(".xml") or f == "AndroidManifest.xml":
                    continue
                path = os.path.join(root, f)
                try:
                    tree = ET.parse(path)
                except Exception as e:
                    sys.stderr.write("res-auto rewrite: skip unparseable %s (%s)\n"
                                     % (os.path.relpath(path, tmpres), e))
                    continue
                moved = 0
                for el in tree.getroot().iter():
                    for k in list(el.attrib.keys()):
                        if k.startswith(res_auto):
                            name = k[len(res_auto):]
                            if name in widgetex_names and name not in app_names:
                                el.attrib[widgetex + name] = el.attrib.pop(k)
                                moved += 1
                if moved:
                    tree.write(path, encoding="utf-8", xml_declaration=True)
                    sys.stderr.write("res-auto rewrite: %s: %d widgetEx attrs -> cdroid.widgetex\n"
                                     % (os.path.relpath(path, tmpres), moved))

    def _compile_shared_lib(self):
        """Build widgetex.pak: a fixed-id 0x02 resource pak (widgetEx attrs only).
        Collects the 5 widgetEx res/values/attrs.xml trees + generates public.xml
        at 0x0201xxxx, then aapt2 link --package-id 0x02 --allow-reserved-package-id.
        Output: widgetex.pak (arsc only) + widgetex.apk (kept for app -I linking)."""
        import subprocess, shutil
        tmpdir = self._workdir()   # out tree; kept after the build (inspectable)
        try:
            tmpres = os.path.join(tmpdir, "res")
            os.makedirs(tmpres, exist_ok=True)
            # Collect widgetEx res trees. Each component's res/values/public.xml
            # (src/gui/widgetEx/<comp>/res/values/public.xml — androidx structure) pins
            # that component's attrs at their stable 0x02 ids; _merge_widgetex_attrs copies
            # them into tmpres/values/<comp>_public.xml and aapt2 honors <public id=>.
            self._merge_widgetex_attrs(tmpres)
            # aapt2 compile.
            compiled = os.path.join(tmpdir, "compiled.zip")
            _r = subprocess.run([self.aapt2_path, "compile", "--dir", tmpres, "-o", compiled],
                                capture_output=True)
            if _r.returncode != 0:
                sys.stderr.write("widgetex compile FAILED:\n%s\n" % _r.stderr.decode()[:2000])
                return False
            # Manifest.
            mpath = os.path.join(tmpdir, "AndroidManifest.xml")
            with open(mpath, "w") as fh:
                fh.write('<?xml version="1.0" encoding="utf-8"?>\n'
                         '<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n'
                         '    package="cdroid.widgetex" android:versionCode="1" android:versionName="1.0"/>\n')
            # aapt2 link with fixed package-id 0x02.
            out_apk = os.path.join(tmpdir, "widgetex.apk")
            link_cmd = [self.aapt2_path, "link",
                        "--package-id", "0x02", "--allow-reserved-package-id",
                        "-I", self.android_jar,
                        "--manifest", mpath, "-o", out_apk, compiled]
            _r = subprocess.run(link_cmd, capture_output=True)
            if _r.returncode != 0:
                sys.stderr.write("widgetex link FAILED:\n%s\n" % _r.stderr.decode()[:2000])
                return False
            # Extract resources.arsc → widgetex.pak.
            arsc = None
            with zipfile.ZipFile(out_apk) as zf:
                arsc = zf.read("resources.arsc") if "resources.arsc" in zf.namelist() else None
            with zipfile.ZipFile(self.pak_path, "w") as zf:
                if arsc:
                    zf.writestr("resources.arsc", arsc, zipfile.ZIP_DEFLATED)
            # Keep the intermediate widgetex.apk for app -I linking.
            bin_dir = os.path.dirname(self.pak_path)
            shutil.copyfile(out_apk, os.path.join(bin_dir, "widgetex.apk"))
            sys.stderr.write("widgetex.pak: built (%d bytes arsc)\n" % (len(arsc) if arsc else 0))
            return arsc is not None
        finally:
            pass  # no cleanup: the work dir stays in the out tree for inspection


    def _compile_aapt2(self):
        """Run aapt2 compile+link on res/, return (binary_xmls, arsc) where
        binary_xmls maps relative XML paths (e.g. 'layout/main.xml') to their
        binary AXML bytes, and arsc is the app's resources.arsc bytes (or None
        if aapt2 did not produce one). The arsc lets app @string/@color refs
        resolve alongside the framework arsc (multi-package ResTable)."""
        import subprocess, shutil
        tmpdir = self._workdir()   # out tree; kept after the build (inspectable)
        try:
            # Copy res/ to temp.
            tmpres = os.path.join(tmpdir, "res")
            shutil.copytree(self.res_dir, tmpres)
            # Remove any stale values/ID.xml (checked-in idgen-era artifact in some
            # app assets/ trees); aapt2 rejects its CDROID-specific <id> format.
            _idxml = os.path.join(tmpres, "values", "ID.xml")
            if os.path.exists(_idxml):
                os.remove(_idxml)
            # Same overlay semantics as the framework build, applied to the
            # app's own staged res (rarely used; kept uniform).
            self._apply_overlays(tmpres)
            # widgetEx attrs: when widgetex.apk (the 0x02 shared lib) is linked via
            # -I below, aapt2 resolves them to the stable 0x02 ids directly — so we
            # must NOT also merge the attr declarations into the app res (that would
            # re-declare them at 0x7f and aapt2 would pick the app's copy). Only fall
            # back to merging when the shared lib isn't available.
            if not self.use_sdk and not (self.widgetex_apk and os.path.exists(self.widgetex_apk)):
                self._merge_widgetex_attrs(tmpres)
            else:
                # Android Studio's layout editor always writes
                # xmlns:app="http://schemas.android.com/apk/res-auto"; aapt2
                # resolves res-auto to the app package only (it never searches
                # -I shared libs), so widgetEx attrs under it fail to link.
                # Rewrite the staged copies (sources untouched): attrs under a
                # res-auto binding whose name is a widgetEx attr move to the
                # cdroid.widgetex namespace, which -I widgetex.apk resolves to
                # the stable 0x02 ids the runtime styleable expects.
                self._rewrite_res_auto_widgetex_attrs(tmpres)
            # Manifest: use the app's own assets/AndroidManifest.xml when present
            # (the runtime parses it for the application theme/label, per-activity
            # theme + configChanges, and the MAIN/LAUNCHER window); otherwise
            # synthesize a minimal one. aapt2 rejects a non-dotted package name,
            # so qualify the namespace (e.g. "axmlapp" -> "cdroid.axmlapp").
            pkg = self.namespace if "." in self.namespace else "cdroid." + self.namespace
            app_manifest = os.path.join(self.res_dir, "AndroidManifest.xml")
            mpath = os.path.join(tmpdir, "AndroidManifest.xml")
            if os.path.exists(app_manifest):
                shutil.copyfile(app_manifest, mpath)
            else:
                manifest = ('<?xml version="1.0" encoding="utf-8"?>\n'
                            '<manifest xmlns:android="http://schemas.android.com/apk/res/android"'
                            ' package="%s">'
                            '<uses-sdk android:minSdkVersion="26" android:targetSdkVersion="36"/>'
                            '</manifest>' % pkg)
                with open(mpath, "w") as fh:
                    fh.write(manifest)
            compiled = os.path.join(tmpdir, "compiled.zip")
            out_apk = os.path.join(tmpdir, "out.apk")
            subprocess.run([self.aapt2_path, "compile", "--dir", tmpres, "-o", compiled],
                           check=True, capture_output=True)
            link_cmd = [self.aapt2_path, "link", "-I", self.android_jar]
            # -I the widgetex 0x02 shared lib so widgetEx attrs resolve to the ids
            # the runtime styleable expects. Layouts reference them via the
            # xmlns:app=".../apk/res/cdroid.widgetex" namespace (res-auto does NOT
            # reach -I packages).
            if self.widgetex_apk and os.path.exists(self.widgetex_apk):
                link_cmd += ["-I", self.widgetex_apk]
            link_cmd += ["--manifest", mpath, "-o", out_apk, compiled]
            subprocess.run(link_cmd, check=True, capture_output=True)
            # Extract binary XML (res/layout/*.xml) + the app's resources.arsc.
            result = {}
            arsc = None
            manifest_bin = None
            with zipfile.ZipFile(out_apk) as zf:
                for name in zf.namelist():
                    if name == "resources.arsc":
                        arsc = zf.read(name)
                    elif name == "AndroidManifest.xml":
                        # Compiled binary manifest — stored in the pak next to the
                        # arsc; the runtime parses it at boot (the PackageManager
                        # role: application/activity theme, configChanges, MAIN).
                        manifest_bin = zf.read(name)
                    elif name.startswith("res/") and name.endswith(".xml"):
                        rel = name[4:]  # strip "res/" prefix -> layout/main.xml
                        result[rel] = zf.read(name)
            # Write app R.h from the app's own arsc (real 0x7f IDs), mirroring
            # _compile_sdk_res. Skip when use_sdk: cdroid's framework R.h is
            # already written by _compile_sdk_res from the full framework apk,
            # and writing here would clobber it with cdroid's slim-subset arsc.
            if (arsc is not None and not self.use_sdk
                    and getattr(self, 'rh_path', None) and self.rh_path):
                _gen = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'aapt2_gen_rh.py')
                _scripts = os.path.dirname(os.path.abspath(_gen))
                # When the app declares its own attrs (values/attrs.xml), also emit
                # R::styleable from them: app attrs resolve from the app arsc dump,
                # android:-prefixed attrs from the framework id maps.
                _cmd = [sys.executable, _gen, out_apk,
                        '--aapt2', self.aapt2_path,
                        '--namespace', self.namespace, '-o', self.rh_path]
                _app_attrs = os.path.join(self.res_dir, 'values', 'attrs.xml')
                if os.path.exists(_app_attrs):
                    _cmd += ['--attrs', _app_attrs,
                             '--fw-ids', os.path.join(_scripts, 'framework_attrids.txt')]
                _r = subprocess.run(_cmd, capture_output=True, text=True)
                sys.stderr.write("aapt2_gen_rh (app): rc=%d %s\n"
                                 % (_r.returncode, (_r.stderr or _r.stdout)[:200]))
            self._app_manifest_bin = manifest_bin
            return result, arsc
        except subprocess.CalledProcessError as e:
            # Surface aapt2's own stderr/stdout (attribute-not-found, etc.) so
            # the actual link/compile error is visible, not just "non-zero exit".
            # NO text-XML fallback: a pak without an arsc resolves no ids at
            # runtime (every inflate of a compiled layout dies far from the
            # cause). Fail the build here instead — the resource error itself
            # is the actionable message.
            err = (e.stderr or b"").decode("utf-8", "replace").strip()
            out = (e.stdout or b"").decode("utf-8", "replace").strip()
            raise SystemExit("pakbuilder: aapt2 failed (rc=%d) — refusing to emit a "
                             "text-XML pak (no arsc => no ids at runtime).\n%s\n%s"
                             % (e.returncode, err, out))
        except Exception as e:
            raise SystemExit("pakbuilder: aapt2 compile failed — refusing to emit a "
                             "text-XML pak (no arsc => no ids at runtime). %s" % e)
        # No cleanup: the work dir stays in the out tree for inspection.

    # ----- packaging: one walk, XML deflated / binaries stored -----
    def build(self):
        # Skip rebuild if pak exists and is newer than all inputs.
        if os.path.exists(self.pak_path):
            pak_mtime = os.path.getmtime(self.pak_path)
            newest = 0
            for root, dirs, files in os.walk(self.res_dir):
                for f in files:
                    m = os.path.getmtime(os.path.join(root, f))
                    if m > newest: newest = m
            # SDK res dir: scan recursively — a directory-level mtime only
            # changes on add/remove in the TOP dir, so in-place content updates
            # (a refreshed slim-framework base on another machine) silently kept
            # a STALE framework arsc and the attr-id tables drifted against it.
            # ~5k stats is tens of milliseconds; correctness is worth it.
            if self.sdk_res and os.path.isdir(self.sdk_res):
                for root, dirs, files in os.walk(self.sdk_res):
                    for f in files:
                        m = os.path.getmtime(os.path.join(root, f))
                        if m > newest: newest = m
            # Overlay dirs are build inputs too — without this an edited overlay
            # would keep producing a stale pak (same class of bug as above).
            for odir in (self.overlay_dirs or []):
                if os.path.isdir(odir):
                    for root, dirs, files in os.walk(odir):
                        for f in files:
                            m = os.path.getmtime(os.path.join(root, f))
                            if m > newest: newest = m
            # Also require R.h present: it is produced during a real rebuild, so
            # a missing/stale R.h must not be skipped (else builds with no R.h).
            if pak_mtime > newest and os.path.exists(self.rh_path):
                sys.stderr.write("pak up to date, skipping rebuild\n")
                return
        # widgetex shared-lib mode: build widgetex.pak (fixed-id 0x02, attrs only).
        if self.namespace == "widgetex":
            if not self.use_aapt2:
                sys.exit("widgetex.pak requires aapt2 + android.jar")
            if self.overlay_dirs:
                sys.exit("widgetex.pak (attrs-only shared lib) does not support --overlay")
            self._compile_shared_lib()
            return
        # SDK mode: build complete framework from SDK data/res/ via aapt2 -x.
        sdk_data = self._compile_sdk_res() if self.use_sdk else {}
        # App mode: compile the app's own res/ via aapt2 (optional).
        # Skip when use_sdk: cdroid.pak's res_dir IS the framework res
        # (src/gui/res, carrying public-final.xml 0x01 IDs), already built as
        # framework -x by _compile_sdk_res. Running app-mode link on it collides
        # (framework package-1 IDs vs app 0x7f space → "can't assign ID
        # 0x010a0004 ... package already has ID 1"). _compile_aapt2 is for real
        # app paks only (use_aapt2 and not use_sdk).
        binary_xmls, app_arsc = self._compile_aapt2() if (self.use_aapt2 and not self.use_sdk) else ({}, None)
        binary_ok = bool(sdk_data) or (app_arsc is not None)
        with zipfile.ZipFile(self.pak_path, "w") as zf:
            # SDK framework: store binary AXML + arsc + drawables. Skip values/
            # and color/ here — cdroid ships its own TEXT versions of those
            # (loadKeyValues needs text; binary selectors can't be parsed as
            # text). Writing both would create duplicate entries that corrupt
            # libzip's local-header offsets and break reading of large entries
            # such as the 47MB resources.arsc.
            for rel, data in sorted(sdk_data.items()):
                if rel.startswith("values/") or rel.startswith("color/"):
                    continue
                zf.writestr(rel, data, zipfile.ZIP_DEFLATED)
            # App's own resources.arsc (multi-package: resolved by Assets
            # alongside the framework arsc; lets app @string/@color refs work).
            if app_arsc:
                zf.writestr("resources.arsc", app_arsc, zipfile.ZIP_DEFLATED)
            _manifest_bin = getattr(self, '_app_manifest_bin', None)
            if _manifest_bin:
                zf.writestr("AndroidManifest.xml", _manifest_bin, zipfile.ZIP_DEFLATED)
            # Walk the res tree for files NOT already provided by SDK. In SDK
            # mode walk the STAGED copy (= sdk_res + scrubs + overlay) so text
            # entries (color/*.xml) reflect the overlay; without one the output
            # is identical (staging is a copytree of the same tree, and the
            # scrubs only touch values/, which is skipped below).
            walk_dir = self.res_dir
            if self.use_sdk and getattr(self, "_sdk_staged_res", None):
                walk_dir = self._sdk_staged_res
            for root, dirs, files in os.walk(walk_dir):
                dirs.sort(); files.sort()
                for f in files:
                    p = os.path.join(root, f)
                    rel = os.path.relpath(p, walk_dir).replace(os.sep, "/")
                    # binary apps/framework: values/ (dimen/string/style/attrs/...)
                    # resolve from arsc (string/color/dimen getters + style bag +
                    # locale setParameters). Skip the text copies — also avoids text
                    # parse bugs (e.g. values-ko XmlPullParser multi-byte error).
                    # color/ ColorStateLists stay text (parsed by loadKeyValues).
                    if rel == "AndroidManifest.xml":
                        # The compiled binary manifest is written separately
                        # (from the aapt2 link output); skip the text source.
                        continue
                    if binary_ok and (rel.startswith("values/") or rel.startswith("values-")):
                        continue
                    if self.use_sdk and rel in sdk_data:
                        # SDK binary replaces layout/drawable (inflation targets).
                        # But keep cdroid's own values/color text — loadKeyValues
                        # needs them (binary selectors can't be parsed as text).
                        if not (rel.startswith("values/") or rel.startswith("color/")):
                            continue
                    if f.endswith(".xml"):
                        if rel in binary_xmls:
                            zf.writestr(rel, binary_xmls[rel], zipfile.ZIP_DEFLATED)
                        else:
                            # cdroid's values/*.xml kept as text (SDK provides
                            # layouts/drawables as binary, but NOT values/ files).
                            zf.writestr(rel, self._strip_xml(p), zipfile.ZIP_DEFLATED)
                    elif f.endswith(".9.png"):               # MUST precede the .png branch
                        arc = rel[:-6] + ".png"              # foo.9.png -> foo.png
                        try:
                            data = self._compile_9patch(p)
                            zf.writestr(arc, data if data else open(p, "rb").read(),
                                        zipfile.ZIP_STORED)
                        except Exception as e:
                            sys.stderr.write("9patch embed failed for %s: %s; storing as-is\n" % (p, e))
                            zf.writestr(arc, open(p, "rb").read(), zipfile.ZIP_STORED)
                    elif f.endswith(BIN_EXTS):
                        zf.writestr(rel, open(p, "rb").read(), zipfile.ZIP_STORED)
                    # other extensions skipped


if __name__ == "__main__":
    if len(sys.argv) < 5:
        sys.exit("Usage: pakbuilder.py <namespace> <resdir> <pakpath> <rhpath> [aapt2] [android.jar] [sdk_res] [filter.json] [--widgetex-apk <apk>] [--framework-apk-out <apk>] [--overlay <dir>]...")
    # Pull --widgetex-apk / --framework-apk-out <path> out of argv first: they are
    # flags so they never collide with the positional sdk_res/filter slots.
    args = sys.argv[1:]
    wxapk = None
    if "--widgetex-apk" in args:
        i = args.index("--widgetex-apk")
        wxapk = args[i + 1] if i + 1 < len(args) else None
        args = args[:i] + args[i + 2:]
    fwout = None
    if "--framework-apk-out" in args:
        i = args.index("--framework-apk-out")
        fwout = args[i + 1] if i + 1 < len(args) else None
        args = args[:i] + args[i + 2:]
    # --overlay <dir> may repeat; applied in order, later dirs win.
    overlays = []
    while "--overlay" in args:
        i = args.index("--overlay")
        if i + 1 >= len(args):
            sys.exit("--overlay requires a directory argument")
        overlays.append(args[i + 1])
        args = args[:i] + args[i + 2:]
    aapt2 = args[4] if len(args) > 4 else None
    ajar  = args[5] if len(args) > 5 else None
    sres  = args[6] if len(args) > 6 else None
    sflt  = args[7] if len(args) > 7 else None
    pb = PakBuilder(*args[0:4], aapt2_path=aapt2, android_jar=ajar, sdk_res=sres,
                    sdk_filter=sflt, widgetex_apk=wxapk, framework_apk_out=fwout,
                    overlay_dirs=overlays)
    pb.build()
