// GENERATED by gen_styleable.py — do not edit by hand.
#include "framework_styleable.h"
namespace cdroid {
namespace styleable {
    namespace AbsListView {
        const uint32_t IDS[] = {
            fw_attr::AbsListView::listSelector, fw_attr::AbsListView::drawSelectorOnTop,
            fw_attr::AbsListView::stackFromBottom, fw_attr::AbsListView::scrollingCache,
            fw_attr::AbsListView::textFilterEnabled, fw_attr::AbsListView::transcriptMode,
            fw_attr::AbsListView::cacheColorHint, fw_attr::AbsListView::fastScrollEnabled,
            fw_attr::AbsListView::fastScrollStyle, fw_attr::AbsListView::smoothScrollbar,
            fw_attr::AbsListView::choiceMode, fw_attr::AbsListView::fastScrollAlwaysVisible, 0 };
    }
    namespace AdapterViewAnimator {
        const uint32_t IDS[] = {
            fw_attr::AdapterViewAnimator::inAnimation, fw_attr::AdapterViewAnimator::outAnimation,
            fw_attr::AdapterViewAnimator::loopViews, fw_attr::AdapterViewAnimator::animateFirstView,
            0 };
    }
    namespace AdapterViewFlipper {
        const uint32_t IDS[] = { fw_attr::AdapterViewFlipper::flipInterval, fw_attr::AdapterViewFlipper::autoStart, 0 };
    }
    namespace AnalogClock {
        const uint32_t IDS[] = {
            fw_attr::AnalogClock::dial, fw_attr::AnalogClock::hand_hour,
            fw_attr::AnalogClock::hand_minute, fw_attr::AnalogClock::hand_second,
            fw_attr::AnalogClock::timeZone, fw_attr::AnalogClock::dialTint,
            fw_attr::AnalogClock::dialTintMode, fw_attr::AnalogClock::hand_hourTint,
            fw_attr::AnalogClock::hand_hourTintMode, fw_attr::AnalogClock::hand_minuteTint,
            fw_attr::AnalogClock::hand_minuteTintMode, fw_attr::AnalogClock::hand_secondTint,
            fw_attr::AnalogClock::hand_secondTintMode, 0 };
    }
    namespace CheckedTextView {
        const uint32_t IDS[] = {
            fw_attr::CheckedTextView::checked, fw_attr::CheckedTextView::checkMark,
            fw_attr::CheckedTextView::checkMarkTint, fw_attr::CheckedTextView::checkMarkTintMode, 0 };
    }
    namespace Chronometer {
        const uint32_t IDS[] = { fw_attr::Chronometer::format, fw_attr::Chronometer::countDown, 0 };
    }
    namespace CompoundButton {
        const uint32_t IDS[] = {
            fw_attr::CompoundButton::checked, fw_attr::CompoundButton::button,
            fw_attr::CompoundButton::buttonTint, fw_attr::CompoundButton::buttonTintMode, 0 };
    }
    namespace FrameLayout {
        const uint32_t IDS[] = { fw_attr::FrameLayout::measureAllChildren, 0 };
    }
    namespace GridLayout {
        const uint32_t IDS[] = {
            fw_attr::GridLayout::orientation, fw_attr::GridLayout::rowCount,
            fw_attr::GridLayout::columnCount, fw_attr::GridLayout::useDefaultMargins,
            fw_attr::GridLayout::alignmentMode, fw_attr::GridLayout::rowOrderPreserved,
            fw_attr::GridLayout::columnOrderPreserved, 0 };
    }
    namespace GridLayoutLayout {
        const uint32_t IDS[] = {
            fw_attr::GridLayoutLayout::layout_row, fw_attr::GridLayoutLayout::layout_rowSpan,
            fw_attr::GridLayoutLayout::layout_rowWeight, fw_attr::GridLayoutLayout::layout_column,
            fw_attr::GridLayoutLayout::layout_columnSpan,
            fw_attr::GridLayoutLayout::layout_columnWeight,
            fw_attr::GridLayoutLayout::layout_gravity, 0 };
    }
    namespace GridView {
        const uint32_t IDS[] = {
            fw_attr::GridView::horizontalSpacing, fw_attr::GridView::verticalSpacing,
            fw_attr::GridView::stretchMode, fw_attr::GridView::columnWidth,
            fw_attr::GridView::numColumns, fw_attr::GridView::gravity, 0 };
    }
    namespace ImageView {
        const uint32_t IDS[] = {
            fw_attr::ImageView::src, fw_attr::ImageView::scaleType,
            fw_attr::ImageView::adjustViewBounds, fw_attr::ImageView::maxWidth,
            fw_attr::ImageView::maxHeight, fw_attr::ImageView::tint,
            fw_attr::ImageView::baselineAlignBottom, fw_attr::ImageView::cropToPadding,
            fw_attr::ImageView::baseline, fw_attr::ImageView::tintMode, 0 };
    }
    namespace KeyboardView {
        const uint32_t IDS[] = {
            fw_attr::KeyboardView::keyBackground, fw_attr::KeyboardView::keyTextSize,
            fw_attr::KeyboardView::labelTextSize, fw_attr::KeyboardView::keyTextColor,
            fw_attr::KeyboardView::keyPreviewLayout, fw_attr::KeyboardView::keyPreviewOffset,
            fw_attr::KeyboardView::keyPreviewHeight, fw_attr::KeyboardView::verticalCorrection,
            fw_attr::KeyboardView::popupLayout, fw_attr::KeyboardView::shadowColor,
            fw_attr::KeyboardView::shadowRadius, 0 };
    }
    namespace Layout {
        const uint32_t IDS[] = { fw_attr::Layout::layout_width, fw_attr::Layout::layout_height, 0 };
    }
    namespace LinearLayout {
        const uint32_t IDS[] = {
            fw_attr::LinearLayout::orientation, fw_attr::LinearLayout::gravity,
            fw_attr::LinearLayout::baselineAligned, fw_attr::LinearLayout::baselineAlignedChildIndex,
            fw_attr::LinearLayout::weightSum, fw_attr::LinearLayout::measureWithLargestChild,
            fw_attr::LinearLayout::divider, fw_attr::LinearLayout::showDividers,
            fw_attr::LinearLayout::dividerPadding, 0 };
    }
    namespace LinearLayoutLayout {
        const uint32_t IDS[] = {
            fw_attr::LinearLayoutLayout::layout_width, fw_attr::LinearLayoutLayout::layout_height,
            fw_attr::LinearLayoutLayout::layout_weight, fw_attr::LinearLayoutLayout::layout_gravity,
            0 };
    }
    namespace ListView {
        const uint32_t IDS[] = {
            fw_attr::ListView::entries, fw_attr::ListView::divider, fw_attr::ListView::dividerHeight,
            fw_attr::ListView::headerDividersEnabled, fw_attr::ListView::footerDividersEnabled,
            fw_attr::ListView::overScrollHeader, fw_attr::ListView::overScrollFooter, 0 };
    }
    namespace MarginLayout {
        const uint32_t IDS[] = {
            fw_attr::MarginLayout::layout_width, fw_attr::MarginLayout::layout_height,
            fw_attr::MarginLayout::layout_margin, fw_attr::MarginLayout::layout_marginLeft,
            fw_attr::MarginLayout::layout_marginTop, fw_attr::MarginLayout::layout_marginRight,
            fw_attr::MarginLayout::layout_marginBottom, fw_attr::MarginLayout::layout_marginStart,
            fw_attr::MarginLayout::layout_marginEnd, fw_attr::MarginLayout::layout_marginHorizontal,
            fw_attr::MarginLayout::layout_marginVertical, 0 };
    }
    namespace NumberPicker {
        const uint32_t IDS[] = {
            fw_attr::NumberPicker::solidColor, fw_attr::NumberPicker::selectionDividerHeight,
            fw_attr::NumberPicker::min, fw_attr::NumberPicker::max, fw_attr::NumberPicker::value,
            fw_attr::NumberPicker::textColor, fw_attr::NumberPicker::textSize,
            fw_attr::NumberPicker::fontFamily, fw_attr::NumberPicker::itemBackground, 0 };
    }
    namespace ProgressBar {
        const uint32_t IDS[] = {
            fw_attr::ProgressBar::min, fw_attr::ProgressBar::max, fw_attr::ProgressBar::progress,
            fw_attr::ProgressBar::secondaryProgress, fw_attr::ProgressBar::indeterminate,
            fw_attr::ProgressBar::indeterminateOnly, fw_attr::ProgressBar::indeterminateDrawable,
            fw_attr::ProgressBar::progressDrawable, fw_attr::ProgressBar::indeterminateDuration,
            fw_attr::ProgressBar::indeterminateBehavior, fw_attr::ProgressBar::minWidth,
            fw_attr::ProgressBar::maxWidth, fw_attr::ProgressBar::minHeight,
            fw_attr::ProgressBar::maxHeight, fw_attr::ProgressBar::interpolator,
            fw_attr::ProgressBar::animationResolution, fw_attr::ProgressBar::mirrorForRtl,
            fw_attr::ProgressBar::progressTint, fw_attr::ProgressBar::progressTintMode,
            fw_attr::ProgressBar::progressBackgroundTint,
            fw_attr::ProgressBar::progressBackgroundTintMode,
            fw_attr::ProgressBar::secondaryProgressTint,
            fw_attr::ProgressBar::secondaryProgressTintMode, fw_attr::ProgressBar::indeterminateTint,
            fw_attr::ProgressBar::indeterminateTintMode, fw_attr::ProgressBar::backgroundTint,
            fw_attr::ProgressBar::backgroundTintMode, 0 };
    }
    namespace RadioGroup {
        const uint32_t IDS[] = { fw_attr::RadioGroup::checkedButton, fw_attr::RadioGroup::orientation, 0 };
    }
    namespace RatingBar {
        const uint32_t IDS[] = {
            fw_attr::RatingBar::numStars, fw_attr::RatingBar::rating, fw_attr::RatingBar::stepSize,
            fw_attr::RatingBar::isIndicator, 0 };
    }
    namespace RelativeLayout {
        const uint32_t IDS[] = { fw_attr::RelativeLayout::gravity, fw_attr::RelativeLayout::ignoreGravity, 0 };
    }
    namespace RelativeLayoutLayout {
        const uint32_t IDS[] = {
            fw_attr::RelativeLayoutLayout::layout_toLeftOf,
            fw_attr::RelativeLayoutLayout::layout_toRightOf,
            fw_attr::RelativeLayoutLayout::layout_above, fw_attr::RelativeLayoutLayout::layout_below,
            fw_attr::RelativeLayoutLayout::layout_alignBaseline,
            fw_attr::RelativeLayoutLayout::layout_alignLeft,
            fw_attr::RelativeLayoutLayout::layout_alignTop,
            fw_attr::RelativeLayoutLayout::layout_alignRight,
            fw_attr::RelativeLayoutLayout::layout_alignBottom,
            fw_attr::RelativeLayoutLayout::layout_alignParentLeft,
            fw_attr::RelativeLayoutLayout::layout_alignParentTop,
            fw_attr::RelativeLayoutLayout::layout_alignParentRight,
            fw_attr::RelativeLayoutLayout::layout_alignParentBottom,
            fw_attr::RelativeLayoutLayout::layout_centerInParent,
            fw_attr::RelativeLayoutLayout::layout_centerHorizontal,
            fw_attr::RelativeLayoutLayout::layout_centerVertical,
            fw_attr::RelativeLayoutLayout::layout_alignWithParentIfMissing,
            fw_attr::RelativeLayoutLayout::layout_toStartOf,
            fw_attr::RelativeLayoutLayout::layout_toEndOf,
            fw_attr::RelativeLayoutLayout::layout_alignStart,
            fw_attr::RelativeLayoutLayout::layout_alignEnd,
            fw_attr::RelativeLayoutLayout::layout_alignParentStart,
            fw_attr::RelativeLayoutLayout::layout_alignParentEnd, 0 };
    }
    namespace ScrollView {
        const uint32_t IDS[] = { fw_attr::ScrollView::fillViewport, 0 };
    }
    namespace SeekBar {
        const uint32_t IDS[] = {
            fw_attr::SeekBar::thumb, fw_attr::SeekBar::thumbOffset, fw_attr::SeekBar::splitTrack,
            fw_attr::SeekBar::thumbTint, fw_attr::SeekBar::thumbTintMode, fw_attr::SeekBar::tickMark,
            fw_attr::SeekBar::tickMarkTint, fw_attr::SeekBar::tickMarkTintMode, 0 };
    }
    namespace Spinner {
        const uint32_t IDS[] = {
            fw_attr::Spinner::prompt, fw_attr::Spinner::spinnerMode,
            fw_attr::Spinner::dropDownSelector, fw_attr::Spinner::popupTheme,
            fw_attr::Spinner::popupBackground, fw_attr::Spinner::popupElevation,
            fw_attr::Spinner::dropDownWidth, fw_attr::Spinner::gravity, 0 };
    }
    namespace Switch {
        const uint32_t IDS[] = {
            fw_attr::Switch::thumb, fw_attr::Switch::thumbTint, fw_attr::Switch::thumbTintMode,
            fw_attr::Switch::track, fw_attr::Switch::trackTint, fw_attr::Switch::trackTintMode,
            fw_attr::Switch::textOn, fw_attr::Switch::textOff, fw_attr::Switch::thumbTextPadding,
            fw_attr::Switch::switchTextAppearance, fw_attr::Switch::switchMinWidth,
            fw_attr::Switch::switchPadding, fw_attr::Switch::splitTrack, fw_attr::Switch::showText,
            0 };
    }
    namespace TabWidget {
        const uint32_t IDS[] = {
            fw_attr::TabWidget::divider, fw_attr::TabWidget::tabStripEnabled,
            fw_attr::TabWidget::tabStripLeft, fw_attr::TabWidget::tabStripRight, 0 };
    }
    namespace TableRowLayout {
        const uint32_t IDS[] = { fw_attr::TableRowLayout::layout_column, fw_attr::TableRowLayout::layout_span, 0 };
    }
    namespace TextAppearance {
        const uint32_t IDS[] = {
            fw_attr::TextAppearance::textColor, fw_attr::TextAppearance::textSize,
            fw_attr::TextAppearance::textStyle, fw_attr::TextAppearance::textFontWeight,
            fw_attr::TextAppearance::typeface, fw_attr::TextAppearance::fontFamily,
            fw_attr::TextAppearance::textLocale, fw_attr::TextAppearance::textColorHighlight,
            fw_attr::TextAppearance::searchResultHighlightColor,
            fw_attr::TextAppearance::focusedSearchResultHighlightColor,
            fw_attr::TextAppearance::textColorHint, fw_attr::TextAppearance::textColorLink,
            fw_attr::TextAppearance::textAllCaps, fw_attr::TextAppearance::shadowColor,
            fw_attr::TextAppearance::shadowDx, fw_attr::TextAppearance::shadowDy,
            fw_attr::TextAppearance::shadowRadius, fw_attr::TextAppearance::elegantTextHeight,
            fw_attr::TextAppearance::fallbackLineSpacing, fw_attr::TextAppearance::letterSpacing,
            fw_attr::TextAppearance::fontFeatureSettings,
            fw_attr::TextAppearance::fontVariationSettings, fw_attr::TextAppearance::lineBreakStyle,
            fw_attr::TextAppearance::lineBreakWordStyle, 0 };
    }
    namespace TextClock {
        const uint32_t IDS[] = {
            fw_attr::TextClock::format12Hour, fw_attr::TextClock::format24Hour,
            fw_attr::TextClock::timeZone, 0 };
    }
    namespace TextView {
        const uint32_t IDS[] = {
            fw_attr::TextView::bufferType, fw_attr::TextView::text, fw_attr::TextView::hint,
            fw_attr::TextView::textColor, fw_attr::TextView::textColorHighlight,
            fw_attr::TextView::searchResultHighlightColor,
            fw_attr::TextView::focusedSearchResultHighlightColor, fw_attr::TextView::textColorHint,
            fw_attr::TextView::textAppearance, fw_attr::TextView::textSize,
            fw_attr::TextView::textScaleX, fw_attr::TextView::typeface, fw_attr::TextView::textStyle,
            fw_attr::TextView::textFontWeight, fw_attr::TextView::fontFamily,
            fw_attr::TextView::textLocale, fw_attr::TextView::textColorLink,
            fw_attr::TextView::cursorVisible, fw_attr::TextView::maxLines,
            fw_attr::TextView::maxHeight, fw_attr::TextView::lines, fw_attr::TextView::height,
            fw_attr::TextView::minLines, fw_attr::TextView::minHeight, fw_attr::TextView::maxEms,
            fw_attr::TextView::maxWidth, fw_attr::TextView::ems, fw_attr::TextView::width,
            fw_attr::TextView::minEms, fw_attr::TextView::minWidth, fw_attr::TextView::gravity,
            fw_attr::TextView::scrollHorizontally, fw_attr::TextView::password,
            fw_attr::TextView::singleLine, fw_attr::TextView::enabled,
            fw_attr::TextView::selectAllOnFocus, fw_attr::TextView::includeFontPadding,
            fw_attr::TextView::maxLength, fw_attr::TextView::shadowColor,
            fw_attr::TextView::shadowDx, fw_attr::TextView::shadowDy,
            fw_attr::TextView::shadowRadius, fw_attr::TextView::autoLink,
            fw_attr::TextView::linksClickable, fw_attr::TextView::numeric, fw_attr::TextView::digits,
            fw_attr::TextView::phoneNumber, fw_attr::TextView::inputMethod,
            fw_attr::TextView::capitalize, fw_attr::TextView::autoText, fw_attr::TextView::editable,
            fw_attr::TextView::freezesText, fw_attr::TextView::ellipsize,
            fw_attr::TextView::drawableTop, fw_attr::TextView::drawableBottom,
            fw_attr::TextView::drawableLeft, fw_attr::TextView::drawableRight,
            fw_attr::TextView::drawableStart, fw_attr::TextView::drawableEnd,
            fw_attr::TextView::drawablePadding, fw_attr::TextView::drawableTint,
            fw_attr::TextView::drawableTintMode, fw_attr::TextView::lineSpacingExtra,
            fw_attr::TextView::lineSpacingMultiplier, fw_attr::TextView::lineHeight,
            fw_attr::TextView::firstBaselineToTopHeight,
            fw_attr::TextView::lastBaselineToBottomHeight, fw_attr::TextView::marqueeRepeatLimit,
            fw_attr::TextView::inputType, fw_attr::TextView::allowUndo,
            fw_attr::TextView::imeOptions, fw_attr::TextView::privateImeOptions,
            fw_attr::TextView::imeActionLabel, fw_attr::TextView::imeActionId,
            fw_attr::TextView::editorExtras, fw_attr::TextView::textSelectHandleLeft,
            fw_attr::TextView::textSelectHandleRight, fw_attr::TextView::textSelectHandle,
            fw_attr::TextView::textEditPasteWindowLayout,
            fw_attr::TextView::textEditNoPasteWindowLayout,
            fw_attr::TextView::textEditSidePasteWindowLayout,
            fw_attr::TextView::textEditSideNoPasteWindowLayout,
            fw_attr::TextView::textEditSuggestionItemLayout,
            fw_attr::TextView::textEditSuggestionContainerLayout,
            fw_attr::TextView::textEditSuggestionHighlightStyle,
            fw_attr::TextView::textCursorDrawable, fw_attr::TextView::textIsSelectable,
            fw_attr::TextView::textAllCaps, fw_attr::TextView::elegantTextHeight,
            fw_attr::TextView::fallbackLineSpacing, fw_attr::TextView::letterSpacing,
            fw_attr::TextView::fontFeatureSettings, fw_attr::TextView::fontVariationSettings,
            fw_attr::TextView::breakStrategy, fw_attr::TextView::hyphenationFrequency,
            fw_attr::TextView::lineBreakStyle, fw_attr::TextView::lineBreakWordStyle,
            fw_attr::TextView::autoSizeTextType, fw_attr::TextView::autoSizeStepGranularity,
            fw_attr::TextView::autoSizePresetSizes, fw_attr::TextView::autoSizeMinTextSize,
            fw_attr::TextView::autoSizeMaxTextSize, fw_attr::TextView::justificationMode,
            fw_attr::TextView::useBoundsForWidth,
            fw_attr::TextView::shiftDrawingOffsetForStartOverhang,
            fw_attr::TextView::useLocalePreferredLineHeightForMinimum, 0 };
    }
    namespace ToggleButton {
        const uint32_t IDS[] = {
            fw_attr::ToggleButton::textOn, fw_attr::ToggleButton::textOff,
            fw_attr::ToggleButton::disabledAlpha, 0 };
    }
    namespace Toolbar {
        const uint32_t IDS[] = {
            fw_attr::Toolbar::titleTextAppearance, fw_attr::Toolbar::subtitleTextAppearance,
            fw_attr::Toolbar::title, fw_attr::Toolbar::subtitle, fw_attr::Toolbar::gravity,
            fw_attr::Toolbar::titleMargin, fw_attr::Toolbar::titleMarginStart,
            fw_attr::Toolbar::titleMarginEnd, fw_attr::Toolbar::titleMarginTop,
            fw_attr::Toolbar::titleMarginBottom, fw_attr::Toolbar::contentInsetStart,
            fw_attr::Toolbar::contentInsetEnd, fw_attr::Toolbar::contentInsetLeft,
            fw_attr::Toolbar::contentInsetRight, fw_attr::Toolbar::contentInsetStartWithNavigation,
            fw_attr::Toolbar::contentInsetEndWithActions, fw_attr::Toolbar::maxButtonHeight,
            fw_attr::Toolbar::buttonGravity, fw_attr::Toolbar::collapseIcon,
            fw_attr::Toolbar::collapseContentDescription, fw_attr::Toolbar::popupTheme,
            fw_attr::Toolbar::navigationIcon, fw_attr::Toolbar::navigationContentDescription,
            fw_attr::Toolbar::logo, fw_attr::Toolbar::logoDescription,
            fw_attr::Toolbar::titleTextColor, fw_attr::Toolbar::subtitleTextColor, 0 };
    }
    namespace View {
        const uint32_t IDS[] = {
            fw_attr::View::id, fw_attr::View::tag, fw_attr::View::scrollX, fw_attr::View::scrollY,
            fw_attr::View::background, fw_attr::View::padding, fw_attr::View::paddingHorizontal,
            fw_attr::View::paddingVertical, fw_attr::View::paddingLeft, fw_attr::View::paddingTop,
            fw_attr::View::paddingRight, fw_attr::View::paddingBottom, fw_attr::View::paddingStart,
            fw_attr::View::paddingEnd, fw_attr::View::focusable, fw_attr::View::autofillHints,
            fw_attr::View::importantForAutofill, fw_attr::View::importantForContentCapture,
            fw_attr::View::isCredential, fw_attr::View::focusableInTouchMode,
            fw_attr::View::visibility, fw_attr::View::fitsSystemWindows, fw_attr::View::scrollbars,
            fw_attr::View::scrollbarStyle, fw_attr::View::isScrollContainer,
            fw_attr::View::fadeScrollbars, fw_attr::View::scrollbarFadeDuration,
            fw_attr::View::scrollbarDefaultDelayBeforeFade, fw_attr::View::scrollbarSize,
            fw_attr::View::scrollbarThumbHorizontal, fw_attr::View::scrollbarThumbVertical,
            fw_attr::View::scrollbarTrackHorizontal, fw_attr::View::scrollbarTrackVertical,
            fw_attr::View::scrollbarAlwaysDrawHorizontalTrack,
            fw_attr::View::scrollbarAlwaysDrawVerticalTrack, fw_attr::View::fadingEdge,
            fw_attr::View::requiresFadingEdge, fw_attr::View::fadingEdgeLength,
            fw_attr::View::nextFocusLeft, fw_attr::View::nextFocusRight, fw_attr::View::nextFocusUp,
            fw_attr::View::nextFocusDown, fw_attr::View::nextFocusForward, fw_attr::View::clickable,
            fw_attr::View::longClickable, fw_attr::View::contextClickable,
            fw_attr::View::saveEnabled, fw_attr::View::filterTouchesWhenObscured,
            fw_attr::View::drawingCacheQuality, fw_attr::View::keepScreenOn,
            fw_attr::View::duplicateParentState, fw_attr::View::minHeight, fw_attr::View::minWidth,
            fw_attr::View::soundEffectsEnabled, fw_attr::View::hapticFeedbackEnabled,
            fw_attr::View::contentDescription, fw_attr::View::supplementalDescription,
            fw_attr::View::accessibilityTraversalBefore, fw_attr::View::accessibilityTraversalAfter,
            fw_attr::View::onClick, fw_attr::View::overScrollMode, fw_attr::View::alpha,
            fw_attr::View::elevation, fw_attr::View::translationX, fw_attr::View::translationY,
            fw_attr::View::translationZ, fw_attr::View::transformPivotX,
            fw_attr::View::transformPivotY, fw_attr::View::rotation, fw_attr::View::rotationX,
            fw_attr::View::rotationY, fw_attr::View::scaleX, fw_attr::View::scaleY,
            fw_attr::View::verticalScrollbarPosition, fw_attr::View::layerType,
            fw_attr::View::layoutDirection, fw_attr::View::textDirection,
            fw_attr::View::textAlignment, fw_attr::View::importantForAccessibility,
            fw_attr::View::accessibilityDataSensitive, fw_attr::View::accessibilityLiveRegion,
            fw_attr::View::labelFor, fw_attr::View::theme, fw_attr::View::transitionName,
            fw_attr::View::nestedScrollingEnabled, fw_attr::View::stateListAnimator,
            fw_attr::View::backgroundTint, fw_attr::View::backgroundTintMode,
            fw_attr::View::outlineProvider, fw_attr::View::foreground,
            fw_attr::View::foregroundGravity, fw_attr::View::foregroundTint,
            fw_attr::View::foregroundTintMode, fw_attr::View::scrollIndicators,
            fw_attr::View::pointerIcon, fw_attr::View::forceHasOverlappingRendering,
            fw_attr::View::tooltipText, fw_attr::View::keyboardNavigationCluster,
            fw_attr::View::nextClusterForward, fw_attr::View::focusedByDefault,
            fw_attr::View::defaultFocusHighlightEnabled, fw_attr::View::screenReaderFocusable,
            fw_attr::View::accessibilityPaneTitle, fw_attr::View::accessibilityHeading,
            fw_attr::View::allowClickWhenDisabled, fw_attr::View::outlineSpotShadowColor,
            fw_attr::View::outlineAmbientShadowColor, fw_attr::View::forceDarkAllowed,
            fw_attr::View::clipToOutline, fw_attr::View::preferKeepClear,
            fw_attr::View::autoHandwritingEnabled, fw_attr::View::handwritingBoundsOffsetLeft,
            fw_attr::View::handwritingBoundsOffsetTop, fw_attr::View::handwritingBoundsOffsetRight,
            fw_attr::View::handwritingBoundsOffsetBottom, fw_attr::View::contentSensitivity, 0 };
    }
    namespace ViewGroup {
        const uint32_t IDS[] = {
            fw_attr::ViewGroup::animateLayoutChanges, fw_attr::ViewGroup::clipChildren,
            fw_attr::ViewGroup::clipToPadding, fw_attr::ViewGroup::layoutAnimation,
            fw_attr::ViewGroup::animationCache, fw_attr::ViewGroup::persistentDrawingCache,
            fw_attr::ViewGroup::alwaysDrawnWithCache, fw_attr::ViewGroup::addStatesFromChildren,
            fw_attr::ViewGroup::descendantFocusability, fw_attr::ViewGroup::touchscreenBlocksFocus,
            fw_attr::ViewGroup::splitMotionEvents, fw_attr::ViewGroup::layoutMode,
            fw_attr::ViewGroup::transitionGroup, 0 };
    }
    namespace AdaptiveIconDrawableLayer {
        const uint32_t IDS[] = { fw_attr::AdaptiveIconDrawableLayer::drawable, 0 };
    }
    namespace AnimatedImageDrawable {
        const uint32_t IDS[] = {
            fw_attr::AnimatedImageDrawable::src, fw_attr::AnimatedImageDrawable::autoMirrored,
            fw_attr::AnimatedImageDrawable::repeatCount, fw_attr::AnimatedImageDrawable::autoStart,
            0 };
    }
    namespace AnimatedRotateDrawable {
        const uint32_t IDS[] = {
            fw_attr::AnimatedRotateDrawable::visible, fw_attr::AnimatedRotateDrawable::pivotX,
            fw_attr::AnimatedRotateDrawable::pivotY, fw_attr::AnimatedRotateDrawable::drawable, 0 };
    }
    namespace AnimatedStateListDrawable {
        const uint32_t IDS[] = {
            fw_attr::AnimatedStateListDrawable::visible,
            fw_attr::AnimatedStateListDrawable::variablePadding,
            fw_attr::AnimatedStateListDrawable::constantSize,
            fw_attr::AnimatedStateListDrawable::dither,
            fw_attr::AnimatedStateListDrawable::enterFadeDuration,
            fw_attr::AnimatedStateListDrawable::exitFadeDuration,
            fw_attr::AnimatedStateListDrawable::autoMirrored, 0 };
    }
    namespace AnimatedStateListDrawableItem {
        const uint32_t IDS[] = {
            fw_attr::AnimatedStateListDrawableItem::drawable,
            fw_attr::AnimatedStateListDrawableItem::id, 0 };
    }
    namespace AnimatedStateListDrawableTransition {
        const uint32_t IDS[] = {
            fw_attr::AnimatedStateListDrawableTransition::fromId,
            fw_attr::AnimatedStateListDrawableTransition::toId,
            fw_attr::AnimatedStateListDrawableTransition::drawable,
            fw_attr::AnimatedStateListDrawableTransition::reversible, 0 };
    }
    namespace AnimatedVectorDrawable {
        const uint32_t IDS[] = { fw_attr::AnimatedVectorDrawable::drawable, 0 };
    }
    namespace AnimatedVectorDrawableTarget {
        const uint32_t IDS[] = {
            fw_attr::AnimatedVectorDrawableTarget::name,
            fw_attr::AnimatedVectorDrawableTarget::animation, 0 };
    }
    namespace AnimationDrawable {
        const uint32_t IDS[] = {
            fw_attr::AnimationDrawable::visible, fw_attr::AnimationDrawable::variablePadding,
            fw_attr::AnimationDrawable::oneshot, 0 };
    }
    namespace AnimationDrawableItem {
        const uint32_t IDS[] = { fw_attr::AnimationDrawableItem::duration, fw_attr::AnimationDrawableItem::drawable, 0 };
    }
    namespace AnimationScaleListDrawable {
        const uint32_t IDS[] = { 0 };
    }
    namespace AnimationScaleListDrawableItem {
        const uint32_t IDS[] = { fw_attr::AnimationScaleListDrawableItem::drawable, 0 };
    }
    namespace BitmapDrawable {
        const uint32_t IDS[] = {
            fw_attr::BitmapDrawable::src, fw_attr::BitmapDrawable::antialias,
            fw_attr::BitmapDrawable::filter, fw_attr::BitmapDrawable::dither,
            fw_attr::BitmapDrawable::gravity, fw_attr::BitmapDrawable::tileMode,
            fw_attr::BitmapDrawable::tileModeX, fw_attr::BitmapDrawable::tileModeY,
            fw_attr::BitmapDrawable::mipMap, fw_attr::BitmapDrawable::autoMirrored,
            fw_attr::BitmapDrawable::tint, fw_attr::BitmapDrawable::tintMode,
            fw_attr::BitmapDrawable::alpha, 0 };
    }
    namespace ClipDrawable {
        const uint32_t IDS[] = {
            fw_attr::ClipDrawable::clipOrientation, fw_attr::ClipDrawable::gravity,
            fw_attr::ClipDrawable::drawable, 0 };
    }
    namespace ColorDrawable {
        const uint32_t IDS[] = { fw_attr::ColorDrawable::color, 0 };
    }
    namespace ColorStateListItem {
        const uint32_t IDS[] = {
            fw_attr::ColorStateListItem::color, fw_attr::ColorStateListItem::alpha,
            fw_attr::ColorStateListItem::lStar, 0 };
    }
    namespace Drawable {
        const uint32_t IDS[] = { fw_attr::Drawable::visible, fw_attr::Drawable::autoMirrored, 0 };
    }
    namespace DrawableCorners {
        const uint32_t IDS[] = {
            fw_attr::DrawableCorners::radius, fw_attr::DrawableCorners::topLeftRadius,
            fw_attr::DrawableCorners::topRightRadius, fw_attr::DrawableCorners::bottomLeftRadius,
            fw_attr::DrawableCorners::bottomRightRadius, 0 };
    }
    namespace DrawableWrapper {
        const uint32_t IDS[] = { fw_attr::DrawableWrapper::drawable, 0 };
    }
    namespace GradientDrawable {
        const uint32_t IDS[] = {
            fw_attr::GradientDrawable::visible, fw_attr::GradientDrawable::dither,
            fw_attr::GradientDrawable::shape, fw_attr::GradientDrawable::innerRadiusRatio,
            fw_attr::GradientDrawable::thicknessRatio, fw_attr::GradientDrawable::innerRadius,
            fw_attr::GradientDrawable::thickness, fw_attr::GradientDrawable::useLevel,
            fw_attr::GradientDrawable::tint, fw_attr::GradientDrawable::tintMode,
            fw_attr::GradientDrawable::opticalInsetLeft, fw_attr::GradientDrawable::opticalInsetTop,
            fw_attr::GradientDrawable::opticalInsetRight,
            fw_attr::GradientDrawable::opticalInsetBottom, 0 };
    }
    namespace GradientDrawableGradient {
        const uint32_t IDS[] = {
            fw_attr::GradientDrawableGradient::startColor,
            fw_attr::GradientDrawableGradient::centerColor,
            fw_attr::GradientDrawableGradient::endColor, fw_attr::GradientDrawableGradient::useLevel,
            fw_attr::GradientDrawableGradient::angle, fw_attr::GradientDrawableGradient::type,
            fw_attr::GradientDrawableGradient::centerX, fw_attr::GradientDrawableGradient::centerY,
            fw_attr::GradientDrawableGradient::gradientRadius, 0 };
    }
    namespace GradientDrawablePadding {
        const uint32_t IDS[] = {
            fw_attr::GradientDrawablePadding::left, fw_attr::GradientDrawablePadding::top,
            fw_attr::GradientDrawablePadding::right, fw_attr::GradientDrawablePadding::bottom, 0 };
    }
    namespace GradientDrawableSize {
        const uint32_t IDS[] = { fw_attr::GradientDrawableSize::width, fw_attr::GradientDrawableSize::height, 0 };
    }
    namespace GradientDrawableSolid {
        const uint32_t IDS[] = { fw_attr::GradientDrawableSolid::color, 0 };
    }
    namespace GradientDrawableStroke {
        const uint32_t IDS[] = {
            fw_attr::GradientDrawableStroke::width, fw_attr::GradientDrawableStroke::color,
            fw_attr::GradientDrawableStroke::dashWidth, fw_attr::GradientDrawableStroke::dashGap, 0 };
    }
    namespace InsetDrawable {
        const uint32_t IDS[] = {
            fw_attr::InsetDrawable::visible, fw_attr::InsetDrawable::drawable,
            fw_attr::InsetDrawable::inset, fw_attr::InsetDrawable::insetLeft,
            fw_attr::InsetDrawable::insetRight, fw_attr::InsetDrawable::insetTop,
            fw_attr::InsetDrawable::insetBottom, 0 };
    }
    namespace LayerDrawable {
        const uint32_t IDS[] = {
            fw_attr::LayerDrawable::opacity, fw_attr::LayerDrawable::autoMirrored,
            fw_attr::LayerDrawable::paddingMode, fw_attr::LayerDrawable::paddingTop,
            fw_attr::LayerDrawable::paddingBottom, fw_attr::LayerDrawable::paddingLeft,
            fw_attr::LayerDrawable::paddingRight, fw_attr::LayerDrawable::paddingStart,
            fw_attr::LayerDrawable::paddingEnd, 0 };
    }
    namespace LayerDrawableItem {
        const uint32_t IDS[] = {
            fw_attr::LayerDrawableItem::left, fw_attr::LayerDrawableItem::top,
            fw_attr::LayerDrawableItem::right, fw_attr::LayerDrawableItem::bottom,
            fw_attr::LayerDrawableItem::start, fw_attr::LayerDrawableItem::end,
            fw_attr::LayerDrawableItem::width, fw_attr::LayerDrawableItem::height,
            fw_attr::LayerDrawableItem::gravity, fw_attr::LayerDrawableItem::drawable,
            fw_attr::LayerDrawableItem::id, 0 };
    }
    namespace LevelListDrawableItem {
        const uint32_t IDS[] = {
            fw_attr::LevelListDrawableItem::minLevel, fw_attr::LevelListDrawableItem::maxLevel,
            fw_attr::LevelListDrawableItem::drawable, 0 };
    }
    namespace MaterialProgressDrawable {
        const uint32_t IDS[] = {
            fw_attr::MaterialProgressDrawable::visible, fw_attr::MaterialProgressDrawable::thickness,
            fw_attr::MaterialProgressDrawable::innerRadius, fw_attr::MaterialProgressDrawable::width,
            fw_attr::MaterialProgressDrawable::height, fw_attr::MaterialProgressDrawable::color, 0 };
    }
    namespace NinePatchDrawable {
        const uint32_t IDS[] = {
            fw_attr::NinePatchDrawable::src, fw_attr::NinePatchDrawable::dither,
            fw_attr::NinePatchDrawable::autoMirrored, fw_attr::NinePatchDrawable::tint,
            fw_attr::NinePatchDrawable::tintMode, fw_attr::NinePatchDrawable::alpha, 0 };
    }
    namespace RippleDrawable {
        const uint32_t IDS[] = {
            fw_attr::RippleDrawable::color, fw_attr::RippleDrawable::radius,
            fw_attr::RippleDrawable::effectColor, 0 };
    }
    namespace RotateDrawable {
        const uint32_t IDS[] = {
            fw_attr::RotateDrawable::visible, fw_attr::RotateDrawable::fromDegrees,
            fw_attr::RotateDrawable::toDegrees, fw_attr::RotateDrawable::pivotX,
            fw_attr::RotateDrawable::pivotY, fw_attr::RotateDrawable::drawable, 0 };
    }
    namespace ScaleDrawable {
        const uint32_t IDS[] = {
            fw_attr::ScaleDrawable::scaleWidth, fw_attr::ScaleDrawable::scaleHeight,
            fw_attr::ScaleDrawable::scaleGravity, fw_attr::ScaleDrawable::level,
            fw_attr::ScaleDrawable::drawable, fw_attr::ScaleDrawable::useIntrinsicSizeAsMinimum, 0 };
    }
    namespace ShapeDrawable {
        const uint32_t IDS[] = {
            fw_attr::ShapeDrawable::color, fw_attr::ShapeDrawable::width,
            fw_attr::ShapeDrawable::height, fw_attr::ShapeDrawable::dither,
            fw_attr::ShapeDrawable::tint, fw_attr::ShapeDrawable::tintMode, 0 };
    }
    namespace ShapeDrawablePadding {
        const uint32_t IDS[] = {
            fw_attr::ShapeDrawablePadding::left, fw_attr::ShapeDrawablePadding::top,
            fw_attr::ShapeDrawablePadding::right, fw_attr::ShapeDrawablePadding::bottom, 0 };
    }
    namespace StateListDrawable {
        const uint32_t IDS[] = {
            fw_attr::StateListDrawable::visible, fw_attr::StateListDrawable::variablePadding,
            fw_attr::StateListDrawable::constantSize, fw_attr::StateListDrawable::dither,
            fw_attr::StateListDrawable::enterFadeDuration,
            fw_attr::StateListDrawable::exitFadeDuration, fw_attr::StateListDrawable::autoMirrored,
            0 };
    }
    namespace StateListDrawableItem {
        const uint32_t IDS[] = { fw_attr::StateListDrawableItem::drawable, 0 };
    }
    namespace VectorDrawable {
        const uint32_t IDS[] = {
            fw_attr::VectorDrawable::tint, fw_attr::VectorDrawable::tintMode,
            fw_attr::VectorDrawable::autoMirrored, fw_attr::VectorDrawable::width,
            fw_attr::VectorDrawable::height, fw_attr::VectorDrawable::viewportWidth,
            fw_attr::VectorDrawable::viewportHeight, fw_attr::VectorDrawable::name,
            fw_attr::VectorDrawable::alpha, fw_attr::VectorDrawable::opticalInsetLeft,
            fw_attr::VectorDrawable::opticalInsetTop, fw_attr::VectorDrawable::opticalInsetRight,
            fw_attr::VectorDrawable::opticalInsetBottom, 0 };
    }
    namespace VectorDrawableClipPath {
        const uint32_t IDS[] = { fw_attr::VectorDrawableClipPath::name, fw_attr::VectorDrawableClipPath::pathData, 0 };
    }
    namespace VectorDrawableGroup {
        const uint32_t IDS[] = {
            fw_attr::VectorDrawableGroup::name, fw_attr::VectorDrawableGroup::rotation,
            fw_attr::VectorDrawableGroup::pivotX, fw_attr::VectorDrawableGroup::pivotY,
            fw_attr::VectorDrawableGroup::translateX, fw_attr::VectorDrawableGroup::translateY,
            fw_attr::VectorDrawableGroup::scaleX, fw_attr::VectorDrawableGroup::scaleY, 0 };
    }
    namespace VectorDrawablePath {
        const uint32_t IDS[] = {
            fw_attr::VectorDrawablePath::name, fw_attr::VectorDrawablePath::strokeWidth,
            fw_attr::VectorDrawablePath::strokeColor, fw_attr::VectorDrawablePath::strokeAlpha,
            fw_attr::VectorDrawablePath::fillColor, fw_attr::VectorDrawablePath::fillAlpha,
            fw_attr::VectorDrawablePath::pathData, fw_attr::VectorDrawablePath::trimPathStart,
            fw_attr::VectorDrawablePath::trimPathEnd, fw_attr::VectorDrawablePath::trimPathOffset,
            fw_attr::VectorDrawablePath::strokeLineCap, fw_attr::VectorDrawablePath::strokeLineJoin,
            fw_attr::VectorDrawablePath::strokeMiterLimit, fw_attr::VectorDrawablePath::fillType, 0 };
    }
} // namespace styleable
} // namespace cdroid
