// GENERATED by gen_styleable.py — do not edit by hand.
// Source: attrs.xml, attrs_cdroid.xml  (fw-ids: framework_attrids.txt)
#ifndef __FRAMEWORK_STYLEABLE_H__
#define __FRAMEWORK_STYLEABLE_H__
#include <cstdint>
#include <cstddef>
namespace cdroid {
namespace internal { namespace R { namespace styleable {
    // AbsListView (12 attrs)
    extern const uint32_t AbsListView[];
    constexpr int AbsListView_listSelector = 0;
    constexpr int AbsListView_drawSelectorOnTop = 1;
    constexpr int AbsListView_stackFromBottom = 2;
    constexpr int AbsListView_scrollingCache = 3;
    constexpr int AbsListView_textFilterEnabled = 4;
    constexpr int AbsListView_transcriptMode = 5;
    constexpr int AbsListView_cacheColorHint = 6;
    constexpr int AbsListView_fastScrollEnabled = 7;
    constexpr int AbsListView_fastScrollStyle = 8;
    constexpr int AbsListView_smoothScrollbar = 9;
    constexpr int AbsListView_choiceMode = 10;
    constexpr int AbsListView_fastScrollAlwaysVisible = 11;

    // CardView (13 attrs)
    extern const uint32_t CardView[];
    constexpr int CardView_cardBackgroundColor = 0;
    constexpr int CardView_cardCornerRadius = 1;
    constexpr int CardView_cardElevation = 2;
    constexpr int CardView_cardMaxElevation = 3;
    constexpr int CardView_cardUseCompatPadding = 4;
    constexpr int CardView_cardPreventCornerOverlap = 5;
    constexpr int CardView_contentPadding = 6;
    constexpr int CardView_contentPaddingLeft = 7;
    constexpr int CardView_contentPaddingTop = 8;
    constexpr int CardView_contentPaddingRight = 9;
    constexpr int CardView_contentPaddingBottom = 10;
    constexpr int CardView_minWidth = 11;
    constexpr int CardView_minHeight = 12;

    // ViewTag (2 attrs)
    extern const uint32_t ViewTag[];
    constexpr int ViewTag_id = 0;
    constexpr int ViewTag_value = 1;

    // Include (2 attrs)
    extern const uint32_t Include[];
    constexpr int Include_id = 0;
    constexpr int Include_visibility = 1;

    // AdapterViewAnimator (4 attrs)
    extern const uint32_t AdapterViewAnimator[];
    constexpr int AdapterViewAnimator_inAnimation = 0;
    constexpr int AdapterViewAnimator_outAnimation = 1;
    constexpr int AdapterViewAnimator_loopViews = 2;
    constexpr int AdapterViewAnimator_animateFirstView = 3;

    // AdapterViewFlipper (2 attrs)
    extern const uint32_t AdapterViewFlipper[];
    constexpr int AdapterViewFlipper_flipInterval = 0;
    constexpr int AdapterViewFlipper_autoStart = 1;

    // AnalogClock (13 attrs)
    extern const uint32_t AnalogClock[];
    constexpr int AnalogClock_dial = 0;
    constexpr int AnalogClock_hand_hour = 1;
    constexpr int AnalogClock_hand_minute = 2;
    constexpr int AnalogClock_hand_second = 3;
    constexpr int AnalogClock_timeZone = 4;
    constexpr int AnalogClock_dialTint = 5;
    constexpr int AnalogClock_dialTintMode = 6;
    constexpr int AnalogClock_hand_hourTint = 7;
    constexpr int AnalogClock_hand_hourTintMode = 8;
    constexpr int AnalogClock_hand_minuteTint = 9;
    constexpr int AnalogClock_hand_minuteTintMode = 10;
    constexpr int AnalogClock_hand_secondTint = 11;
    constexpr int AnalogClock_hand_secondTintMode = 12;

    // AlertDialog (22 attrs)
    extern const uint32_t AlertDialog[];
    constexpr int AlertDialog_fullDark = 0;
    constexpr int AlertDialog_topDark = 1;
    constexpr int AlertDialog_centerDark = 2;
    constexpr int AlertDialog_bottomDark = 3;
    constexpr int AlertDialog_fullBright = 4;
    constexpr int AlertDialog_topBright = 5;
    constexpr int AlertDialog_centerBright = 6;
    constexpr int AlertDialog_bottomBright = 7;
    constexpr int AlertDialog_bottomMedium = 8;
    constexpr int AlertDialog_centerMedium = 9;
    constexpr int AlertDialog_layout = 10;
    constexpr int AlertDialog_buttonPanelSideLayout = 11;
    constexpr int AlertDialog_listLayout = 12;
    constexpr int AlertDialog_multiChoiceItemLayout = 13;
    constexpr int AlertDialog_singleChoiceItemLayout = 14;
    constexpr int AlertDialog_listItemLayout = 15;
    constexpr int AlertDialog_progressLayout = 16;
    constexpr int AlertDialog_horizontalProgressLayout = 17;
    constexpr int AlertDialog_showTitle = 18;
    constexpr int AlertDialog_needsDefaultBackgrounds = 19;
    constexpr int AlertDialog_controllerType = 20;
    constexpr int AlertDialog_selectionScrollOffset = 21;

    // CheckedTextView (5 attrs)
    extern const uint32_t CheckedTextView[];
    constexpr int CheckedTextView_checked = 0;
    constexpr int CheckedTextView_checkMark = 1;
    constexpr int CheckedTextView_checkMarkTint = 2;
    constexpr int CheckedTextView_checkMarkTintMode = 3;
    constexpr int CheckedTextView_checkMarkGravity = 4;

    // Chronometer (2 attrs)
    extern const uint32_t Chronometer[];
    constexpr int Chronometer_format = 0;
    constexpr int Chronometer_countDown = 1;

    // CompoundButton (4 attrs)
    extern const uint32_t CompoundButton[];
    constexpr int CompoundButton_checked = 0;
    constexpr int CompoundButton_button = 1;
    constexpr int CompoundButton_buttonTint = 2;
    constexpr int CompoundButton_buttonTintMode = 3;

    // FrameLayout (1 attrs)
    extern const uint32_t FrameLayout[];
    constexpr int FrameLayout_measureAllChildren = 0;

    // GridLayout (7 attrs)
    extern const uint32_t GridLayout[];
    constexpr int GridLayout_orientation = 0;
    constexpr int GridLayout_rowCount = 1;
    constexpr int GridLayout_columnCount = 2;
    constexpr int GridLayout_useDefaultMargins = 3;
    constexpr int GridLayout_alignmentMode = 4;
    constexpr int GridLayout_rowOrderPreserved = 5;
    constexpr int GridLayout_columnOrderPreserved = 6;

    // GridLayoutLayout (7 attrs)
    extern const uint32_t GridLayoutLayout[];
    constexpr int GridLayoutLayout_layout_row = 0;
    constexpr int GridLayoutLayout_layout_rowSpan = 1;
    constexpr int GridLayoutLayout_layout_rowWeight = 2;
    constexpr int GridLayoutLayout_layout_column = 3;
    constexpr int GridLayoutLayout_layout_columnSpan = 4;
    constexpr int GridLayoutLayout_layout_columnWeight = 5;
    constexpr int GridLayoutLayout_layout_gravity = 6;

    // GridView (6 attrs)
    extern const uint32_t GridView[];
    constexpr int GridView_horizontalSpacing = 0;
    constexpr int GridView_verticalSpacing = 1;
    constexpr int GridView_stretchMode = 2;
    constexpr int GridView_columnWidth = 3;
    constexpr int GridView_numColumns = 4;
    constexpr int GridView_gravity = 5;

    // ImageView (11 attrs)
    extern const uint32_t ImageView[];
    constexpr int ImageView_src = 0;
    constexpr int ImageView_scaleType = 1;
    constexpr int ImageView_adjustViewBounds = 2;
    constexpr int ImageView_maxWidth = 3;
    constexpr int ImageView_maxHeight = 4;
    constexpr int ImageView_tint = 5;
    constexpr int ImageView_baselineAlignBottom = 6;
    constexpr int ImageView_cropToPadding = 7;
    constexpr int ImageView_baseline = 8;
    constexpr int ImageView_drawableAlpha = 9;
    constexpr int ImageView_tintMode = 10;

    // KeyboardView (12 attrs)
    extern const uint32_t KeyboardView[];
    constexpr int KeyboardView_keyboardViewStyle = 0;
    constexpr int KeyboardView_keyBackground = 1;
    constexpr int KeyboardView_keyTextSize = 2;
    constexpr int KeyboardView_labelTextSize = 3;
    constexpr int KeyboardView_keyTextColor = 4;
    constexpr int KeyboardView_keyPreviewLayout = 5;
    constexpr int KeyboardView_keyPreviewOffset = 6;
    constexpr int KeyboardView_keyPreviewHeight = 7;
    constexpr int KeyboardView_verticalCorrection = 8;
    constexpr int KeyboardView_popupLayout = 9;
    constexpr int KeyboardView_shadowColor = 10;
    constexpr int KeyboardView_shadowRadius = 11;

    // Layout (2 attrs)
    extern const uint32_t Layout[];
    constexpr int Layout_layout_width = 0;
    constexpr int Layout_layout_height = 1;

    // LinearLayout (9 attrs)
    extern const uint32_t LinearLayout[];
    constexpr int LinearLayout_orientation = 0;
    constexpr int LinearLayout_gravity = 1;
    constexpr int LinearLayout_baselineAligned = 2;
    constexpr int LinearLayout_baselineAlignedChildIndex = 3;
    constexpr int LinearLayout_weightSum = 4;
    constexpr int LinearLayout_measureWithLargestChild = 5;
    constexpr int LinearLayout_divider = 6;
    constexpr int LinearLayout_showDividers = 7;
    constexpr int LinearLayout_dividerPadding = 8;

    // LinearLayoutLayout (4 attrs)
    extern const uint32_t LinearLayoutLayout[];
    constexpr int LinearLayoutLayout_layout_width = 0;
    constexpr int LinearLayoutLayout_layout_height = 1;
    constexpr int LinearLayoutLayout_layout_weight = 2;
    constexpr int LinearLayoutLayout_layout_gravity = 3;

    // ListView (7 attrs)
    extern const uint32_t ListView[];
    constexpr int ListView_entries = 0;
    constexpr int ListView_divider = 1;
    constexpr int ListView_dividerHeight = 2;
    constexpr int ListView_headerDividersEnabled = 3;
    constexpr int ListView_footerDividersEnabled = 4;
    constexpr int ListView_overScrollHeader = 5;
    constexpr int ListView_overScrollFooter = 6;

    // MarginLayout (11 attrs)
    extern const uint32_t MarginLayout[];
    constexpr int MarginLayout_layout_width = 0;
    constexpr int MarginLayout_layout_height = 1;
    constexpr int MarginLayout_layout_margin = 2;
    constexpr int MarginLayout_layout_marginLeft = 3;
    constexpr int MarginLayout_layout_marginTop = 4;
    constexpr int MarginLayout_layout_marginRight = 5;
    constexpr int MarginLayout_layout_marginBottom = 6;
    constexpr int MarginLayout_layout_marginStart = 7;
    constexpr int MarginLayout_layout_marginEnd = 8;
    constexpr int MarginLayout_layout_marginHorizontal = 9;
    constexpr int MarginLayout_layout_marginVertical = 10;

    // NumberPicker (18 attrs)
    extern const uint32_t NumberPicker[];
    constexpr int NumberPicker_solidColor = 0;
    constexpr int NumberPicker_selectionDivider = 1;
    constexpr int NumberPicker_selectionDividerHeight = 2;
    constexpr int NumberPicker_selectionDividersDistance = 3;
    constexpr int NumberPicker_internalMinHeight = 4;
    constexpr int NumberPicker_internalMaxHeight = 5;
    constexpr int NumberPicker_internalMinWidth = 6;
    constexpr int NumberPicker_internalMaxWidth = 7;
    constexpr int NumberPicker_internalLayout = 8;
    constexpr int NumberPicker_virtualButtonPressedDrawable = 9;
    constexpr int NumberPicker_hideWheelUntilFocused = 10;
    constexpr int NumberPicker_min = 11;
    constexpr int NumberPicker_max = 12;
    constexpr int NumberPicker_value = 13;
    constexpr int NumberPicker_textColor = 14;
    constexpr int NumberPicker_textSize = 15;
    constexpr int NumberPicker_fontFamily = 16;
    constexpr int NumberPicker_itemBackground = 17;

    // PopupWindow (6 attrs)
    extern const uint32_t PopupWindow[];
    constexpr int PopupWindow_popupBackground = 0;
    constexpr int PopupWindow_popupElevation = 1;
    constexpr int PopupWindow_popupAnimationStyle = 2;
    constexpr int PopupWindow_overlapAnchor = 3;
    constexpr int PopupWindow_popupEnterTransition = 4;
    constexpr int PopupWindow_popupExitTransition = 5;

    // ProgressBar (27 attrs)
    extern const uint32_t ProgressBar[];
    constexpr int ProgressBar_min = 0;
    constexpr int ProgressBar_max = 1;
    constexpr int ProgressBar_progress = 2;
    constexpr int ProgressBar_secondaryProgress = 3;
    constexpr int ProgressBar_indeterminate = 4;
    constexpr int ProgressBar_indeterminateOnly = 5;
    constexpr int ProgressBar_indeterminateDrawable = 6;
    constexpr int ProgressBar_progressDrawable = 7;
    constexpr int ProgressBar_indeterminateDuration = 8;
    constexpr int ProgressBar_indeterminateBehavior = 9;
    constexpr int ProgressBar_minWidth = 10;
    constexpr int ProgressBar_maxWidth = 11;
    constexpr int ProgressBar_minHeight = 12;
    constexpr int ProgressBar_maxHeight = 13;
    constexpr int ProgressBar_interpolator = 14;
    constexpr int ProgressBar_animationResolution = 15;
    constexpr int ProgressBar_mirrorForRtl = 16;
    constexpr int ProgressBar_progressTint = 17;
    constexpr int ProgressBar_progressTintMode = 18;
    constexpr int ProgressBar_progressBackgroundTint = 19;
    constexpr int ProgressBar_progressBackgroundTintMode = 20;
    constexpr int ProgressBar_secondaryProgressTint = 21;
    constexpr int ProgressBar_secondaryProgressTintMode = 22;
    constexpr int ProgressBar_indeterminateTint = 23;
    constexpr int ProgressBar_indeterminateTintMode = 24;
    constexpr int ProgressBar_backgroundTint = 25;
    constexpr int ProgressBar_backgroundTintMode = 26;

    // RadioGroup (2 attrs)
    extern const uint32_t RadioGroup[];
    constexpr int RadioGroup_checkedButton = 0;
    constexpr int RadioGroup_orientation = 1;

    // RatingBar (4 attrs)
    extern const uint32_t RatingBar[];
    constexpr int RatingBar_numStars = 0;
    constexpr int RatingBar_rating = 1;
    constexpr int RatingBar_stepSize = 2;
    constexpr int RatingBar_isIndicator = 3;

    // RelativeLayout (2 attrs)
    extern const uint32_t RelativeLayout[];
    constexpr int RelativeLayout_gravity = 0;
    constexpr int RelativeLayout_ignoreGravity = 1;

    // RelativeLayoutLayout (23 attrs)
    extern const uint32_t RelativeLayoutLayout[];
    constexpr int RelativeLayoutLayout_layout_toLeftOf = 0;
    constexpr int RelativeLayoutLayout_layout_toRightOf = 1;
    constexpr int RelativeLayoutLayout_layout_above = 2;
    constexpr int RelativeLayoutLayout_layout_below = 3;
    constexpr int RelativeLayoutLayout_layout_alignBaseline = 4;
    constexpr int RelativeLayoutLayout_layout_alignLeft = 5;
    constexpr int RelativeLayoutLayout_layout_alignTop = 6;
    constexpr int RelativeLayoutLayout_layout_alignRight = 7;
    constexpr int RelativeLayoutLayout_layout_alignBottom = 8;
    constexpr int RelativeLayoutLayout_layout_alignParentLeft = 9;
    constexpr int RelativeLayoutLayout_layout_alignParentTop = 10;
    constexpr int RelativeLayoutLayout_layout_alignParentRight = 11;
    constexpr int RelativeLayoutLayout_layout_alignParentBottom = 12;
    constexpr int RelativeLayoutLayout_layout_centerInParent = 13;
    constexpr int RelativeLayoutLayout_layout_centerHorizontal = 14;
    constexpr int RelativeLayoutLayout_layout_centerVertical = 15;
    constexpr int RelativeLayoutLayout_layout_alignWithParentIfMissing = 16;
    constexpr int RelativeLayoutLayout_layout_toStartOf = 17;
    constexpr int RelativeLayoutLayout_layout_toEndOf = 18;
    constexpr int RelativeLayoutLayout_layout_alignStart = 19;
    constexpr int RelativeLayoutLayout_layout_alignEnd = 20;
    constexpr int RelativeLayoutLayout_layout_alignParentStart = 21;
    constexpr int RelativeLayoutLayout_layout_alignParentEnd = 22;

    // ScrollView (1 attrs)
    extern const uint32_t ScrollView[];
    constexpr int ScrollView_fillViewport = 0;

    // SeekBar (9 attrs)
    extern const uint32_t SeekBar[];
    constexpr int SeekBar_thumb = 0;
    constexpr int SeekBar_thumbOffset = 1;
    constexpr int SeekBar_splitTrack = 2;
    constexpr int SeekBar_useDisabledAlpha = 3;
    constexpr int SeekBar_thumbTint = 4;
    constexpr int SeekBar_thumbTintMode = 5;
    constexpr int SeekBar_tickMark = 6;
    constexpr int SeekBar_tickMarkTint = 7;
    constexpr int SeekBar_tickMarkTintMode = 8;

    // Spinner (10 attrs)
    extern const uint32_t Spinner[];
    constexpr int Spinner_prompt = 0;
    constexpr int Spinner_spinnerMode = 1;
    constexpr int Spinner_dropDownSelector = 2;
    constexpr int Spinner_popupTheme = 3;
    constexpr int Spinner_popupBackground = 4;
    constexpr int Spinner_popupElevation = 5;
    constexpr int Spinner_dropDownWidth = 6;
    constexpr int Spinner_popupPromptView = 7;
    constexpr int Spinner_gravity = 8;
    constexpr int Spinner_disableChildrenWhenDisabled = 9;

    // Switch (14 attrs)
    extern const uint32_t Switch[];
    constexpr int Switch_thumb = 0;
    constexpr int Switch_thumbTint = 1;
    constexpr int Switch_thumbTintMode = 2;
    constexpr int Switch_track = 3;
    constexpr int Switch_trackTint = 4;
    constexpr int Switch_trackTintMode = 5;
    constexpr int Switch_textOn = 6;
    constexpr int Switch_textOff = 7;
    constexpr int Switch_thumbTextPadding = 8;
    constexpr int Switch_switchTextAppearance = 9;
    constexpr int Switch_switchMinWidth = 10;
    constexpr int Switch_switchPadding = 11;
    constexpr int Switch_splitTrack = 12;
    constexpr int Switch_showText = 13;

    // TabWidget (5 attrs)
    extern const uint32_t TabWidget[];
    constexpr int TabWidget_divider = 0;
    constexpr int TabWidget_tabStripEnabled = 1;
    constexpr int TabWidget_tabStripLeft = 2;
    constexpr int TabWidget_tabStripRight = 3;
    constexpr int TabWidget_tabLayout = 4;

    // TableRowLayout (2 attrs)
    extern const uint32_t TableRowLayout[];
    constexpr int TableRowLayout_layout_column = 0;
    constexpr int TableRowLayout_layout_span = 1;

    // TextAppearance (24 attrs)
    extern const uint32_t TextAppearance[];
    constexpr int TextAppearance_textColor = 0;
    constexpr int TextAppearance_textSize = 1;
    constexpr int TextAppearance_textStyle = 2;
    constexpr int TextAppearance_textFontWeight = 3;
    constexpr int TextAppearance_typeface = 4;
    constexpr int TextAppearance_fontFamily = 5;
    constexpr int TextAppearance_textLocale = 6;
    constexpr int TextAppearance_textColorHighlight = 7;
    constexpr int TextAppearance_searchResultHighlightColor = 8;
    constexpr int TextAppearance_focusedSearchResultHighlightColor = 9;
    constexpr int TextAppearance_textColorHint = 10;
    constexpr int TextAppearance_textColorLink = 11;
    constexpr int TextAppearance_textAllCaps = 12;
    constexpr int TextAppearance_shadowColor = 13;
    constexpr int TextAppearance_shadowDx = 14;
    constexpr int TextAppearance_shadowDy = 15;
    constexpr int TextAppearance_shadowRadius = 16;
    constexpr int TextAppearance_elegantTextHeight = 17;
    constexpr int TextAppearance_fallbackLineSpacing = 18;
    constexpr int TextAppearance_letterSpacing = 19;
    constexpr int TextAppearance_fontFeatureSettings = 20;
    constexpr int TextAppearance_fontVariationSettings = 21;
    constexpr int TextAppearance_lineBreakStyle = 22;
    constexpr int TextAppearance_lineBreakWordStyle = 23;

    // TextClock (3 attrs)
    extern const uint32_t TextClock[];
    constexpr int TextClock_format12Hour = 0;
    constexpr int TextClock_format24Hour = 1;
    constexpr int TextClock_timeZone = 2;

    // TextView (106 attrs)
    extern const uint32_t TextView[];
    constexpr int TextView_bufferType = 0;
    constexpr int TextView_text = 1;
    constexpr int TextView_hint = 2;
    constexpr int TextView_textColor = 3;
    constexpr int TextView_textColorHighlight = 4;
    constexpr int TextView_searchResultHighlightColor = 5;
    constexpr int TextView_focusedSearchResultHighlightColor = 6;
    constexpr int TextView_textColorHint = 7;
    constexpr int TextView_textAppearance = 8;
    constexpr int TextView_textSize = 9;
    constexpr int TextView_textScaleX = 10;
    constexpr int TextView_typeface = 11;
    constexpr int TextView_textStyle = 12;
    constexpr int TextView_textFontWeight = 13;
    constexpr int TextView_fontFamily = 14;
    constexpr int TextView_textLocale = 15;
    constexpr int TextView_textColorLink = 16;
    constexpr int TextView_cursorVisible = 17;
    constexpr int TextView_maxLines = 18;
    constexpr int TextView_maxHeight = 19;
    constexpr int TextView_lines = 20;
    constexpr int TextView_height = 21;
    constexpr int TextView_minLines = 22;
    constexpr int TextView_minHeight = 23;
    constexpr int TextView_maxEms = 24;
    constexpr int TextView_maxWidth = 25;
    constexpr int TextView_ems = 26;
    constexpr int TextView_width = 27;
    constexpr int TextView_minEms = 28;
    constexpr int TextView_minWidth = 29;
    constexpr int TextView_gravity = 30;
    constexpr int TextView_scrollHorizontally = 31;
    constexpr int TextView_password = 32;
    constexpr int TextView_singleLine = 33;
    constexpr int TextView_enabled = 34;
    constexpr int TextView_selectAllOnFocus = 35;
    constexpr int TextView_includeFontPadding = 36;
    constexpr int TextView_maxLength = 37;
    constexpr int TextView_shadowColor = 38;
    constexpr int TextView_shadowDx = 39;
    constexpr int TextView_shadowDy = 40;
    constexpr int TextView_shadowRadius = 41;
    constexpr int TextView_autoLink = 42;
    constexpr int TextView_linksClickable = 43;
    constexpr int TextView_numeric = 44;
    constexpr int TextView_digits = 45;
    constexpr int TextView_phoneNumber = 46;
    constexpr int TextView_inputMethod = 47;
    constexpr int TextView_capitalize = 48;
    constexpr int TextView_autoText = 49;
    constexpr int TextView_editable = 50;
    constexpr int TextView_freezesText = 51;
    constexpr int TextView_ellipsize = 52;
    constexpr int TextView_drawableTop = 53;
    constexpr int TextView_drawableBottom = 54;
    constexpr int TextView_drawableLeft = 55;
    constexpr int TextView_drawableRight = 56;
    constexpr int TextView_drawableStart = 57;
    constexpr int TextView_drawableEnd = 58;
    constexpr int TextView_drawablePadding = 59;
    constexpr int TextView_drawableTint = 60;
    constexpr int TextView_drawableTintMode = 61;
    constexpr int TextView_lineSpacingExtra = 62;
    constexpr int TextView_lineSpacingMultiplier = 63;
    constexpr int TextView_lineHeight = 64;
    constexpr int TextView_firstBaselineToTopHeight = 65;
    constexpr int TextView_lastBaselineToBottomHeight = 66;
    constexpr int TextView_marqueeRepeatLimit = 67;
    constexpr int TextView_inputType = 68;
    constexpr int TextView_allowUndo = 69;
    constexpr int TextView_imeOptions = 70;
    constexpr int TextView_privateImeOptions = 71;
    constexpr int TextView_imeActionLabel = 72;
    constexpr int TextView_imeActionId = 73;
    constexpr int TextView_editorExtras = 74;
    constexpr int TextView_textSelectHandleLeft = 75;
    constexpr int TextView_textSelectHandleRight = 76;
    constexpr int TextView_textSelectHandle = 77;
    constexpr int TextView_textEditPasteWindowLayout = 78;
    constexpr int TextView_textEditNoPasteWindowLayout = 79;
    constexpr int TextView_textEditSidePasteWindowLayout = 80;
    constexpr int TextView_textEditSideNoPasteWindowLayout = 81;
    constexpr int TextView_textEditSuggestionItemLayout = 82;
    constexpr int TextView_textEditSuggestionContainerLayout = 83;
    constexpr int TextView_textEditSuggestionHighlightStyle = 84;
    constexpr int TextView_textCursorDrawable = 85;
    constexpr int TextView_textIsSelectable = 86;
    constexpr int TextView_textAllCaps = 87;
    constexpr int TextView_elegantTextHeight = 88;
    constexpr int TextView_fallbackLineSpacing = 89;
    constexpr int TextView_letterSpacing = 90;
    constexpr int TextView_fontFeatureSettings = 91;
    constexpr int TextView_fontVariationSettings = 92;
    constexpr int TextView_breakStrategy = 93;
    constexpr int TextView_hyphenationFrequency = 94;
    constexpr int TextView_lineBreakStyle = 95;
    constexpr int TextView_lineBreakWordStyle = 96;
    constexpr int TextView_autoSizeTextType = 97;
    constexpr int TextView_autoSizeStepGranularity = 98;
    constexpr int TextView_autoSizePresetSizes = 99;
    constexpr int TextView_autoSizeMinTextSize = 100;
    constexpr int TextView_autoSizeMaxTextSize = 101;
    constexpr int TextView_justificationMode = 102;
    constexpr int TextView_useBoundsForWidth = 103;
    constexpr int TextView_shiftDrawingOffsetForStartOverhang = 104;
    constexpr int TextView_useLocalePreferredLineHeightForMinimum = 105;

    // ToggleButton (3 attrs)
    extern const uint32_t ToggleButton[];
    constexpr int ToggleButton_textOn = 0;
    constexpr int ToggleButton_textOff = 1;
    constexpr int ToggleButton_disabledAlpha = 2;

    // Toolbar (28 attrs)
    extern const uint32_t Toolbar[];
    constexpr int Toolbar_titleTextAppearance = 0;
    constexpr int Toolbar_subtitleTextAppearance = 1;
    constexpr int Toolbar_title = 2;
    constexpr int Toolbar_subtitle = 3;
    constexpr int Toolbar_gravity = 4;
    constexpr int Toolbar_titleMargin = 5;
    constexpr int Toolbar_titleMarginStart = 6;
    constexpr int Toolbar_titleMarginEnd = 7;
    constexpr int Toolbar_titleMarginTop = 8;
    constexpr int Toolbar_titleMarginBottom = 9;
    constexpr int Toolbar_contentInsetStart = 10;
    constexpr int Toolbar_contentInsetEnd = 11;
    constexpr int Toolbar_contentInsetLeft = 12;
    constexpr int Toolbar_contentInsetRight = 13;
    constexpr int Toolbar_contentInsetStartWithNavigation = 14;
    constexpr int Toolbar_contentInsetEndWithActions = 15;
    constexpr int Toolbar_maxButtonHeight = 16;
    constexpr int Toolbar_navigationButtonStyle = 17;
    constexpr int Toolbar_buttonGravity = 18;
    constexpr int Toolbar_collapseIcon = 19;
    constexpr int Toolbar_collapseContentDescription = 20;
    constexpr int Toolbar_popupTheme = 21;
    constexpr int Toolbar_navigationIcon = 22;
    constexpr int Toolbar_navigationContentDescription = 23;
    constexpr int Toolbar_logo = 24;
    constexpr int Toolbar_logoDescription = 25;
    constexpr int Toolbar_titleTextColor = 26;
    constexpr int Toolbar_subtitleTextColor = 27;

    // View (123 attrs)
    extern const uint32_t View[];
    constexpr int View_id = 0;
    constexpr int View_tag = 1;
    constexpr int View_scrollX = 2;
    constexpr int View_scrollY = 3;
    constexpr int View_background = 4;
    constexpr int View_padding = 5;
    constexpr int View_paddingHorizontal = 6;
    constexpr int View_paddingVertical = 7;
    constexpr int View_paddingLeft = 8;
    constexpr int View_paddingTop = 9;
    constexpr int View_paddingRight = 10;
    constexpr int View_paddingBottom = 11;
    constexpr int View_paddingStart = 12;
    constexpr int View_paddingEnd = 13;
    constexpr int View_focusable = 14;
    constexpr int View___removed3 = 15;
    constexpr int View___removed4 = 16;
    constexpr int View___removed5 = 17;
    constexpr int View_autofillHints = 18;
    constexpr int View_importantForAutofill = 19;
    constexpr int View_importantForContentCapture = 20;
    constexpr int View_isCredential = 21;
    constexpr int View_scrollCaptureHint = 22;
    constexpr int View_focusableInTouchMode = 23;
    constexpr int View_visibility = 24;
    constexpr int View_fitsSystemWindows = 25;
    constexpr int View_scrollbars = 26;
    constexpr int View_scrollbarStyle = 27;
    constexpr int View_isScrollContainer = 28;
    constexpr int View_fadeScrollbars = 29;
    constexpr int View_scrollbarFadeDuration = 30;
    constexpr int View_scrollbarDefaultDelayBeforeFade = 31;
    constexpr int View_scrollbarSize = 32;
    constexpr int View_scrollbarThumbHorizontal = 33;
    constexpr int View_scrollbarThumbVertical = 34;
    constexpr int View_scrollbarTrackHorizontal = 35;
    constexpr int View_scrollbarTrackVertical = 36;
    constexpr int View_scrollbarAlwaysDrawHorizontalTrack = 37;
    constexpr int View_scrollbarAlwaysDrawVerticalTrack = 38;
    constexpr int View_fadingEdge = 39;
    constexpr int View_requiresFadingEdge = 40;
    constexpr int View_fadingEdgeLength = 41;
    constexpr int View_nextFocusLeft = 42;
    constexpr int View_nextFocusRight = 43;
    constexpr int View_nextFocusUp = 44;
    constexpr int View_nextFocusDown = 45;
    constexpr int View_nextFocusForward = 46;
    constexpr int View_clickable = 47;
    constexpr int View_longClickable = 48;
    constexpr int View_contextClickable = 49;
    constexpr int View_saveEnabled = 50;
    constexpr int View_filterTouchesWhenObscured = 51;
    constexpr int View_drawingCacheQuality = 52;
    constexpr int View_keepScreenOn = 53;
    constexpr int View_duplicateParentState = 54;
    constexpr int View_minHeight = 55;
    constexpr int View_minWidth = 56;
    constexpr int View_soundEffectsEnabled = 57;
    constexpr int View_hapticFeedbackEnabled = 58;
    constexpr int View_contentDescription = 59;
    constexpr int View_supplementalDescription = 60;
    constexpr int View_accessibilityTraversalBefore = 61;
    constexpr int View_accessibilityTraversalAfter = 62;
    constexpr int View_onClick = 63;
    constexpr int View_overScrollMode = 64;
    constexpr int View_alpha = 65;
    constexpr int View_elevation = 66;
    constexpr int View_translationX = 67;
    constexpr int View_translationY = 68;
    constexpr int View_translationZ = 69;
    constexpr int View_transformPivotX = 70;
    constexpr int View_transformPivotY = 71;
    constexpr int View_rotation = 72;
    constexpr int View_rotationX = 73;
    constexpr int View_rotationY = 74;
    constexpr int View_scaleX = 75;
    constexpr int View_scaleY = 76;
    constexpr int View_verticalScrollbarPosition = 77;
    constexpr int View_layerType = 78;
    constexpr int View_layoutDirection = 79;
    constexpr int View_textDirection = 80;
    constexpr int View_textAlignment = 81;
    constexpr int View_importantForAccessibility = 82;
    constexpr int View_accessibilityDataSensitive = 83;
    constexpr int View_accessibilityLiveRegion = 84;
    constexpr int View_labelFor = 85;
    constexpr int View_theme = 86;
    constexpr int View_transitionName = 87;
    constexpr int View_nestedScrollingEnabled = 88;
    constexpr int View_stateListAnimator = 89;
    constexpr int View_backgroundTint = 90;
    constexpr int View_backgroundTintMode = 91;
    constexpr int View_outlineProvider = 92;
    constexpr int View_foreground = 93;
    constexpr int View_foregroundGravity = 94;
    constexpr int View_foregroundInsidePadding = 95;
    constexpr int View_foregroundTint = 96;
    constexpr int View_foregroundTintMode = 97;
    constexpr int View_scrollIndicators = 98;
    constexpr int View_pointerIcon = 99;
    constexpr int View_forceHasOverlappingRendering = 100;
    constexpr int View_tooltipText = 101;
    constexpr int View_keyboardNavigationCluster = 102;
    constexpr int View___removed0 = 103;
    constexpr int View_nextClusterForward = 104;
    constexpr int View___removed1 = 105;
    constexpr int View_focusedByDefault = 106;
    constexpr int View_defaultFocusHighlightEnabled = 107;
    constexpr int View_screenReaderFocusable = 108;
    constexpr int View_accessibilityPaneTitle = 109;
    constexpr int View_accessibilityHeading = 110;
    constexpr int View_allowClickWhenDisabled = 111;
    constexpr int View_outlineSpotShadowColor = 112;
    constexpr int View_outlineAmbientShadowColor = 113;
    constexpr int View_forceDarkAllowed = 114;
    constexpr int View_clipToOutline = 115;
    constexpr int View_preferKeepClear = 116;
    constexpr int View_autoHandwritingEnabled = 117;
    constexpr int View_handwritingBoundsOffsetLeft = 118;
    constexpr int View_handwritingBoundsOffsetTop = 119;
    constexpr int View_handwritingBoundsOffsetRight = 120;
    constexpr int View_handwritingBoundsOffsetBottom = 121;
    constexpr int View_contentSensitivity = 122;

    // ViewGroup (13 attrs)
    extern const uint32_t ViewGroup[];
    constexpr int ViewGroup_animateLayoutChanges = 0;
    constexpr int ViewGroup_clipChildren = 1;
    constexpr int ViewGroup_clipToPadding = 2;
    constexpr int ViewGroup_layoutAnimation = 3;
    constexpr int ViewGroup_animationCache = 4;
    constexpr int ViewGroup_persistentDrawingCache = 5;
    constexpr int ViewGroup_alwaysDrawnWithCache = 6;
    constexpr int ViewGroup_addStatesFromChildren = 7;
    constexpr int ViewGroup_descendantFocusability = 8;
    constexpr int ViewGroup_touchscreenBlocksFocus = 9;
    constexpr int ViewGroup_splitMotionEvents = 10;
    constexpr int ViewGroup_layoutMode = 11;
    constexpr int ViewGroup_transitionGroup = 12;

    // ListPopupWindow (2 attrs)
    extern const uint32_t ListPopupWindow[];
    constexpr int ListPopupWindow_dropDownVerticalOffset = 0;
    constexpr int ListPopupWindow_dropDownHorizontalOffset = 1;

    // FastScroll (14 attrs)
    extern const uint32_t FastScroll[];
    constexpr int FastScroll_thumbDrawable = 0;
    constexpr int FastScroll_thumbMinWidth = 1;
    constexpr int FastScroll_thumbMinHeight = 2;
    constexpr int FastScroll_trackDrawable = 3;
    constexpr int FastScroll_backgroundRight = 4;
    constexpr int FastScroll_backgroundLeft = 5;
    constexpr int FastScroll_position = 6;
    constexpr int FastScroll_textAppearance = 7;
    constexpr int FastScroll_textColor = 8;
    constexpr int FastScroll_textSize = 9;
    constexpr int FastScroll_minWidth = 10;
    constexpr int FastScroll_minHeight = 11;
    constexpr int FastScroll_padding = 12;
    constexpr int FastScroll_thumbPosition = 13;

    // AdaptiveIconDrawableLayer (1 attrs)
    extern const uint32_t AdaptiveIconDrawableLayer[];
    constexpr int AdaptiveIconDrawableLayer_drawable = 0;

    // AnimatedImageDrawable (4 attrs)
    extern const uint32_t AnimatedImageDrawable[];
    constexpr int AnimatedImageDrawable_src = 0;
    constexpr int AnimatedImageDrawable_autoMirrored = 1;
    constexpr int AnimatedImageDrawable_repeatCount = 2;
    constexpr int AnimatedImageDrawable_autoStart = 3;

    // AnimatedRotateDrawable (6 attrs)
    extern const uint32_t AnimatedRotateDrawable[];
    constexpr int AnimatedRotateDrawable_visible = 0;
    constexpr int AnimatedRotateDrawable_frameDuration = 1;
    constexpr int AnimatedRotateDrawable_framesCount = 2;
    constexpr int AnimatedRotateDrawable_pivotX = 3;
    constexpr int AnimatedRotateDrawable_pivotY = 4;
    constexpr int AnimatedRotateDrawable_drawable = 5;

    // AnimatedStateListDrawable (7 attrs)
    extern const uint32_t AnimatedStateListDrawable[];
    constexpr int AnimatedStateListDrawable_visible = 0;
    constexpr int AnimatedStateListDrawable_variablePadding = 1;
    constexpr int AnimatedStateListDrawable_constantSize = 2;
    constexpr int AnimatedStateListDrawable_dither = 3;
    constexpr int AnimatedStateListDrawable_enterFadeDuration = 4;
    constexpr int AnimatedStateListDrawable_exitFadeDuration = 5;
    constexpr int AnimatedStateListDrawable_autoMirrored = 6;

    // AnimatedStateListDrawableItem (2 attrs)
    extern const uint32_t AnimatedStateListDrawableItem[];
    constexpr int AnimatedStateListDrawableItem_drawable = 0;
    constexpr int AnimatedStateListDrawableItem_id = 1;

    // AnimatedStateListDrawableTransition (4 attrs)
    extern const uint32_t AnimatedStateListDrawableTransition[];
    constexpr int AnimatedStateListDrawableTransition_fromId = 0;
    constexpr int AnimatedStateListDrawableTransition_toId = 1;
    constexpr int AnimatedStateListDrawableTransition_drawable = 2;
    constexpr int AnimatedStateListDrawableTransition_reversible = 3;

    // AnimatedVectorDrawable (1 attrs)
    extern const uint32_t AnimatedVectorDrawable[];
    constexpr int AnimatedVectorDrawable_drawable = 0;

    // AnimatedVectorDrawableTarget (2 attrs)
    extern const uint32_t AnimatedVectorDrawableTarget[];
    constexpr int AnimatedVectorDrawableTarget_name = 0;
    constexpr int AnimatedVectorDrawableTarget_animation = 1;

    // AnimationDrawable (3 attrs)
    extern const uint32_t AnimationDrawable[];
    constexpr int AnimationDrawable_visible = 0;
    constexpr int AnimationDrawable_variablePadding = 1;
    constexpr int AnimationDrawable_oneshot = 2;

    // AnimationDrawableItem (2 attrs)
    extern const uint32_t AnimationDrawableItem[];
    constexpr int AnimationDrawableItem_duration = 0;
    constexpr int AnimationDrawableItem_drawable = 1;

    // AnimationScaleListDrawable (0 attrs)
    extern const uint32_t AnimationScaleListDrawable[];
    constexpr int AnimationScaleListDrawable___none = 0;

    // AnimationScaleListDrawableItem (1 attrs)
    extern const uint32_t AnimationScaleListDrawableItem[];
    constexpr int AnimationScaleListDrawableItem_drawable = 0;

    // BitmapDrawable (13 attrs)
    extern const uint32_t BitmapDrawable[];
    constexpr int BitmapDrawable_src = 0;
    constexpr int BitmapDrawable_antialias = 1;
    constexpr int BitmapDrawable_filter = 2;
    constexpr int BitmapDrawable_dither = 3;
    constexpr int BitmapDrawable_gravity = 4;
    constexpr int BitmapDrawable_tileMode = 5;
    constexpr int BitmapDrawable_tileModeX = 6;
    constexpr int BitmapDrawable_tileModeY = 7;
    constexpr int BitmapDrawable_mipMap = 8;
    constexpr int BitmapDrawable_autoMirrored = 9;
    constexpr int BitmapDrawable_tint = 10;
    constexpr int BitmapDrawable_tintMode = 11;
    constexpr int BitmapDrawable_alpha = 12;

    // ClipDrawable (3 attrs)
    extern const uint32_t ClipDrawable[];
    constexpr int ClipDrawable_clipOrientation = 0;
    constexpr int ClipDrawable_gravity = 1;
    constexpr int ClipDrawable_drawable = 2;

    // ColorDrawable (1 attrs)
    extern const uint32_t ColorDrawable[];
    constexpr int ColorDrawable_color = 0;

    // ColorStateListItem (3 attrs)
    extern const uint32_t ColorStateListItem[];
    constexpr int ColorStateListItem_color = 0;
    constexpr int ColorStateListItem_alpha = 1;
    constexpr int ColorStateListItem_lStar = 2;

    // Drawable (2 attrs)
    extern const uint32_t Drawable[];
    constexpr int Drawable_visible = 0;
    constexpr int Drawable_autoMirrored = 1;

    // DrawableCorners (5 attrs)
    extern const uint32_t DrawableCorners[];
    constexpr int DrawableCorners_radius = 0;
    constexpr int DrawableCorners_topLeftRadius = 1;
    constexpr int DrawableCorners_topRightRadius = 2;
    constexpr int DrawableCorners_bottomLeftRadius = 3;
    constexpr int DrawableCorners_bottomRightRadius = 4;

    // DrawableWrapper (1 attrs)
    extern const uint32_t DrawableWrapper[];
    constexpr int DrawableWrapper_drawable = 0;

    // GradientDrawable (15 attrs)
    extern const uint32_t GradientDrawable[];
    constexpr int GradientDrawable_visible = 0;
    constexpr int GradientDrawable_dither = 1;
    constexpr int GradientDrawable_shape = 2;
    constexpr int GradientDrawable_innerRadiusRatio = 3;
    constexpr int GradientDrawable_thicknessRatio = 4;
    constexpr int GradientDrawable_innerRadius = 5;
    constexpr int GradientDrawable_thickness = 6;
    constexpr int GradientDrawable_useLevel = 7;
    constexpr int GradientDrawable_tint = 8;
    constexpr int GradientDrawable_tintMode = 9;
    constexpr int GradientDrawable_opticalInsetLeft = 10;
    constexpr int GradientDrawable_opticalInsetTop = 11;
    constexpr int GradientDrawable_opticalInsetRight = 12;
    constexpr int GradientDrawable_opticalInsetBottom = 13;
    constexpr int GradientDrawable_strokeCap = 14;

    // GradientDrawableGradient (9 attrs)
    extern const uint32_t GradientDrawableGradient[];
    constexpr int GradientDrawableGradient_startColor = 0;
    constexpr int GradientDrawableGradient_centerColor = 1;
    constexpr int GradientDrawableGradient_endColor = 2;
    constexpr int GradientDrawableGradient_useLevel = 3;
    constexpr int GradientDrawableGradient_angle = 4;
    constexpr int GradientDrawableGradient_type = 5;
    constexpr int GradientDrawableGradient_centerX = 6;
    constexpr int GradientDrawableGradient_centerY = 7;
    constexpr int GradientDrawableGradient_gradientRadius = 8;

    // GradientDrawablePadding (4 attrs)
    extern const uint32_t GradientDrawablePadding[];
    constexpr int GradientDrawablePadding_left = 0;
    constexpr int GradientDrawablePadding_top = 1;
    constexpr int GradientDrawablePadding_right = 2;
    constexpr int GradientDrawablePadding_bottom = 3;

    // GradientDrawableSize (2 attrs)
    extern const uint32_t GradientDrawableSize[];
    constexpr int GradientDrawableSize_width = 0;
    constexpr int GradientDrawableSize_height = 1;

    // GradientDrawableSolid (1 attrs)
    extern const uint32_t GradientDrawableSolid[];
    constexpr int GradientDrawableSolid_color = 0;

    // GradientDrawableStroke (4 attrs)
    extern const uint32_t GradientDrawableStroke[];
    constexpr int GradientDrawableStroke_width = 0;
    constexpr int GradientDrawableStroke_color = 1;
    constexpr int GradientDrawableStroke_dashWidth = 2;
    constexpr int GradientDrawableStroke_dashGap = 3;

    // InsetDrawable (7 attrs)
    extern const uint32_t InsetDrawable[];
    constexpr int InsetDrawable_visible = 0;
    constexpr int InsetDrawable_drawable = 1;
    constexpr int InsetDrawable_inset = 2;
    constexpr int InsetDrawable_insetLeft = 3;
    constexpr int InsetDrawable_insetRight = 4;
    constexpr int InsetDrawable_insetTop = 5;
    constexpr int InsetDrawable_insetBottom = 6;

    // LayerDrawable (9 attrs)
    extern const uint32_t LayerDrawable[];
    constexpr int LayerDrawable_opacity = 0;
    constexpr int LayerDrawable_autoMirrored = 1;
    constexpr int LayerDrawable_paddingMode = 2;
    constexpr int LayerDrawable_paddingTop = 3;
    constexpr int LayerDrawable_paddingBottom = 4;
    constexpr int LayerDrawable_paddingLeft = 5;
    constexpr int LayerDrawable_paddingRight = 6;
    constexpr int LayerDrawable_paddingStart = 7;
    constexpr int LayerDrawable_paddingEnd = 8;

    // LayerDrawableItem (11 attrs)
    extern const uint32_t LayerDrawableItem[];
    constexpr int LayerDrawableItem_left = 0;
    constexpr int LayerDrawableItem_top = 1;
    constexpr int LayerDrawableItem_right = 2;
    constexpr int LayerDrawableItem_bottom = 3;
    constexpr int LayerDrawableItem_start = 4;
    constexpr int LayerDrawableItem_end = 5;
    constexpr int LayerDrawableItem_width = 6;
    constexpr int LayerDrawableItem_height = 7;
    constexpr int LayerDrawableItem_gravity = 8;
    constexpr int LayerDrawableItem_drawable = 9;
    constexpr int LayerDrawableItem_id = 10;

    // LevelListDrawableItem (3 attrs)
    extern const uint32_t LevelListDrawableItem[];
    constexpr int LevelListDrawableItem_minLevel = 0;
    constexpr int LevelListDrawableItem_maxLevel = 1;
    constexpr int LevelListDrawableItem_drawable = 2;

    // MaterialProgressDrawable (6 attrs)
    extern const uint32_t MaterialProgressDrawable[];
    constexpr int MaterialProgressDrawable_visible = 0;
    constexpr int MaterialProgressDrawable_thickness = 1;
    constexpr int MaterialProgressDrawable_innerRadius = 2;
    constexpr int MaterialProgressDrawable_width = 3;
    constexpr int MaterialProgressDrawable_height = 4;
    constexpr int MaterialProgressDrawable_color = 5;

    // NinePatchDrawable (6 attrs)
    extern const uint32_t NinePatchDrawable[];
    constexpr int NinePatchDrawable_src = 0;
    constexpr int NinePatchDrawable_dither = 1;
    constexpr int NinePatchDrawable_autoMirrored = 2;
    constexpr int NinePatchDrawable_tint = 3;
    constexpr int NinePatchDrawable_tintMode = 4;
    constexpr int NinePatchDrawable_alpha = 5;

    // RippleDrawable (3 attrs)
    extern const uint32_t RippleDrawable[];
    constexpr int RippleDrawable_color = 0;
    constexpr int RippleDrawable_radius = 1;
    constexpr int RippleDrawable_effectColor = 2;

    // RotateDrawable (6 attrs)
    extern const uint32_t RotateDrawable[];
    constexpr int RotateDrawable_visible = 0;
    constexpr int RotateDrawable_fromDegrees = 1;
    constexpr int RotateDrawable_toDegrees = 2;
    constexpr int RotateDrawable_pivotX = 3;
    constexpr int RotateDrawable_pivotY = 4;
    constexpr int RotateDrawable_drawable = 5;

    // ScaleDrawable (6 attrs)
    extern const uint32_t ScaleDrawable[];
    constexpr int ScaleDrawable_scaleWidth = 0;
    constexpr int ScaleDrawable_scaleHeight = 1;
    constexpr int ScaleDrawable_scaleGravity = 2;
    constexpr int ScaleDrawable_level = 3;
    constexpr int ScaleDrawable_drawable = 4;
    constexpr int ScaleDrawable_useIntrinsicSizeAsMinimum = 5;

    // ShapeDrawable (6 attrs)
    extern const uint32_t ShapeDrawable[];
    constexpr int ShapeDrawable_color = 0;
    constexpr int ShapeDrawable_width = 1;
    constexpr int ShapeDrawable_height = 2;
    constexpr int ShapeDrawable_dither = 3;
    constexpr int ShapeDrawable_tint = 4;
    constexpr int ShapeDrawable_tintMode = 5;

    // ShapeDrawablePadding (4 attrs)
    extern const uint32_t ShapeDrawablePadding[];
    constexpr int ShapeDrawablePadding_left = 0;
    constexpr int ShapeDrawablePadding_top = 1;
    constexpr int ShapeDrawablePadding_right = 2;
    constexpr int ShapeDrawablePadding_bottom = 3;

    // StateListDrawable (7 attrs)
    extern const uint32_t StateListDrawable[];
    constexpr int StateListDrawable_visible = 0;
    constexpr int StateListDrawable_variablePadding = 1;
    constexpr int StateListDrawable_constantSize = 2;
    constexpr int StateListDrawable_dither = 3;
    constexpr int StateListDrawable_enterFadeDuration = 4;
    constexpr int StateListDrawable_exitFadeDuration = 5;
    constexpr int StateListDrawable_autoMirrored = 6;

    // StateListDrawableItem (1 attrs)
    extern const uint32_t StateListDrawableItem[];
    constexpr int StateListDrawableItem_drawable = 0;

    // VectorDrawable (13 attrs)
    extern const uint32_t VectorDrawable[];
    constexpr int VectorDrawable_tint = 0;
    constexpr int VectorDrawable_tintMode = 1;
    constexpr int VectorDrawable_autoMirrored = 2;
    constexpr int VectorDrawable_width = 3;
    constexpr int VectorDrawable_height = 4;
    constexpr int VectorDrawable_viewportWidth = 5;
    constexpr int VectorDrawable_viewportHeight = 6;
    constexpr int VectorDrawable_name = 7;
    constexpr int VectorDrawable_alpha = 8;
    constexpr int VectorDrawable_opticalInsetLeft = 9;
    constexpr int VectorDrawable_opticalInsetTop = 10;
    constexpr int VectorDrawable_opticalInsetRight = 11;
    constexpr int VectorDrawable_opticalInsetBottom = 12;

    // VectorDrawableClipPath (2 attrs)
    extern const uint32_t VectorDrawableClipPath[];
    constexpr int VectorDrawableClipPath_name = 0;
    constexpr int VectorDrawableClipPath_pathData = 1;

    // VectorDrawableGroup (8 attrs)
    extern const uint32_t VectorDrawableGroup[];
    constexpr int VectorDrawableGroup_name = 0;
    constexpr int VectorDrawableGroup_rotation = 1;
    constexpr int VectorDrawableGroup_pivotX = 2;
    constexpr int VectorDrawableGroup_pivotY = 3;
    constexpr int VectorDrawableGroup_translateX = 4;
    constexpr int VectorDrawableGroup_translateY = 5;
    constexpr int VectorDrawableGroup_scaleX = 6;
    constexpr int VectorDrawableGroup_scaleY = 7;

    // VectorDrawablePath (14 attrs)
    extern const uint32_t VectorDrawablePath[];
    constexpr int VectorDrawablePath_name = 0;
    constexpr int VectorDrawablePath_strokeWidth = 1;
    constexpr int VectorDrawablePath_strokeColor = 2;
    constexpr int VectorDrawablePath_strokeAlpha = 3;
    constexpr int VectorDrawablePath_fillColor = 4;
    constexpr int VectorDrawablePath_fillAlpha = 5;
    constexpr int VectorDrawablePath_pathData = 6;
    constexpr int VectorDrawablePath_trimPathStart = 7;
    constexpr int VectorDrawablePath_trimPathEnd = 8;
    constexpr int VectorDrawablePath_trimPathOffset = 9;
    constexpr int VectorDrawablePath_strokeLineCap = 10;
    constexpr int VectorDrawablePath_strokeLineJoin = 11;
    constexpr int VectorDrawablePath_strokeMiterLimit = 12;
    constexpr int VectorDrawablePath_fillType = 13;

    // DatePicker (22 attrs)
    extern const uint32_t DatePicker[];
    constexpr int DatePicker_firstDayOfWeek = 0;
    constexpr int DatePicker_minDate = 1;
    constexpr int DatePicker_maxDate = 2;
    constexpr int DatePicker_spinnersShown = 3;
    constexpr int DatePicker_calendarViewShown = 4;
    constexpr int DatePicker_internalLayout = 5;
    constexpr int DatePicker_legacyLayout = 6;
    constexpr int DatePicker_headerTextColor = 7;
    constexpr int DatePicker_headerBackground = 8;
    constexpr int DatePicker_yearListItemTextAppearance = 9;
    constexpr int DatePicker_yearListItemActivatedTextAppearance = 10;
    constexpr int DatePicker_calendarTextColor = 11;
    constexpr int DatePicker_datePickerMode = 12;
    constexpr int DatePicker_startYear = 13;
    constexpr int DatePicker_endYear = 14;
    constexpr int DatePicker_headerMonthTextAppearance = 15;
    constexpr int DatePicker_headerDayOfMonthTextAppearance = 16;
    constexpr int DatePicker_headerYearTextAppearance = 17;
    constexpr int DatePicker_dayOfWeekBackground = 18;
    constexpr int DatePicker_dayOfWeekTextAppearance = 19;
    constexpr int DatePicker_yearListSelectorColor = 20;
    constexpr int DatePicker_dialogMode = 21;

    // CalendarView (17 attrs)
    extern const uint32_t CalendarView[];
    constexpr int CalendarView_firstDayOfWeek = 0;
    constexpr int CalendarView_minDate = 1;
    constexpr int CalendarView_maxDate = 2;
    constexpr int CalendarView_monthTextAppearance = 3;
    constexpr int CalendarView_weekDayTextAppearance = 4;
    constexpr int CalendarView_dateTextAppearance = 5;
    constexpr int CalendarView_daySelectorColor = 6;
    constexpr int CalendarView_dayHighlightColor = 7;
    constexpr int CalendarView_calendarViewMode = 8;
    constexpr int CalendarView_showWeekNumber = 9;
    constexpr int CalendarView_shownWeekCount = 10;
    constexpr int CalendarView_selectedWeekBackgroundColor = 11;
    constexpr int CalendarView_focusedMonthDateColor = 12;
    constexpr int CalendarView_unfocusedMonthDateColor = 13;
    constexpr int CalendarView_weekNumberColor = 14;
    constexpr int CalendarView_weekSeparatorLineColor = 15;
    constexpr int CalendarView_selectedDateVerticalBar = 16;

    // TimePicker (14 attrs)
    extern const uint32_t TimePicker[];
    constexpr int TimePicker_legacyLayout = 0;
    constexpr int TimePicker_internalLayout = 1;
    constexpr int TimePicker_headerTextColor = 2;
    constexpr int TimePicker_headerBackground = 3;
    constexpr int TimePicker_numbersTextColor = 4;
    constexpr int TimePicker_numbersInnerTextColor = 5;
    constexpr int TimePicker_numbersBackgroundColor = 6;
    constexpr int TimePicker_numbersSelectorColor = 7;
    constexpr int TimePicker_timePickerMode = 8;
    constexpr int TimePicker_headerAmPmTextAppearance = 9;
    constexpr int TimePicker_headerTimeTextAppearance = 10;
    constexpr int TimePicker_amPmTextColor = 11;
    constexpr int TimePicker_amPmBackgroundColor = 12;
    constexpr int TimePicker_dialogMode = 13;

    // IconMenuView (5 attrs)
    extern const uint32_t IconMenuView[];
    constexpr int IconMenuView_rowHeight = 0;
    constexpr int IconMenuView_maxRows = 1;
    constexpr int IconMenuView_maxItemsPerRow = 2;
    constexpr int IconMenuView_maxItems = 3;
    constexpr int IconMenuView_moreIcon = 4;

    // MenuView (9 attrs)
    extern const uint32_t MenuView[];
    constexpr int MenuView_itemTextAppearance = 0;
    constexpr int MenuView_horizontalDivider = 1;
    constexpr int MenuView_verticalDivider = 2;
    constexpr int MenuView_headerBackground = 3;
    constexpr int MenuView_itemBackground = 4;
    constexpr int MenuView_windowAnimationStyle = 5;
    constexpr int MenuView_itemIconDisabledAlpha = 6;
    constexpr int MenuView_preserveIconSpacing = 7;
    constexpr int MenuView_subMenuArrow = 8;

    // MenuItem (23 attrs)
    extern const uint32_t MenuItem[];
    constexpr int MenuItem_id = 0;
    constexpr int MenuItem_menuCategory = 1;
    constexpr int MenuItem_orderInCategory = 2;
    constexpr int MenuItem_title = 3;
    constexpr int MenuItem_titleCondensed = 4;
    constexpr int MenuItem_icon = 5;
    constexpr int MenuItem_iconTint = 6;
    constexpr int MenuItem_iconTintMode = 7;
    constexpr int MenuItem_alphabeticShortcut = 8;
    constexpr int MenuItem_alphabeticModifiers = 9;
    constexpr int MenuItem_numericShortcut = 10;
    constexpr int MenuItem_numericModifiers = 11;
    constexpr int MenuItem_checkable = 12;
    constexpr int MenuItem_checked = 13;
    constexpr int MenuItem_visible = 14;
    constexpr int MenuItem_enabled = 15;
    constexpr int MenuItem_onClick = 16;
    constexpr int MenuItem_showAsAction = 17;
    constexpr int MenuItem_actionLayout = 18;
    constexpr int MenuItem_actionViewClass = 19;
    constexpr int MenuItem_actionProviderClass = 20;
    constexpr int MenuItem_contentDescription = 21;
    constexpr int MenuItem_tooltipText = 22;

    // CandidateView (4 attrs)
    extern const uint32_t CandidateView[];
    constexpr int CandidateView_candidate_background = 0;
    constexpr int CandidateView_candidate_normal = 1;
    constexpr int CandidateView_candidate_other = 2;
    constexpr int CandidateView_candidate_recommand = 3;

    // PlotView (5 attrs)
    extern const uint32_t PlotView[];
    constexpr int PlotView_showGrid = 0;
    constexpr int PlotView_gridColor = 1;
    constexpr int PlotView_tickLabelSize = 2;
    constexpr int PlotView_tickMarks = 3;
    constexpr int PlotView_tickLabels = 4;

    // NumberPickerCdroid (7 attrs)
    extern const uint32_t NumberPickerCdroid[];
    constexpr int NumberPickerCdroid_selectedfontFamily = 0;
    constexpr int NumberPickerCdroid_selectedTextColor = 1;
    constexpr int NumberPickerCdroid_textColor2 = 2;
    constexpr int NumberPickerCdroid_updateInputTextInFling = 3;
    constexpr int NumberPickerCdroid_wheelItemCount = 4;
    constexpr int NumberPickerCdroid_wrapSelectorWheel = 5;
    constexpr int NumberPickerCdroid_selectedTextSize = 6;

    // ChronometerCdroid (1 attrs)
    extern const uint32_t ChronometerCdroid[];
    constexpr int ChronometerCdroid_colonBlinking = 0;

    // SimpleMonthViewCdroid (1 attrs)
    extern const uint32_t SimpleMonthViewCdroid[];
    constexpr int SimpleMonthViewCdroid_dayTextAppearance = 0;

    // ScrollViewCdroid (1 attrs)
    extern const uint32_t ScrollViewCdroid[];
    constexpr int ScrollViewCdroid_scrollDuration = 0;

    // StateSetCdroid (2 attrs)
    extern const uint32_t StateSetCdroid[];
    constexpr int StateSetCdroid_state_drag_acceptable = 0;
    constexpr int StateSetCdroid_state_drag_hoved = 1;

    // Animator (9 attrs)
    extern const uint32_t Animator[];
    constexpr int Animator_interpolator = 0;
    constexpr int Animator_duration = 1;
    constexpr int Animator_startOffset = 2;
    constexpr int Animator_repeatCount = 3;
    constexpr int Animator_repeatMode = 4;
    constexpr int Animator_valueFrom = 5;
    constexpr int Animator_valueTo = 6;
    constexpr int Animator_valueType = 7;
    constexpr int Animator_removeBeforeMRelease = 8;

    // PropertyValuesHolder (4 attrs)
    extern const uint32_t PropertyValuesHolder[];
    constexpr int PropertyValuesHolder_valueType = 0;
    constexpr int PropertyValuesHolder_propertyName = 1;
    constexpr int PropertyValuesHolder_valueFrom = 2;
    constexpr int PropertyValuesHolder_valueTo = 3;

    // Keyframe (4 attrs)
    extern const uint32_t Keyframe[];
    constexpr int Keyframe_valueType = 0;
    constexpr int Keyframe_value = 1;
    constexpr int Keyframe_fraction = 2;
    constexpr int Keyframe_interpolator = 3;

    // PropertyAnimator (4 attrs)
    extern const uint32_t PropertyAnimator[];
    constexpr int PropertyAnimator_propertyName = 0;
    constexpr int PropertyAnimator_propertyXName = 1;
    constexpr int PropertyAnimator_propertyYName = 2;
    constexpr int PropertyAnimator_pathData = 3;

    // AnimatorSet (1 attrs)
    extern const uint32_t AnimatorSet[];
    constexpr int AnimatorSet_ordering = 0;

    // Animation (15 attrs)
    extern const uint32_t Animation[];
    constexpr int Animation_interpolator = 0;
    constexpr int Animation_fillEnabled = 1;
    constexpr int Animation_fillBefore = 2;
    constexpr int Animation_fillAfter = 3;
    constexpr int Animation_duration = 4;
    constexpr int Animation_startOffset = 5;
    constexpr int Animation_repeatCount = 6;
    constexpr int Animation_repeatMode = 7;
    constexpr int Animation_zAdjustment = 8;
    constexpr int Animation_background = 9;
    constexpr int Animation_detachWallpaper = 10;
    constexpr int Animation_showWallpaper = 11;
    constexpr int Animation_hasRoundedCorners = 12;
    constexpr int Animation_showBackdrop = 13;
    constexpr int Animation_backdropColor = 14;

    // AnimationSet (6 attrs)
    extern const uint32_t AnimationSet[];
    constexpr int AnimationSet_shareInterpolator = 0;
    constexpr int AnimationSet_fillBefore = 1;
    constexpr int AnimationSet_fillAfter = 2;
    constexpr int AnimationSet_duration = 3;
    constexpr int AnimationSet_startOffset = 4;
    constexpr int AnimationSet_repeatMode = 5;

    // AlphaAnimation (2 attrs)
    extern const uint32_t AlphaAnimation[];
    constexpr int AlphaAnimation_fromAlpha = 0;
    constexpr int AlphaAnimation_toAlpha = 1;

    // RotateAnimation (4 attrs)
    extern const uint32_t RotateAnimation[];
    constexpr int RotateAnimation_fromDegrees = 0;
    constexpr int RotateAnimation_toDegrees = 1;
    constexpr int RotateAnimation_pivotX = 2;
    constexpr int RotateAnimation_pivotY = 3;

    // ScaleAnimation (6 attrs)
    extern const uint32_t ScaleAnimation[];
    constexpr int ScaleAnimation_fromXScale = 0;
    constexpr int ScaleAnimation_toXScale = 1;
    constexpr int ScaleAnimation_fromYScale = 2;
    constexpr int ScaleAnimation_toYScale = 3;
    constexpr int ScaleAnimation_pivotX = 4;
    constexpr int ScaleAnimation_pivotY = 5;

    // TranslateAnimation (4 attrs)
    extern const uint32_t TranslateAnimation[];
    constexpr int TranslateAnimation_fromXDelta = 0;
    constexpr int TranslateAnimation_toXDelta = 1;
    constexpr int TranslateAnimation_fromYDelta = 2;
    constexpr int TranslateAnimation_toYDelta = 3;

    // ClipRectAnimation (8 attrs)
    extern const uint32_t ClipRectAnimation[];
    constexpr int ClipRectAnimation_fromLeft = 0;
    constexpr int ClipRectAnimation_fromTop = 1;
    constexpr int ClipRectAnimation_fromRight = 2;
    constexpr int ClipRectAnimation_fromBottom = 3;
    constexpr int ClipRectAnimation_toLeft = 4;
    constexpr int ClipRectAnimation_toTop = 5;
    constexpr int ClipRectAnimation_toRight = 6;
    constexpr int ClipRectAnimation_toBottom = 7;

    // ExtendAnimation (8 attrs)
    extern const uint32_t ExtendAnimation[];
    constexpr int ExtendAnimation_fromExtendLeft = 0;
    constexpr int ExtendAnimation_fromExtendTop = 1;
    constexpr int ExtendAnimation_fromExtendRight = 2;
    constexpr int ExtendAnimation_fromExtendBottom = 3;
    constexpr int ExtendAnimation_toExtendLeft = 4;
    constexpr int ExtendAnimation_toExtendTop = 5;
    constexpr int ExtendAnimation_toExtendRight = 6;
    constexpr int ExtendAnimation_toExtendBottom = 7;

    // AccelerateInterpolator (1 attrs)
    extern const uint32_t AccelerateInterpolator[];
    constexpr int AccelerateInterpolator_factor = 0;

    // DecelerateInterpolator (1 attrs)
    extern const uint32_t DecelerateInterpolator[];
    constexpr int DecelerateInterpolator_factor = 0;

    // CycleInterpolator (1 attrs)
    extern const uint32_t CycleInterpolator[];
    constexpr int CycleInterpolator_cycles = 0;

    // AnticipateInterpolator (1 attrs)
    extern const uint32_t AnticipateInterpolator[];
    constexpr int AnticipateInterpolator_tension = 0;

    // OvershootInterpolator (1 attrs)
    extern const uint32_t OvershootInterpolator[];
    constexpr int OvershootInterpolator_tension = 0;

    // AnticipateOvershootInterpolator (2 attrs)
    extern const uint32_t AnticipateOvershootInterpolator[];
    constexpr int AnticipateOvershootInterpolator_tension = 0;
    constexpr int AnticipateOvershootInterpolator_extraTension = 1;

    // PathInterpolator (5 attrs)
    extern const uint32_t PathInterpolator[];
    constexpr int PathInterpolator_controlX1 = 0;
    constexpr int PathInterpolator_controlY1 = 1;
    constexpr int PathInterpolator_controlX2 = 2;
    constexpr int PathInterpolator_controlY2 = 3;
    constexpr int PathInterpolator_pathData = 4;

    // DrawableContainerState (2 attrs)
    extern const uint32_t DrawableContainerState[];
    constexpr int DrawableContainerState_constantSize = 0;
    constexpr int DrawableContainerState_variablePadding = 1;

    // GradientDrawablePattern (1 attrs)
    extern const uint32_t GradientDrawablePattern[];
    constexpr int GradientDrawablePattern_pattern = 0;

    // GradientColor (12 attrs)
    extern const uint32_t GradientColor[];
    constexpr int GradientColor_startColor = 0;
    constexpr int GradientColor_centerColor = 1;
    constexpr int GradientColor_endColor = 2;
    constexpr int GradientColor_type = 3;
    constexpr int GradientColor_gradientRadius = 4;
    constexpr int GradientColor_centerX = 5;
    constexpr int GradientColor_centerY = 6;
    constexpr int GradientColor_startX = 7;
    constexpr int GradientColor_startY = 8;
    constexpr int GradientColor_endX = 9;
    constexpr int GradientColor_endY = 10;
    constexpr int GradientColor_tileMode = 11;

    // GradientColorItem (2 attrs)
    extern const uint32_t GradientColorItem[];
    constexpr int GradientColorItem_offset = 0;
    constexpr int GradientColorItem_color = 1;

    // Badge (28 attrs)
    extern const uint32_t Badge[];
    constexpr int Badge_backgroundColor = 0;
    constexpr int Badge_badgeRadius = 1;
    constexpr int Badge_badgeWithTextRadius = 2;
    constexpr int Badge_badgeWidth = 3;
    constexpr int Badge_badgeHeight = 4;
    constexpr int Badge_badgeWithTextWidth = 5;
    constexpr int Badge_badgeWithTextHeight = 6;
    constexpr int Badge_badgeTextAppearance = 7;
    constexpr int Badge_badgeText = 8;
    constexpr int Badge_badgeTextColor = 9;
    constexpr int Badge_badgeGravity = 10;
    constexpr int Badge_badgeFixedEdge = 11;
    constexpr int Badge_offsetAlignmentMode = 12;
    constexpr int Badge_badgeWidePadding = 13;
    constexpr int Badge_badgeVerticalPadding = 14;
    constexpr int Badge_horizontalOffset = 15;
    constexpr int Badge_verticalOffset = 16;
    constexpr int Badge_horizontalOffsetWithText = 17;
    constexpr int Badge_verticalOffsetWithText = 18;
    constexpr int Badge_largeFontVerticalOffsetAdjustment = 19;
    constexpr int Badge_maxCharacterCount = 20;
    constexpr int Badge_maxNumber = 21;
    constexpr int Badge_number = 22;
    constexpr int Badge_badgeShapeAppearance = 23;
    constexpr int Badge_badgeShapeAppearanceOverlay = 24;
    constexpr int Badge_badgeWithTextShapeAppearance = 25;
    constexpr int Badge_badgeWithTextShapeAppearanceOverlay = 26;
    constexpr int Badge_autoAdjustToWithinGrandparentBounds = 27;

    // ViewStub (3 attrs)
    extern const uint32_t ViewStub[];
    constexpr int ViewStub_id = 0;
    constexpr int ViewStub_layout = 1;
    constexpr int ViewStub_inflatedId = 2;

    // LayoutAnimation (4 attrs)
    extern const uint32_t LayoutAnimation[];
    constexpr int LayoutAnimation_delay = 0;
    constexpr int LayoutAnimation_animation = 1;
    constexpr int LayoutAnimation_animationOrder = 2;
    constexpr int LayoutAnimation_interpolator = 3;

    // GridLayoutAnimation (4 attrs)
    extern const uint32_t GridLayoutAnimation[];
    constexpr int GridLayoutAnimation_columnDelay = 0;
    constexpr int GridLayoutAnimation_rowDelay = 1;
    constexpr int GridLayoutAnimation_direction = 2;
    constexpr int GridLayoutAnimation_directionPriority = 3;

    // PointerIcon (3 attrs)
    extern const uint32_t PointerIcon[];
    constexpr int PointerIcon_bitmap = 0;
    constexpr int PointerIcon_hotSpotX = 1;
    constexpr int PointerIcon_hotSpotY = 2;

    // Keyboard (4 attrs)
    extern const uint32_t Keyboard[];
    constexpr int Keyboard_keyWidth = 0;
    constexpr int Keyboard_keyHeight = 1;
    constexpr int Keyboard_horizontalGap = 2;
    constexpr int Keyboard_verticalGap = 3;

    // Keyboard_Row (2 attrs)
    extern const uint32_t Keyboard_Row[];
    constexpr int Keyboard_Row_rowEdgeFlags = 0;
    constexpr int Keyboard_Row_keyboardMode = 1;

    // Keyboard_Key (12 attrs)
    extern const uint32_t Keyboard_Key[];
    constexpr int Keyboard_Key_codes = 0;
    constexpr int Keyboard_Key_popupKeyboard = 1;
    constexpr int Keyboard_Key_popupCharacters = 2;
    constexpr int Keyboard_Key_keyEdgeFlags = 3;
    constexpr int Keyboard_Key_isModifier = 4;
    constexpr int Keyboard_Key_isSticky = 5;
    constexpr int Keyboard_Key_isRepeatable = 6;
    constexpr int Keyboard_Key_iconPreview = 7;
    constexpr int Keyboard_Key_keyOutputText = 8;
    constexpr int Keyboard_Key_keyLabel = 9;
    constexpr int Keyboard_Key_keyIcon = 10;
    constexpr int Keyboard_Key_keyboardMode = 11;

    // MenuGroup (6 attrs)
    extern const uint32_t MenuGroup[];
    constexpr int MenuGroup_id = 0;
    constexpr int MenuGroup_menuCategory = 1;
    constexpr int MenuGroup_orderInCategory = 2;
    constexpr int MenuGroup_checkableBehavior = 3;
    constexpr int MenuGroup_visible = 4;
    constexpr int MenuGroup_enabled = 5;

    // GestureOverlayView (12 attrs)
    extern const uint32_t GestureOverlayView[];
    constexpr int GestureOverlayView_gestureStrokeWidth = 0;
    constexpr int GestureOverlayView_gestureColor = 1;
    constexpr int GestureOverlayView_uncertainGestureColor = 2;
    constexpr int GestureOverlayView_fadeOffset = 3;
    constexpr int GestureOverlayView_fadeDuration = 4;
    constexpr int GestureOverlayView_gestureStrokeType = 5;
    constexpr int GestureOverlayView_gestureStrokeLengthThreshold = 6;
    constexpr int GestureOverlayView_gestureStrokeSquarenessThreshold = 7;
    constexpr int GestureOverlayView_gestureStrokeAngleThreshold = 8;
    constexpr int GestureOverlayView_eventsInterceptionEnabled = 9;
    constexpr int GestureOverlayView_fadeEnabled = 10;
    constexpr int GestureOverlayView_orientation = 11;

} } } // namespace internal::R::styleable
} // namespace cdroid
#endif // __FRAMEWORK_STYLEABLE_H__
