#pragma once

/*Generated by machine ,Do not edit!!!*/

namespace cdroid{

class R{
public:
    enum id {
        parentPanel             = 0x000003E8 /*      1000*/ ,
        topPanel                = 0x000003E9 /*      1001*/ ,
        title_template          = 0x000003EA /*      1002*/ ,
        icon                    = 0x000003EB /*      1003*/ ,
        alertTitle              = 0x000003EC /*      1004*/ ,
        titleDivider            = 0x000003ED /*      1005*/ ,
        contentPanel            = 0x000003EE /*      1006*/ ,
        scrollView              = 0x000003EF /*      1007*/ ,
        message                 = 0x000003F0 /*      1008*/ ,
        customPanel             = 0x000003F1 /*      1009*/ ,
        custom                  = 0x000003F2 /*      1010*/ ,
        buttonPanel             = 0x000003F3 /*      1011*/ ,
        leftSpacer              = 0x000003F4 /*      1012*/ ,
        button1                 = 0x000003F5 /*      1013*/ ,
        button3                 = 0x000003F6 /*      1014*/ ,
        button2                 = 0x000003F7 /*      1015*/ ,
        rightSpacer             = 0x000003F8 /*      1016*/ ,
        titleDividerNoCustom    = 0x000003F9 /*      1017*/ ,
        text1                   = 0x000003FA /*      1018*/ ,
        select_dialog_listview  = 0x000003FB /*      1019*/ ,
        increment               = 0x000003FC /*      1020*/ ,
        numberpicker_input      = 0x000003FD /*      1021*/ ,
        decrement               = 0x000003FE /*      1022*/ ,
        textSpacerNoTitle       = 0x000003FF /*      1023*/ ,
        textSpacerNoButtons     = 0x00000400 /*      1024*/ ,
        titleDividerTop         = 0x00000401 /*      1025*/ ,
        background              = 0x00000402 /*      1026*/ ,
        progress                = 0x00000403 /*      1027*/ ,
        secondaryProgress       = 0x00000404 /*      1028*/
    };//endof enum id

};//endof class R

}//endof namespace

