#pragma once

/*Generated by machine ,Do not edit!!!*/

namespace cdroid{

class R{
public:
    class id {
    public: enum{
         background              = 0x000003E8 /*      1000*/,
         progress                = 0x000003E9 /*      1001*/,
         secondaryProgress       = 0x000003EA /*      1002*/,
         parentPanel             = 0x000003EB /*      1003*/,
         topPanel                = 0x000003EC /*      1004*/,
         titleDividerTop         = 0x000003ED /*      1005*/,
         title_template          = 0x000003EE /*      1006*/,
         icon                    = 0x000003EF /*      1007*/,
         alertTitle              = 0x000003F0 /*      1008*/,
         titleDivider            = 0x000003F1 /*      1009*/,
         contentPanel            = 0x000003F2 /*      1010*/,
         scrollView              = 0x000003F3 /*      1011*/,
         message                 = 0x000003F4 /*      1012*/,
         customPanel             = 0x000003F5 /*      1013*/,
         custom                  = 0x000003F6 /*      1014*/,
         buttonPanel             = 0x000003F7 /*      1015*/,
         button2                 = 0x000003F8 /*      1016*/,
         button3                 = 0x000003F9 /*      1017*/,
         button1                 = 0x000003FA /*      1018*/,
         text1                   = 0x000003FB /*      1019*/,
         titleDividerNoCustom    = 0x000003FC /*      1020*/,
         textSpacerNoTitle       = 0x000003FD /*      1021*/,
         textSpacerNoButtons     = 0x000003FE /*      1022*/,
         increment               = 0x000003FF /*      1023*/,
         numberpicker_input      = 0x00000400 /*      1024*/,
         decrement               = 0x00000401 /*      1025*/,
         leftSpacer              = 0x00000402 /*      1026*/,
         rightSpacer             = 0x00000403 /*      1027*/,
         select_dialog_listview  = 0x00000404 /*      1028*/
    };};//endof class&enum id

};//endof class R

}//endof namespace

