#pragma once

/*Generated by machine ,Do not edit !!!*/

namespace cdroid{

namespace R{
    namespace id{
         static constexpr int background              = 0x000003E8 ;/*1000*/
         static constexpr int toggle                  = 0x000003E9 ;/*1001*/
         static constexpr int progress                = 0x000003EA ;/*1002*/
         static constexpr int secondaryProgress       = 0x000003EB ;/*1003*/
         static constexpr int off                     = 0x000003EC ;/*1004*/
         static constexpr int on                      = 0x000003ED ;/*1005*/
         static constexpr int parentPanel             = 0x000003EE ;/*1006*/
         static constexpr int topPanel                = 0x000003EF ;/*1007*/
         static constexpr int title_template          = 0x000003F0 ;/*1008*/
         static constexpr int icon                    = 0x000003F1 ;/*1009*/
         static constexpr int alertTitle              = 0x000003F2 ;/*1010*/
         static constexpr int titleDivider            = 0x000003F3 ;/*1011*/
         static constexpr int contentPanel            = 0x000003F4 ;/*1012*/
         static constexpr int scrollView              = 0x000003F5 ;/*1013*/
         static constexpr int message                 = 0x000003F6 ;/*1014*/
         static constexpr int customPanel             = 0x000003F7 ;/*1015*/
         static constexpr int custom                  = 0x000003F8 ;/*1016*/
         static constexpr int buttonPanel             = 0x000003F9 ;/*1017*/
         static constexpr int leftSpacer              = 0x000003FA ;/*1018*/
         static constexpr int button1                 = 0x000003FB ;/*1019*/
         static constexpr int button3                 = 0x000003FC ;/*1020*/
         static constexpr int button2                 = 0x000003FD ;/*1021*/
         static constexpr int rightSpacer             = 0x000003FE ;/*1022*/
         static constexpr int titleDividerTop         = 0x000003FF ;/*1023*/
         static constexpr int textSpacerNoTitle       = 0x00000400 ;/*1024*/
         static constexpr int textSpacerNoButtons     = 0x00000401 ;/*1025*/
         static constexpr int progress_percent        = 0x00000402 ;/*1026*/
         static constexpr int progress_number         = 0x00000403 ;/*1027*/
         static constexpr int titleDividerNoCustom    = 0x00000404 ;/*1028*/
         static constexpr int predict2                = 0x00000405 ;/*1029*/
         static constexpr int closekeyboard           = 0x00000406 ;/*1030*/
         static constexpr int predict1                = 0x00000407 ;/*1031*/
         static constexpr int keyboardview            = 0x00000408 ;/*1032*/
         static constexpr int prev                    = 0x00000409 ;/*1033*/
         static constexpr int rew                     = 0x0000040A ;/*1034*/
         static constexpr int pause                   = 0x0000040B ;/*1035*/
         static constexpr int ffwd                    = 0x0000040C ;/*1036*/
         static constexpr int next                    = 0x0000040D ;/*1037*/
         static constexpr int time_current            = 0x0000040E ;/*1038*/
         static constexpr int mediacontroller_progress= 0x0000040F ;/*1039*/
         static constexpr int time                    = 0x00000410 ;/*1040*/
         static constexpr int increment               = 0x00000411 ;/*1041*/
         static constexpr int numberpicker_input      = 0x00000412 ;/*1042*/
         static constexpr int decrement               = 0x00000413 ;/*1043*/
         static constexpr int body                    = 0x00000414 ;/*1044*/
         static constexpr int select_dialog_listview  = 0x00000415 ;/*1045*/
         static constexpr int text1                   = 0x00000416 ;/*1046*/
    };/*namespace id*/

    namespace strings{
    };/*namespace strings*/

};//endof namespace R

}//endof namespace

