/*********************************************************************************
 * Copyright (C) [2019] [houzh@msn.com]
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *********************************************************************************/
#ifndef __CDROID_PREFERENCE_SCREEN_H__
#define __CDROID_PREFERENCE_SCREEN_H__

#include <preference/preferencegroup.h>

namespace cdroid {

class PreferenceManager;

/**
 * Port of androidx.preference.PreferenceScreen — a top-level container that
 * represents a settings screen. This is the root component of your Preference
 * hierarchy.
 */
class PreferenceScreen final : public PreferenceGroup {
public:
    PreferenceScreen(Context& context, const AttributeSet& attrs);

    void onClick() override;

    bool isOnSameScreenAsChildren() const override;

    /**
     * See #setShouldUseGeneratedIds(boolean)
     */
    bool shouldUseGeneratedIds() const;

    /**
     * Set whether the adapter created for this screen should attempt to use
     * the preference IDs generated by PreferenceGroup#addPreference as stable
     * item IDs.
     */
    void setShouldUseGeneratedIds(bool shouldUseGeneratedIds);

    std::string getPreferenceClassName() const override { return "PreferenceScreen"; }

private:
    bool mShouldUseGeneratedIds = true;
};

} // namespace cdroid

#endif // __CDROID_PREFERENCE_SCREEN_H__
