find_package(PkgConfig)
pkg_check_modules(PC_JPEG  libjpeg)

find_path(JPEG_INCLUDE_DIRS
    NAMES jpeglib.h
    HINTS ${PC_JPEG_INCLUDEDIR}
    ${PC_JPEG_INCLUDE_DIRS}
)

find_library(JPEG_LIBRARIES
    NAMES jpeg
    HINTS ${PC_JPEG_LIBDIR}
    ${PC_JPEG_LIBRARY_DIRS}
)

if(JPEG_INCLUDE_DIRS AND JPEG_LIBRARIES)
    set(JPEG_FOUND TRUE)
    set(JPEG_LIBRARY ${JPEG_LIBRARIES})
    set(JPEG_INCLUDE_DIR ${JPEG_INCLUDE_DIRS})
    set(JPEG_VERSION ${PC_JPEG_VERSION})

   if(NOT TARGET JPEG::JPEG)
     add_library(JPEG::JPEG UNKNOWN IMPORTED)
     if(JPEG_INCLUDE_DIRS)
       set_target_properties(JPEG::JPEG PROPERTIES
         INTERFACE_INCLUDE_DIRECTORIES "${JPEG_INCLUDE_DIRS}")
     endif()
     if(EXISTS "${JPEG_LIBRARY}")
       set_target_properties(JPEG::JPEG PROPERTIES
         IMPORTED_LINK_INTERFACE_LANGUAGES "C"
         IMPORTED_LOCATION "${JPEG_LIBRARY}")
     endif()
     if(EXISTS "${JPEG_LIBRARY_RELEASE}")
       set_property(TARGET JPEG::JPEG APPEND PROPERTY
         IMPORTED_CONFIGURATIONS RELEASE)
       set_target_properties(JPEG::JPEG PROPERTIES
         IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
         IMPORTED_LOCATION_RELEASE "${JPEG_LIBRARY_RELEASE}")
     endif()
     if(EXISTS "${JPEG_LIBRARY_DEBUG}")
       set_property(TARGET JPEG::JPEG APPEND PROPERTY
         IMPORTED_CONFIGURATIONS DEBUG)
       set_target_properties(JPEG::JPEG PROPERTIES
         IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
         IMPORTED_LOCATION_DEBUG "${JPEG_LIBRARY_DEBUG}")
     endif()
   endif()
endif()

#message("JPEG_LIBRARIES=${JPEG_LIBRARIES} JPEG_FOUND=${JPEG_FOUND}")
include(FindPackageHandleStandardArgs)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(JPEG REQUIRED_VARS JPEG_INCLUDE_DIRS JPEG_LIBRARIES 
#	FOUND_VAR JPEG_FOUND VERSION_VAR JPEG_VERSION)

mark_as_advanced(JPEG_LIBRARIES JPEG_LIBRARY JPEG_INCLUDE_DIRS JPEG_INCLUDE_DIR JPEG_FOUND)

