find_package(PkgConfig)
pkg_check_modules(PC_LUNASVG  lunasvg)

find_path(LUNASVG_INCLUDE_DIRS
    NAMES lunasvg.h
    HINTS ${PC_LUNASVG_INCLUDEDIR}
    ${PC_LUNASVG_INCLUDE_DIRS}
)

find_library(LUNASVG_LIBRARIES
    NAMES lunasvg
    HINTS ${PC_LUNASVG_LIBDIR}
    ${PC_LUNASVG_LIBRARY_DIRS}
)

if(LUNASVG_INCLUDE_DIRS AND LUNASVG_LIBRARIES)
    set(LUNASVG_FOUND TRUE)
    set(LUNASVG_LIBRARY ${LUNASVG_LIBRARIES})
    set(LUNASVG_INCLUDE_DIR ${LUNASVG_INCLUDE_DIRS})
    set(LUNASVG_VERSION ${PC_LUNASVG_VERSION})
endif()

include(FindPackageHandleStandardArgs)
mark_as_advanced(LUNASVG_LIBRARIES LUNASVG_LIBRARY LUNASVG_INCLUDE_DIRS LUNASVG_INCLUDE_DIR LUNASVG_FOUND)

