
find_package(PkgConfig)
pkg_check_modules(PC_EXPAT expat)

find_path(EXPAT_INCLUDE_DIR
    NAMES expat.h
    HINTS ${PC_EXPAT_INCLUDE_DIRS}
    ${PC_EXPAT_INCLUDEDIR}
)

find_library(EXPAT_LIBRARY
    NAMES expat
    HINTS ${PC_EXPAT_LIBDIR}
    ${PC_EXPAT_LIBRARY_DIRS}
)

if(EXPAT_INCLUDE_DIR AND NOT EXPAT_LIBRARY)
    set(EXPAT_LIBRARY "-L${CMAKE_INSTALL_PREFIX}/lib -lexpat")
endif()
if(EXPAT_INCLUDE_DIR AND EXPAT_LIBRARY)
    set(EXPAT_FOUND TRUE)
    set(EXPAT_INCLUDE_DIRS ${EXPAT_INCLUDE_DIR})
    set(EXPAT_LIBRARIES ${EXPAT_LIBRARY})
    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(expat  EXPAT_LIBRARIES EXPAT_LIBRARY EXPAT_INCLUDE_DIRS EXPAT_INCLUDE_DIR)
    mark_as_advanced(EXPAT_LIBRARIES EXPAT_LIBRARY EXPAT_INCLUDE_DIRS EXPAT_INCLUDE_DIR)
endif()
#message(FATAL_ERROR "EXPAT_LIBRARY=${EXPAT_LIBRARY}") 

