
find_package(PkgConfig)
pkg_check_modules(PC_WEBP libwebpmux)

find_path(WEBP_INCLUDE_DIR
    NAMES demux.h
    HINTS ${PC_WEBP_INCLUDE_DIRS}
    ${PC_WEBP_INCLUDEDIR}
)

find_library(WEBP_LIBRARY
    NAMES webpdemux
    HINTS ${PC_WEBP_LIBDIR}
    ${PC_WEBP_LIBRARY_DIRS}
)

if(WEBP_INCLUDE_DIR AND WEBP_LIBRARY)
    set(WEBP_FOUND TRUE)
    set(WEBP_INCLUDE_DIRS ${WEBP_INCLUDE_DIR})
    set(WEBP_LIBRARIES ${WEBP_LIBRARY})
    set(WEBP_VERSION ${PC_WEBP_VERSION})
    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(WEBP  FOUND_VAR WEBP_FOUND VERSION_VAR WEBP_VERSION 
	    REQUIRED_VARS WEBP_LIBRARIES WEBP_LIBRARY WEBP_INCLUDE_DIRS WEBP_INCLUDE_DIR)
    mark_as_advanced(WEBP_LIBRARIES WEBP_LIBRARY WEBP_INCLUDE_DIRS WEBP_INCLUDE_DIR)
endif()

