if (ENABLE_WEARABLE_WIDGETS)
SET(WEAR_SOURCES
    widgetEx/wear/arclayout.cc
    widgetEx/wear/boxinsetlayout.cc
    widgetEx/wear/roundeddrawable.cc
    widgetEx/wear/scrollmanager.cc
    widgetEx/wear/progressdrawable.cc
    widgetEx/wear/backbuttondismisscontroller.cc
    widgetEx/wear/circularprogresslayoutcontroller.cc
    widgetEx/wear/circularprogressdrawable.cc
    widgetEx/wear/circularprogresslayout.cc
    widgetEx/wear/wearablerecyclerview.cc
    widgetEx/wear/dismissibleframelayout.cc
    widgetEx/wear/swipedismisscontroller.cc
    widgetEx/wear/curvinglayoutcallback.cc
    widgetEx/wear/swipedismissframelayout.cc
    widgetEx/wear/swipedismisstransitionhelper.cc
    widgetEx/wear/wearablelinearlayoutmanager.cc
    widgetEx/wear/confirmationoverlay.cc
    widgetEx/wear/resourcesutil.cc
    widgetEx/wear/simpleanimatorlistener.cc
    widgetEx/wear/wearabledrawerlayout.cc
    widgetEx/wear/wearabledrawercontroller.cc
    widgetEx/wear/wearabledrawerview.cc
    widgetEx/wear/flingwatcherfactory.cc
    widgetEx/wear/recyclerviewflingwatcher.cc
    widgetEx/wear/abslistviewflingwatcher.cc
    widgetEx/wear/scrollviewflingwatcher.cc
    widgetEx/wear/nestedscrollviewflingwatcher.cc
    widgetEx/wear/circledimageview.cc
    widgetEx/wear/pageindicatorview.cc
    widgetEx/wear/wearabledraweractionmenu.cc
    widgetEx/wear/wearabledraweractionview.cc
    widgetEx/wear/wearablenavigationdraweradapter.cc
    widgetEx/wear/wearablenavigationdrawerview.cc
    widgetEx/wear/singlepagepresenter.cc
    widgetEx/wear/singlepageui.cc
    widgetEx/wear/multipagepresenter.cc
    widgetEx/wear/multipageui.cc
    widgetEx/wear/curvedtextview.cc
)
endif(ENABLE_WEARABLE_WIDGETS)
