#pragma once

/*Generated by machine ,Do not edit !!!*/

namespace w9{

namespace R{
    namespace id{
         static constexpr int horizontalScroll        = 0x00002710 ;/*10000*/
         static constexpr int linearLayout            = 0x00002711 ;/*10001*/
         static constexpr int relativeLayout          = 0x00002712 ;/*10002*/
         static constexpr int temp                    = 0x00002713 ;/*10003*/
         static constexpr int tips                    = 0x00002714 ;/*10004*/
         static constexpr int often                   = 0x00002715 ;/*10005*/
         static constexpr int care                    = 0x00002716 ;/*10006*/
         static constexpr int favorite                = 0x00002717 ;/*10007*/
         static constexpr int options                 = 0x00002718 ;/*10008*/
         static constexpr int text1                   = 0x00002719 ;/*10009*/
         static constexpr int text2                   = 0x0000271A ;/*10010*/
         static constexpr int content                 = 0x0000271B ;/*10011*/
         static constexpr int optionsContainer        = 0x0000271C ;/*10012*/
    };/*namespace id*/

    namespace strings{
          static constexpr int weathertips             = 0x00002710 ;/*10000*/
    };/*namespace strings*/

};//endof namespace R

}//endof namespace

